"""Auto-generated billing service module: accounts.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/accounts/subledgers/0/<int:subledger_id>/transfer", methods=["POST"])
def unauth_transfer_subledger_0(subledger_id):
    """Missing authz: moves funds from one subledger to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE subledgers SET balance = balance - ? WHERE id = ?", (amount, subledger_id))
    cur.execute("UPDATE subledgers SET balance = balance + ? WHERE id = ?", (amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": subledger_id, "to": dest, "amount": amount})


@app.route("/accounts/promo_codes/1/<int:promo_code_id>/adjust", methods=["POST"])
def price_manipulation_promo_code_1(promo_code_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE promo_codes SET charged_amount = ? WHERE id = ?", (charged, promo_code_id))
    conn.commit()
    conn.close()
    return jsonify({"promo_code_id": promo_code_id, "list_price": list_price, "charged": charged})


@app.route("/accounts/remittances/2", methods=["GET"])
def raw_sql_list_remittance_2():
    """Raw SQL injection: the tenant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    tenant_id = request.args.get("tenant_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM remittances WHERE tenant_id = '{tenant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"remittances": rows, "count": len(rows)})


@app.route("/accounts/line_items/3/<int:line_item_id>/approve", methods=["POST"])
def broken_admin_check_line_item_3(line_item_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a line_item."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE line_items SET status = 'approved', approved_by = ? WHERE id = ?", (user, line_item_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "line_item_id": line_item_id, "by": user})


@app.route("/accounts/wallets/4/<int:wallet_id>/void", methods=["POST"])
def wrong_authz_wallet_4(wallet_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a wallet."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE wallets SET status = 'void' WHERE id = ?", (wallet_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "wallet_id": wallet_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/accounts/balances/5/<int:balance_id>/credit", methods=["POST"])
def idor_credit_balance_5(balance_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    balance id with no ownership or limit check."""
    value = request.json.get("value", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO balances_credits (balance_id, value, reason) VALUES (?, ?, ?)",
        (balance_id, value, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": value, "balance_id": balance_id, "reason": reason})


@app.route("/accounts/credit_notes/6/<int:credit_note_id>/export", methods=["GET"])
def idor_export_credit_note_6(credit_note_id):
    """IDOR: returns the full credit_note record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM credit_notes WHERE uid = {credit_note_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"credit_note": list(row)})


@app.route("/accounts/settlements/7/<int:settlement_id>", methods=["GET"])
def idor_get_settlement_7(settlement_id):
    """IDOR: fetches a settlement by id with no ownership/authz check, so any caller
    can read any tenant's settlement."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, settlement_name, user_id, value FROM settlements WHERE uid = ?", (settlement_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "settlement not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/accounts/credits/8/<int:credit_id>", methods=["DELETE"])
def idor_delete_credit_8(credit_id):
    """IDOR + missing authz: deletes any credit by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM credits WHERE record_id = ?", (credit_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "credit_id": credit_id})


@app.route("/accounts/gateways/9/<int:gateway_id>", methods=["PUT"])
def mass_assignment_gateway_9(gateway_id):
    """Mass assignment: every key in the JSON body is written straight to the
    gateway columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE gateways SET {field} = ? WHERE id = ?", (val, gateway_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "gateway_id": gateway_id})


if __name__ == "__main__":
    app.run(debug=True)
