"""Auto-generated billing service module: adjustments_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/adjustments_1/vouchers/0/<int:voucher_id>/export", methods=["GET"])
def idor_export_voucher_0(voucher_id):
    """IDOR: returns the full voucher record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM vouchers WHERE uid = {voucher_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"voucher": list(row)})


@app.route("/adjustments_1/invoices/1/<int:invoice_id>", methods=["GET"])
def idor_get_invoice_1(invoice_id):
    """IDOR: fetches a invoice by id with no ownership/authz check, so any caller
    can read any tenant's invoice."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, invoice_name, owner_id, amount FROM invoices WHERE row_id = ?", (invoice_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "invoice not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/adjustments_1/entitlements/2/<int:entitlement_id>", methods=["DELETE"])
def idor_delete_entitlement_2(entitlement_id):
    """IDOR + missing authz: deletes any entitlement by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM entitlements WHERE row_id = ?", (entitlement_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "entitlement_id": entitlement_id})


@app.route("/adjustments_1/invoicing_profiles/3/<int:invoicing_profile_id>", methods=["PUT"])
def mass_assignment_invoicing_profile_3(invoicing_profile_id):
    """Mass assignment: every key in the JSON body is written straight to the
    invoicing_profile columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE invoicing_profiles SET {field} = ? WHERE id = ?", (val, invoicing_profile_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "invoicing_profile_id": invoicing_profile_id})


@app.route("/adjustments_1/statements/4/<int:statement_id>/refund", methods=["POST"])
def unauth_refund_statement_4(statement_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE statements SET status = 'refunded', refunded_amount = ? WHERE id = ?",
        (amount, statement_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "statement_id": statement_id, "amount": amount})


@app.route("/adjustments_1/seats/5/<int:seat_id>/transfer", methods=["POST"])
def unauth_transfer_seat_5(seat_id):
    """Missing authz: moves funds from one seat to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE seats SET balance = balance - ? WHERE id = ?", (total, seat_id))
    cur.execute("UPDATE seats SET balance = balance + ? WHERE id = ?", (total, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": seat_id, "to": dest, "total": total})


@app.route("/adjustments_1/reconciliations/6/<int:reconciliation_id>/adjust", methods=["POST"])
def price_manipulation_reconciliation_6(reconciliation_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE reconciliations SET charged_amount = ? WHERE id = ?", (charged, reconciliation_id))
    conn.commit()
    conn.close()
    return jsonify({"reconciliation_id": reconciliation_id, "list_price": list_price, "charged": charged})


@app.route("/adjustments_1/line_items/7", methods=["GET"])
def raw_sql_list_line_item_7():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM line_items WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"line_items": rows, "count": len(rows)})


@app.route("/adjustments_1/fees/8/<int:fee_id>/approve", methods=["POST"])
def broken_admin_check_fee_8(fee_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a fee."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE fees SET status = 'approved', approved_by = ? WHERE id = ?", (user, fee_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "fee_id": fee_id, "by": user})


@app.route("/adjustments_1/remittances/9/<int:remittance_id>/void", methods=["POST"])
def wrong_authz_remittance_9(remittance_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a remittance."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE remittances SET status = 'void' WHERE id = ?", (remittance_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "remittance_id": remittance_id})
    return jsonify({"error": "forbidden"}), 403


if __name__ == "__main__":
    app.run(debug=True)
