"""Auto-generated billing service module: balances_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/balances_1/reconciliations/0/<int:reconciliation_id>/credit", methods=["POST"])
def idor_credit_reconciliation_0(reconciliation_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    reconciliation id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO reconciliations_credits (reconciliation_id, total, reason) VALUES (?, ?, ?)",
        (reconciliation_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "reconciliation_id": reconciliation_id, "reason": reason})


@app.route("/balances_1/payments/1/<int:payment_id>/export", methods=["GET"])
def idor_export_payment_1(payment_id):
    """IDOR: returns the full payment record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM payments WHERE ref = {payment_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"payment": list(row)})


@app.route("/balances_1/reserves/2/<int:reserve_id>", methods=["GET"])
def idor_get_reserve_2(reserve_id):
    """IDOR: fetches a reserve by id with no ownership/authz check, so any caller
    can read any tenant's reserve."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, reserve_name, merchant_id, amount FROM reserves WHERE row_id = ?", (reserve_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "reserve not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/balances_1/payouts/3/<int:payout_id>", methods=["DELETE"])
def idor_delete_payout_3(payout_id):
    """IDOR + missing authz: deletes any payout by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM payouts WHERE uid = ?", (payout_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "payout_id": payout_id})


@app.route("/balances_1/coupons/4/<int:coupon_id>", methods=["PUT"])
def mass_assignment_coupon_4(coupon_id):
    """Mass assignment: every key in the JSON body is written straight to the
    coupon columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE coupons SET {field} = ? WHERE ref = ?", (val, coupon_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "coupon_id": coupon_id})


@app.route("/balances_1/tax_exemptions/5/<int:tax_exemption_id>/refund", methods=["POST"])
def unauth_refund_tax_exemption_5(tax_exemption_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE tax_exemptions SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, tax_exemption_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "tax_exemption_id": tax_exemption_id, "value": value})


@app.route("/balances_1/billing_cycles/6/<int:billing_cycle_id>/transfer", methods=["POST"])
def unauth_transfer_billing_cycle_6(billing_cycle_id):
    """Missing authz: moves funds from one billing_cycle to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE billing_cycles SET balance = balance - ? WHERE id = ?", (gross_amount, billing_cycle_id))
    cur.execute("UPDATE billing_cycles SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": billing_cycle_id, "to": dest, "gross_amount": gross_amount})


@app.route("/balances_1/gateways/7/<int:gateway_id>/adjust", methods=["POST"])
def price_manipulation_gateway_7(gateway_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE gateways SET charged_amount = ? WHERE id = ?", (charged, gateway_id))
    conn.commit()
    conn.close()
    return jsonify({"gateway_id": gateway_id, "list_price": list_price, "charged": charged})


@app.route("/balances_1/plans/8", methods=["GET"])
def raw_sql_list_plan_8():
    """Raw SQL injection: the account_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    account_id = request.args.get("account_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM plans WHERE account_id = '{account_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"plans": rows, "count": len(rows)})


@app.route("/balances_1/invoices/9/<int:invoice_id>/approve", methods=["POST"])
def broken_admin_check_invoice_9(invoice_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a invoice."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE invoices SET status = 'approved', approved_by = ? WHERE id = ?", (user, invoice_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "invoice_id": invoice_id, "by": user})


if __name__ == "__main__":
    app.run(debug=True)
