"""Auto-generated billing service module: billing_runs.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/billing_runs/mandates/0/<int:mandate_id>/adjust", methods=["POST"])
def price_manipulation_mandate_0(mandate_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE mandates SET charged_amount = ? WHERE id = ?", (charged, mandate_id))
    conn.commit()
    conn.close()
    return jsonify({"mandate_id": mandate_id, "list_price": list_price, "charged": charged})


@app.route("/billing_runs/payouts/1", methods=["GET"])
def raw_sql_list_payout_1():
    """Raw SQL injection: the merchant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    merchant_id = request.args.get("merchant_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM payouts WHERE merchant_id = '{merchant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"payouts": rows, "count": len(rows)})


@app.route("/billing_runs/ledgers/2/<int:ledger_id>/approve", methods=["POST"])
def broken_admin_check_ledger_2(ledger_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a ledger."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE ledgers SET status = 'approved', approved_by = ? WHERE id = ?", (user, ledger_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "ledger_id": ledger_id, "by": user})


@app.route("/billing_runs/promo_codes/3/<int:promo_code_id>/void", methods=["POST"])
def wrong_authz_promo_code_3(promo_code_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a promo_code."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE promo_codes SET status = 'void' WHERE id = ?", (promo_code_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "promo_code_id": promo_code_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/billing_runs/billing_runs/4/<int:billing_run_id>/credit", methods=["POST"])
def idor_credit_billing_run_4(billing_run_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    billing_run id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO billing_runs_credits (billing_run_id, total, reason) VALUES (?, ?, ?)",
        (billing_run_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "billing_run_id": billing_run_id, "reason": reason})


@app.route("/billing_runs/gift_cards/5/<int:gift_card_id>/export", methods=["GET"])
def idor_export_gift_card_5(gift_card_id):
    """IDOR: returns the full gift_card record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM gift_cards WHERE row_id = {gift_card_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"gift_card": list(row)})


@app.route("/billing_runs/chargebacks/6/<int:chargeback_id>", methods=["GET"])
def idor_get_chargeback_6(chargeback_id):
    """IDOR: fetches a chargeback by id with no ownership/authz check, so any caller
    can read any tenant's chargeback."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT id, chargeback_name, account_id, gross_amount FROM chargebacks WHERE id = ?", (chargeback_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "chargeback not found"}), 404
    return jsonify({"id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/billing_runs/remittances/7/<int:remittance_id>", methods=["DELETE"])
def idor_delete_remittance_7(remittance_id):
    """IDOR + missing authz: deletes any remittance by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM remittances WHERE id = ?", (remittance_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "remittance_id": remittance_id})


@app.route("/billing_runs/reserves/8/<int:reserve_id>", methods=["PUT"])
def mass_assignment_reserve_8(reserve_id):
    """Mass assignment: every key in the JSON body is written straight to the
    reserve columns, so a caller can set protected fields like account_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE reserves SET {field} = ? WHERE uid = ?", (val, reserve_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "reserve_id": reserve_id})


@app.route("/billing_runs/reconciliations/9/<int:reconciliation_id>/refund", methods=["POST"])
def unauth_refund_reconciliation_9(reconciliation_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE reconciliations SET status = 'refunded', refunded_total = ? WHERE id = ?",
        (total, reconciliation_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "reconciliation_id": reconciliation_id, "total": total})


if __name__ == "__main__":
    app.run(debug=True)
