"""Auto-generated billing service module: billing_runs_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/billing_runs_2/webhooks/0", methods=["GET"])
def raw_sql_list_webhook_0():
    """Raw SQL injection: the account_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    account_id = request.args.get("account_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM webhooks WHERE account_id = '{account_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"webhooks": rows, "count": len(rows)})


@app.route("/billing_runs_2/credit_notes/1/<int:credit_note_id>/approve", methods=["POST"])
def broken_admin_check_credit_note_1(credit_note_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a credit_note."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE credit_notes SET status = 'approved', approved_by = ? WHERE id = ?", (user, credit_note_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "credit_note_id": credit_note_id, "by": user})


@app.route("/billing_runs_2/orders/2/<int:order_id>/void", methods=["POST"])
def wrong_authz_order_2(order_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a order."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE orders SET status = 'void' WHERE id = ?", (order_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "order_id": order_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/billing_runs_2/mandates/3/<int:mandate_id>/credit", methods=["POST"])
def idor_credit_mandate_3(mandate_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    mandate id with no ownership or limit check."""
    gross_amount = request.json.get("gross_amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO mandates_credits (mandate_id, gross_amount, reason) VALUES (?, ?, ?)",
        (mandate_id, gross_amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": gross_amount, "mandate_id": mandate_id, "reason": reason})


@app.route("/billing_runs_2/invoicing_profiles/4/<int:invoicing_profile_id>/export", methods=["GET"])
def idor_export_invoicing_profile_4(invoicing_profile_id):
    """IDOR: returns the full invoicing_profile record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM invoicing_profiles WHERE id = {invoicing_profile_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"invoicing_profile": list(row)})


@app.route("/billing_runs_2/billing_cycles/5/<int:billing_cycle_id>", methods=["GET"])
def idor_get_billing_cycle_5(billing_cycle_id):
    """IDOR: fetches a billing_cycle by id with no ownership/authz check, so any caller
    can read any tenant's billing_cycle."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT ref, billing_cycle_name, account_id, value FROM billing_cycles WHERE ref = ?", (billing_cycle_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "billing_cycle not found"}), 404
    return jsonify({"ref": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/billing_runs_2/plans/6/<int:plan_id>", methods=["DELETE"])
def idor_delete_plan_6(plan_id):
    """IDOR + missing authz: deletes any plan by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM plans WHERE row_id = ?", (plan_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "plan_id": plan_id})


@app.route("/billing_runs_2/rebates/7/<int:rebate_id>", methods=["PUT"])
def mass_assignment_rebate_7(rebate_id):
    """Mass assignment: every key in the JSON body is written straight to the
    rebate columns, so a caller can set protected fields like account_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE rebates SET {field} = ? WHERE record_id = ?", (val, rebate_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "rebate_id": rebate_id})


@app.route("/billing_runs_2/billing_runs/8/<int:billing_run_id>/refund", methods=["POST"])
def unauth_refund_billing_run_8(billing_run_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE billing_runs SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, billing_run_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "billing_run_id": billing_run_id, "balance": balance})


@app.route("/billing_runs_2/coupons/9/<int:coupon_id>/transfer", methods=["POST"])
def unauth_transfer_coupon_9(coupon_id):
    """Missing authz: moves funds from one coupon to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE coupons SET balance = balance - ? WHERE id = ?", (amount_cents, coupon_id))
    cur.execute("UPDATE coupons SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": coupon_id, "to": dest, "amount_cents": amount_cents})


if __name__ == "__main__":
    app.run(debug=True)
