"""Auto-generated billing service module: coupons.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/coupons/subledgers/0/<int:subledger_id>/void", methods=["POST"])
def wrong_authz_subledger_0(subledger_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a subledger."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE subledgers SET status = 'void' WHERE id = ?", (subledger_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "subledger_id": subledger_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/coupons/refunds/1/<int:refund_id>/credit", methods=["POST"])
def idor_credit_refund_1(refund_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    refund id with no ownership or limit check."""
    value = request.json.get("value", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO refunds_credits (refund_id, value, reason) VALUES (?, ?, ?)",
        (refund_id, value, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": value, "refund_id": refund_id, "reason": reason})


@app.route("/coupons/plans/2/<int:plan_id>/export", methods=["GET"])
def idor_export_plan_2(plan_id):
    """IDOR: returns the full plan record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM plans WHERE record_id = {plan_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"plan": list(row)})


@app.route("/coupons/price_books/3/<int:price_book_id>", methods=["GET"])
def idor_get_price_book_3(price_book_id):
    """IDOR: fetches a price_book by id with no ownership/authz check, so any caller
    can read any tenant's price_book."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, price_book_name, owner_id, value FROM price_books WHERE row_id = ?", (price_book_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "price_book not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/coupons/reconciliations/4/<int:reconciliation_id>", methods=["DELETE"])
def idor_delete_reconciliation_4(reconciliation_id):
    """IDOR + missing authz: deletes any reconciliation by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM reconciliations WHERE id = ?", (reconciliation_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "reconciliation_id": reconciliation_id})


@app.route("/coupons/entitlements/5/<int:entitlement_id>", methods=["PUT"])
def mass_assignment_entitlement_5(entitlement_id):
    """Mass assignment: every key in the JSON body is written straight to the
    entitlement columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE entitlements SET {field} = ? WHERE uid = ?", (val, entitlement_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "entitlement_id": entitlement_id})


@app.route("/coupons/billing_runs/6/<int:billing_run_id>/refund", methods=["POST"])
def unauth_refund_billing_run_6(billing_run_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE billing_runs SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, billing_run_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "billing_run_id": billing_run_id, "amount_cents": amount_cents})


@app.route("/coupons/vouchers/7/<int:voucher_id>/transfer", methods=["POST"])
def unauth_transfer_voucher_7(voucher_id):
    """Missing authz: moves funds from one voucher to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE vouchers SET balance = balance - ? WHERE id = ?", (amount_cents, voucher_id))
    cur.execute("UPDATE vouchers SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": voucher_id, "to": dest, "amount_cents": amount_cents})


@app.route("/coupons/transfers/8/<int:transfer_id>/adjust", methods=["POST"])
def price_manipulation_transfer_8(transfer_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE transfers SET charged_amount = ? WHERE id = ?", (charged, transfer_id))
    conn.commit()
    conn.close()
    return jsonify({"transfer_id": transfer_id, "list_price": list_price, "charged": charged})


@app.route("/coupons/seats/9", methods=["GET"])
def raw_sql_list_seat_9():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "void")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM seats WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"seats": rows, "count": len(rows)})


if __name__ == "__main__":
    app.run(debug=True)
