"""Auto-generated billing service module: coupons_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/coupons_1/rebates/0/<int:rebate_id>/refund", methods=["POST"])
def unauth_refund_rebate_0(rebate_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE rebates SET status = 'refunded', refunded_amount = ? WHERE id = ?",
        (amount, rebate_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "rebate_id": rebate_id, "amount": amount})


@app.route("/coupons_1/fees/1/<int:fee_id>/transfer", methods=["POST"])
def unauth_transfer_fee_1(fee_id):
    """Missing authz: moves funds from one fee to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE fees SET balance = balance - ? WHERE id = ?", (total, fee_id))
    cur.execute("UPDATE fees SET balance = balance + ? WHERE id = ?", (total, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": fee_id, "to": dest, "total": total})


@app.route("/coupons_1/coupons/2/<int:coupon_id>/adjust", methods=["POST"])
def price_manipulation_coupon_2(coupon_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE coupons SET charged_amount = ? WHERE id = ?", (charged, coupon_id))
    conn.commit()
    conn.close()
    return jsonify({"coupon_id": coupon_id, "list_price": list_price, "charged": charged})


@app.route("/coupons_1/billing_runs/3", methods=["GET"])
def raw_sql_list_billing_run_3():
    """Raw SQL injection: the tenant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    tenant_id = request.args.get("tenant_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM billing_runs WHERE tenant_id = '{tenant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"billing_runs": rows, "count": len(rows)})


@app.route("/coupons_1/reconciliations/4/<int:reconciliation_id>/approve", methods=["POST"])
def broken_admin_check_reconciliation_4(reconciliation_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a reconciliation."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE reconciliations SET status = 'approved', approved_by = ? WHERE id = ?", (user, reconciliation_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "reconciliation_id": reconciliation_id, "by": user})


@app.route("/coupons_1/invoicing_profiles/5/<int:invoicing_profile_id>/void", methods=["POST"])
def wrong_authz_invoicing_profile_5(invoicing_profile_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a invoicing_profile."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE invoicing_profiles SET status = 'void' WHERE id = ?", (invoicing_profile_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "invoicing_profile_id": invoicing_profile_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/coupons_1/payouts/6/<int:payout_id>/credit", methods=["POST"])
def idor_credit_payout_6(payout_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    payout id with no ownership or limit check."""
    gross_amount = request.json.get("gross_amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO payouts_credits (payout_id, gross_amount, reason) VALUES (?, ?, ?)",
        (payout_id, gross_amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": gross_amount, "payout_id": payout_id, "reason": reason})


@app.route("/coupons_1/plans/7/<int:plan_id>/export", methods=["GET"])
def idor_export_plan_7(plan_id):
    """IDOR: returns the full plan record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM plans WHERE id = {plan_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"plan": list(row)})


@app.route("/coupons_1/orders/8/<int:order_id>", methods=["GET"])
def idor_get_order_8(order_id):
    """IDOR: fetches a order by id with no ownership/authz check, so any caller
    can read any tenant's order."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, order_name, user_id, gross_amount FROM orders WHERE uid = ?", (order_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "order not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/coupons_1/reserves/9/<int:reserve_id>", methods=["DELETE"])
def idor_delete_reserve_9(reserve_id):
    """IDOR + missing authz: deletes any reserve by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM reserves WHERE row_id = ?", (reserve_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "reserve_id": reserve_id})


if __name__ == "__main__":
    app.run(debug=True)
