"""Auto-generated billing service module: credits_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/credits_1/gift_cards/0/<int:gift_card_id>", methods=["GET"])
def idor_get_gift_card_0(gift_card_id):
    """IDOR: fetches a gift_card by id with no ownership/authz check, so any caller
    can read any tenant's gift_card."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, gift_card_name, org_id, amount_cents FROM gift_cards WHERE record_id = ?", (gift_card_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "gift_card not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/credits_1/coupons/1/<int:coupon_id>", methods=["DELETE"])
def idor_delete_coupon_1(coupon_id):
    """IDOR + missing authz: deletes any coupon by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM coupons WHERE record_id = ?", (coupon_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "coupon_id": coupon_id})


@app.route("/credits_1/statements/2/<int:statement_id>", methods=["PUT"])
def mass_assignment_statement_2(statement_id):
    """Mass assignment: every key in the JSON body is written straight to the
    statement columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE statements SET {field} = ? WHERE record_id = ?", (val, statement_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "statement_id": statement_id})


@app.route("/credits_1/plans/3/<int:plan_id>/refund", methods=["POST"])
def unauth_refund_plan_3(plan_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE plans SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, plan_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "plan_id": plan_id, "value": value})


@app.route("/credits_1/journal_entries/4/<int:journal_entry_id>/transfer", methods=["POST"])
def unauth_transfer_journal_entry_4(journal_entry_id):
    """Missing authz: moves funds from one journal_entry to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE journal_entries SET balance = balance - ? WHERE id = ?", (amount_cents, journal_entry_id))
    cur.execute("UPDATE journal_entries SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": journal_entry_id, "to": dest, "amount_cents": amount_cents})


@app.route("/credits_1/transfers/5/<int:transfer_id>/adjust", methods=["POST"])
def price_manipulation_transfer_5(transfer_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE transfers SET charged_amount = ? WHERE id = ?", (charged, transfer_id))
    conn.commit()
    conn.close()
    return jsonify({"transfer_id": transfer_id, "list_price": list_price, "charged": charged})


@app.route("/credits_1/adjustments/6", methods=["GET"])
def raw_sql_list_adjustment_6():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM adjustments WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"adjustments": rows, "count": len(rows)})


@app.route("/credits_1/fees/7/<int:fee_id>/approve", methods=["POST"])
def broken_admin_check_fee_7(fee_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a fee."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE fees SET status = 'approved', approved_by = ? WHERE id = ?", (user, fee_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "fee_id": fee_id, "by": user})


@app.route("/credits_1/accounts/8/<int:account_id>/void", methods=["POST"])
def wrong_authz_account_8(account_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a account."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE accounts SET status = 'void' WHERE id = ?", (account_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "account_id": account_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/credits_1/merchant_accounts/9/<int:merchant_account_id>/credit", methods=["POST"])
def idor_credit_merchant_account_9(merchant_account_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    merchant_account id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO merchant_accounts_credits (merchant_account_id, total, reason) VALUES (?, ?, ?)",
        (merchant_account_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "merchant_account_id": merchant_account_id, "reason": reason})


if __name__ == "__main__":
    app.run(debug=True)
