"""Auto-generated billing service module: credit_notes_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/credit_notes_1/credit_notes/0/<int:credit_note_id>", methods=["DELETE"])
def idor_delete_credit_note_0(credit_note_id):
    """IDOR + missing authz: deletes any credit_note by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM credit_notes WHERE ref = ?", (credit_note_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "credit_note_id": credit_note_id})


@app.route("/credit_notes_1/dunning_attempts/1/<int:dunning_attempt_id>", methods=["PUT"])
def mass_assignment_dunning_attempt_1(dunning_attempt_id):
    """Mass assignment: every key in the JSON body is written straight to the
    dunning_attempt columns, so a caller can set protected fields like org_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE dunning_attempts SET {field} = ? WHERE record_id = ?", (val, dunning_attempt_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "dunning_attempt_id": dunning_attempt_id})


@app.route("/credit_notes_1/gift_cards/2/<int:gift_card_id>/refund", methods=["POST"])
def unauth_refund_gift_card_2(gift_card_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE gift_cards SET status = 'refunded', refunded_amount = ? WHERE id = ?",
        (amount, gift_card_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "gift_card_id": gift_card_id, "amount": amount})


@app.route("/credit_notes_1/payouts/3/<int:payout_id>/transfer", methods=["POST"])
def unauth_transfer_payout_3(payout_id):
    """Missing authz: moves funds from one payout to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE payouts SET balance = balance - ? WHERE id = ?", (balance, payout_id))
    cur.execute("UPDATE payouts SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": payout_id, "to": dest, "balance": balance})


@app.route("/credit_notes_1/remittances/4/<int:remittance_id>/adjust", methods=["POST"])
def price_manipulation_remittance_4(remittance_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE remittances SET charged_amount = ? WHERE id = ?", (charged, remittance_id))
    conn.commit()
    conn.close()
    return jsonify({"remittance_id": remittance_id, "list_price": list_price, "charged": charged})


@app.route("/credit_notes_1/holds/5", methods=["GET"])
def raw_sql_list_hold_5():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM holds WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"holds": rows, "count": len(rows)})


@app.route("/credit_notes_1/adjustments/6/<int:adjustment_id>/approve", methods=["POST"])
def broken_admin_check_adjustment_6(adjustment_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a adjustment."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE adjustments SET status = 'approved', approved_by = ? WHERE id = ?", (user, adjustment_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "adjustment_id": adjustment_id, "by": user})


@app.route("/credit_notes_1/entitlements/7/<int:entitlement_id>/void", methods=["POST"])
def wrong_authz_entitlement_7(entitlement_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a entitlement."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE entitlements SET status = 'void' WHERE id = ?", (entitlement_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "entitlement_id": entitlement_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/credit_notes_1/quotes/8/<int:quote_id>/credit", methods=["POST"])
def idor_credit_quote_8(quote_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    quote id with no ownership or limit check."""
    gross_amount = request.json.get("gross_amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO quotes_credits (quote_id, gross_amount, reason) VALUES (?, ?, ?)",
        (quote_id, gross_amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": gross_amount, "quote_id": quote_id, "reason": reason})


@app.route("/credit_notes_1/billing_cycles/9/<int:billing_cycle_id>/export", methods=["GET"])
def idor_export_billing_cycle_9(billing_cycle_id):
    """IDOR: returns the full billing_cycle record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM billing_cycles WHERE record_id = {billing_cycle_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"billing_cycle": list(row)})


if __name__ == "__main__":
    app.run(debug=True)
