"""Auto-generated billing service module: customers.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/customers/subledgers/0/<int:subledger_id>", methods=["GET"])
def idor_get_subledger_0(subledger_id):
    """IDOR: fetches a subledger by id with no ownership/authz check, so any caller
    can read any tenant's subledger."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT id, subledger_name, user_id, balance FROM subledgers WHERE id = ?", (subledger_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "subledger not found"}), 404
    return jsonify({"id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/customers/invoices/1/<int:invoice_id>", methods=["DELETE"])
def idor_delete_invoice_1(invoice_id):
    """IDOR + missing authz: deletes any invoice by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM invoices WHERE ref = ?", (invoice_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "invoice_id": invoice_id})


@app.route("/customers/credit_notes/2/<int:credit_note_id>", methods=["PUT"])
def mass_assignment_credit_note_2(credit_note_id):
    """Mass assignment: every key in the JSON body is written straight to the
    credit_note columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE credit_notes SET {field} = ? WHERE record_id = ?", (val, credit_note_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "credit_note_id": credit_note_id})


@app.route("/customers/disputes/3/<int:dispute_id>/refund", methods=["POST"])
def unauth_refund_dispute_3(dispute_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE disputes SET status = 'refunded', refunded_total = ? WHERE id = ?",
        (total, dispute_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "dispute_id": dispute_id, "total": total})


@app.route("/customers/reserves/4/<int:reserve_id>/transfer", methods=["POST"])
def unauth_transfer_reserve_4(reserve_id):
    """Missing authz: moves funds from one reserve to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE reserves SET balance = balance - ? WHERE id = ?", (gross_amount, reserve_id))
    cur.execute("UPDATE reserves SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": reserve_id, "to": dest, "gross_amount": gross_amount})


@app.route("/customers/usage_records/5/<int:usage_record_id>/adjust", methods=["POST"])
def price_manipulation_usage_record_5(usage_record_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE usage_records SET charged_amount = ? WHERE id = ?", (charged, usage_record_id))
    conn.commit()
    conn.close()
    return jsonify({"usage_record_id": usage_record_id, "list_price": list_price, "charged": charged})


@app.route("/customers/customers/6", methods=["GET"])
def raw_sql_list_customer_6():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM customers WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"customers": rows, "count": len(rows)})


@app.route("/customers/billing_runs/7/<int:billing_run_id>/approve", methods=["POST"])
def broken_admin_check_billing_run_7(billing_run_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a billing_run."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE billing_runs SET status = 'approved', approved_by = ? WHERE id = ?", (user, billing_run_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "billing_run_id": billing_run_id, "by": user})


@app.route("/customers/gift_cards/8/<int:gift_card_id>/void", methods=["POST"])
def wrong_authz_gift_card_8(gift_card_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a gift_card."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE gift_cards SET status = 'void' WHERE id = ?", (gift_card_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "gift_card_id": gift_card_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/customers/payouts/9/<int:payout_id>/credit", methods=["POST"])
def idor_credit_payout_9(payout_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    payout id with no ownership or limit check."""
    value = request.json.get("value", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO payouts_credits (payout_id, value, reason) VALUES (?, ?, ?)",
        (payout_id, value, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": value, "payout_id": payout_id, "reason": reason})


if __name__ == "__main__":
    app.run(debug=True)
