"""Auto-generated billing service module: discounts_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/discounts_2/journal_entries/0/<int:journal_entry_id>/export", methods=["GET"])
def idor_export_journal_entry_0(journal_entry_id):
    """IDOR: returns the full journal_entry record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM journal_entries WHERE uid = {journal_entry_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"journal_entry": list(row)})


@app.route("/discounts_2/invoicing_profiles/1/<int:invoicing_profile_id>", methods=["GET"])
def idor_get_invoicing_profile_1(invoicing_profile_id):
    """IDOR: fetches a invoicing_profile by id with no ownership/authz check, so any caller
    can read any tenant's invoicing_profile."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT id, invoicing_profile_name, tenant_id, gross_amount FROM invoicing_profiles WHERE id = ?", (invoicing_profile_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "invoicing_profile not found"}), 404
    return jsonify({"id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/discounts_2/seats/2/<int:seat_id>", methods=["DELETE"])
def idor_delete_seat_2(seat_id):
    """IDOR + missing authz: deletes any seat by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM seats WHERE record_id = ?", (seat_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "seat_id": seat_id})


@app.route("/discounts_2/gift_cards/3/<int:gift_card_id>", methods=["PUT"])
def mass_assignment_gift_card_3(gift_card_id):
    """Mass assignment: every key in the JSON body is written straight to the
    gift_card columns, so a caller can set protected fields like user_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE gift_cards SET {field} = ? WHERE uid = ?", (val, gift_card_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "gift_card_id": gift_card_id})


@app.route("/discounts_2/remittances/4/<int:remittance_id>/refund", methods=["POST"])
def unauth_refund_remittance_4(remittance_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE remittances SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, remittance_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "remittance_id": remittance_id, "value": value})


@app.route("/discounts_2/coupons/5/<int:coupon_id>/transfer", methods=["POST"])
def unauth_transfer_coupon_5(coupon_id):
    """Missing authz: moves funds from one coupon to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE coupons SET balance = balance - ? WHERE id = ?", (gross_amount, coupon_id))
    cur.execute("UPDATE coupons SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": coupon_id, "to": dest, "gross_amount": gross_amount})


@app.route("/discounts_2/invoices/6/<int:invoice_id>/adjust", methods=["POST"])
def price_manipulation_invoice_6(invoice_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE invoices SET charged_amount = ? WHERE id = ?", (charged, invoice_id))
    conn.commit()
    conn.close()
    return jsonify({"invoice_id": invoice_id, "list_price": list_price, "charged": charged})


@app.route("/discounts_2/billing_cycles/7", methods=["GET"])
def raw_sql_list_billing_cycle_7():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM billing_cycles WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"billing_cycles": rows, "count": len(rows)})


@app.route("/discounts_2/merchant_accounts/8/<int:merchant_account_id>/approve", methods=["POST"])
def broken_admin_check_merchant_account_8(merchant_account_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a merchant_account."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE merchant_accounts SET status = 'approved', approved_by = ? WHERE id = ?", (user, merchant_account_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "merchant_account_id": merchant_account_id, "by": user})


@app.route("/discounts_2/mandates/9/<int:mandate_id>/void", methods=["POST"])
def wrong_authz_mandate_9(mandate_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a mandate."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE mandates SET status = 'void' WHERE id = ?", (mandate_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "mandate_id": mandate_id})
    return jsonify({"error": "forbidden"}), 403


if __name__ == "__main__":
    app.run(debug=True)
