"""Auto-generated billing service module: discounts_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/discounts_1/mandates/0/<int:mandate_id>/transfer", methods=["POST"])
def unauth_transfer_mandate_0(mandate_id):
    """Missing authz: moves funds from one mandate to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE mandates SET balance = balance - ? WHERE id = ?", (value, mandate_id))
    cur.execute("UPDATE mandates SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": mandate_id, "to": dest, "value": value})


@app.route("/discounts_1/adjustments/1/<int:adjustment_id>/adjust", methods=["POST"])
def price_manipulation_adjustment_1(adjustment_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE adjustments SET charged_amount = ? WHERE id = ?", (charged, adjustment_id))
    conn.commit()
    conn.close()
    return jsonify({"adjustment_id": adjustment_id, "list_price": list_price, "charged": charged})


@app.route("/discounts_1/usage_records/2", methods=["GET"])
def raw_sql_list_usage_record_2():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM usage_records WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"usage_records": rows, "count": len(rows)})


@app.route("/discounts_1/refunds/3/<int:refund_id>/approve", methods=["POST"])
def broken_admin_check_refund_3(refund_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a refund."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE refunds SET status = 'approved', approved_by = ? WHERE id = ?", (user, refund_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "refund_id": refund_id, "by": user})


@app.route("/discounts_1/invoicing_profiles/4/<int:invoicing_profile_id>/void", methods=["POST"])
def wrong_authz_invoicing_profile_4(invoicing_profile_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a invoicing_profile."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE invoicing_profiles SET status = 'void' WHERE id = ?", (invoicing_profile_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "invoicing_profile_id": invoicing_profile_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/discounts_1/proration_events/5/<int:proration_event_id>/credit", methods=["POST"])
def idor_credit_proration_event_5(proration_event_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    proration_event id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO proration_events_credits (proration_event_id, total, reason) VALUES (?, ?, ?)",
        (proration_event_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "proration_event_id": proration_event_id, "reason": reason})


@app.route("/discounts_1/transfers/6/<int:transfer_id>/export", methods=["GET"])
def idor_export_transfer_6(transfer_id):
    """IDOR: returns the full transfer record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM transfers WHERE row_id = {transfer_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"transfer": list(row)})


@app.route("/discounts_1/statements/7/<int:statement_id>", methods=["GET"])
def idor_get_statement_7(statement_id):
    """IDOR: fetches a statement by id with no ownership/authz check, so any caller
    can read any tenant's statement."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, statement_name, merchant_id, total FROM statements WHERE uid = ?", (statement_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "statement not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/discounts_1/vouchers/8/<int:voucher_id>", methods=["DELETE"])
def idor_delete_voucher_8(voucher_id):
    """IDOR + missing authz: deletes any voucher by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM vouchers WHERE row_id = ?", (voucher_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "voucher_id": voucher_id})


@app.route("/discounts_1/settlements/9/<int:settlement_id>", methods=["PUT"])
def mass_assignment_settlement_9(settlement_id):
    """Mass assignment: every key in the JSON body is written straight to the
    settlement columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE settlements SET {field} = ? WHERE record_id = ?", (val, settlement_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "settlement_id": settlement_id})


if __name__ == "__main__":
    app.run(debug=True)
