"""Auto-generated billing service module: disputes.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/disputes/billing_runs/0/<int:billing_run_id>/refund", methods=["POST"])
def unauth_refund_billing_run_0(billing_run_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE billing_runs SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, billing_run_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "billing_run_id": billing_run_id, "value": value})


@app.route("/disputes/webhooks/1/<int:webhook_id>/transfer", methods=["POST"])
def unauth_transfer_webhook_1(webhook_id):
    """Missing authz: moves funds from one webhook to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE webhooks SET balance = balance - ? WHERE id = ?", (value, webhook_id))
    cur.execute("UPDATE webhooks SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": webhook_id, "to": dest, "value": value})


@app.route("/disputes/settlements/2/<int:settlement_id>/adjust", methods=["POST"])
def price_manipulation_settlement_2(settlement_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE settlements SET charged_amount = ? WHERE id = ?", (charged, settlement_id))
    conn.commit()
    conn.close()
    return jsonify({"settlement_id": settlement_id, "list_price": list_price, "charged": charged})


@app.route("/disputes/usage_records/3", methods=["GET"])
def raw_sql_list_usage_record_3():
    """Raw SQL injection: the merchant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    merchant_id = request.args.get("merchant_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM usage_records WHERE merchant_id = '{merchant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"usage_records": rows, "count": len(rows)})


@app.route("/disputes/rebates/4/<int:rebate_id>/approve", methods=["POST"])
def broken_admin_check_rebate_4(rebate_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a rebate."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE rebates SET status = 'approved', approved_by = ? WHERE id = ?", (user, rebate_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "rebate_id": rebate_id, "by": user})


@app.route("/disputes/orders/5/<int:order_id>/void", methods=["POST"])
def wrong_authz_order_5(order_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a order."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE orders SET status = 'void' WHERE id = ?", (order_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "order_id": order_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/disputes/plans/6/<int:plan_id>/credit", methods=["POST"])
def idor_credit_plan_6(plan_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    plan id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO plans_credits (plan_id, total, reason) VALUES (?, ?, ?)",
        (plan_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "plan_id": plan_id, "reason": reason})


@app.route("/disputes/reconciliations/7/<int:reconciliation_id>/export", methods=["GET"])
def idor_export_reconciliation_7(reconciliation_id):
    """IDOR: returns the full reconciliation record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM reconciliations WHERE record_id = {reconciliation_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"reconciliation": list(row)})


@app.route("/disputes/tax_exemptions/8/<int:tax_exemption_id>", methods=["GET"])
def idor_get_tax_exemption_8(tax_exemption_id):
    """IDOR: fetches a tax_exemption by id with no ownership/authz check, so any caller
    can read any tenant's tax_exemption."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT id, tax_exemption_name, merchant_id, balance FROM tax_exemptions WHERE id = ?", (tax_exemption_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "tax_exemption not found"}), 404
    return jsonify({"id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/disputes/gift_cards/9/<int:gift_card_id>", methods=["DELETE"])
def idor_delete_gift_card_9(gift_card_id):
    """IDOR + missing authz: deletes any gift_card by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM gift_cards WHERE row_id = ?", (gift_card_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "gift_card_id": gift_card_id})


if __name__ == "__main__":
    app.run(debug=True)
