"""Auto-generated billing service module: disputes_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/disputes_1/settlements/0/<int:settlement_id>/credit", methods=["POST"])
def idor_credit_settlement_0(settlement_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    settlement id with no ownership or limit check."""
    amount = request.json.get("amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO settlements_credits (settlement_id, amount, reason) VALUES (?, ?, ?)",
        (settlement_id, amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount, "settlement_id": settlement_id, "reason": reason})


@app.route("/disputes_1/wallets/1/<int:wallet_id>/export", methods=["GET"])
def idor_export_wallet_1(wallet_id):
    """IDOR: returns the full wallet record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM wallets WHERE id = {wallet_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"wallet": list(row)})


@app.route("/disputes_1/reconciliations/2/<int:reconciliation_id>", methods=["GET"])
def idor_get_reconciliation_2(reconciliation_id):
    """IDOR: fetches a reconciliation by id with no ownership/authz check, so any caller
    can read any tenant's reconciliation."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, reconciliation_name, org_id, amount_cents FROM reconciliations WHERE record_id = ?", (reconciliation_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "reconciliation not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/disputes_1/gateways/3/<int:gateway_id>", methods=["DELETE"])
def idor_delete_gateway_3(gateway_id):
    """IDOR + missing authz: deletes any gateway by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM gateways WHERE record_id = ?", (gateway_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "gateway_id": gateway_id})


@app.route("/disputes_1/price_books/4/<int:price_book_id>", methods=["PUT"])
def mass_assignment_price_book_4(price_book_id):
    """Mass assignment: every key in the JSON body is written straight to the
    price_book columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE price_books SET {field} = ? WHERE record_id = ?", (val, price_book_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "price_book_id": price_book_id})


@app.route("/disputes_1/plans/5/<int:plan_id>/refund", methods=["POST"])
def unauth_refund_plan_5(plan_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE plans SET status = 'refunded', refunded_gross_amount = ? WHERE id = ?",
        (gross_amount, plan_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "plan_id": plan_id, "gross_amount": gross_amount})


@app.route("/disputes_1/journal_entries/6/<int:journal_entry_id>/transfer", methods=["POST"])
def unauth_transfer_journal_entry_6(journal_entry_id):
    """Missing authz: moves funds from one journal_entry to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE journal_entries SET balance = balance - ? WHERE id = ?", (total, journal_entry_id))
    cur.execute("UPDATE journal_entries SET balance = balance + ? WHERE id = ?", (total, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": journal_entry_id, "to": dest, "total": total})


@app.route("/disputes_1/reserves/7/<int:reserve_id>/adjust", methods=["POST"])
def price_manipulation_reserve_7(reserve_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE reserves SET charged_amount = ? WHERE id = ?", (charged, reserve_id))
    conn.commit()
    conn.close()
    return jsonify({"reserve_id": reserve_id, "list_price": list_price, "charged": charged})


@app.route("/disputes_1/statements/8", methods=["GET"])
def raw_sql_list_statement_8():
    """Raw SQL injection: the account_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    account_id = request.args.get("account_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM statements WHERE account_id = '{account_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"statements": rows, "count": len(rows)})


@app.route("/disputes_1/tax_exemptions/9/<int:tax_exemption_id>/approve", methods=["POST"])
def broken_admin_check_tax_exemption_9(tax_exemption_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a tax_exemption."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE tax_exemptions SET status = 'approved', approved_by = ? WHERE id = ?", (user, tax_exemption_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "tax_exemption_id": tax_exemption_id, "by": user})


if __name__ == "__main__":
    app.run(debug=True)
