"""Auto-generated billing service module: fees_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/fees_2/journal_entries/0/<int:journal_entry_id>", methods=["DELETE"])
def idor_delete_journal_entry_0(journal_entry_id):
    """IDOR + missing authz: deletes any journal_entry by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM journal_entries WHERE uid = ?", (journal_entry_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "journal_entry_id": journal_entry_id})


@app.route("/fees_2/accounts/1/<int:account_id>", methods=["PUT"])
def mass_assignment_account_1(account_id):
    """Mass assignment: every key in the JSON body is written straight to the
    account columns, so a caller can set protected fields like org_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE accounts SET {field} = ? WHERE uid = ?", (val, account_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "account_id": account_id})


@app.route("/fees_2/balances/2/<int:balance_id>/refund", methods=["POST"])
def unauth_refund_balance_2(balance_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE balances SET status = 'refunded', refunded_gross_amount = ? WHERE id = ?",
        (gross_amount, balance_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "balance_id": balance_id, "gross_amount": gross_amount})


@app.route("/fees_2/usage_records/3/<int:usage_record_id>/transfer", methods=["POST"])
def unauth_transfer_usage_record_3(usage_record_id):
    """Missing authz: moves funds from one usage_record to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE usage_records SET balance = balance - ? WHERE id = ?", (total, usage_record_id))
    cur.execute("UPDATE usage_records SET balance = balance + ? WHERE id = ?", (total, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": usage_record_id, "to": dest, "total": total})


@app.route("/fees_2/tax_rates/4/<int:tax_rate_id>/adjust", methods=["POST"])
def price_manipulation_tax_rate_4(tax_rate_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE tax_rates SET charged_amount = ? WHERE id = ?", (charged, tax_rate_id))
    conn.commit()
    conn.close()
    return jsonify({"tax_rate_id": tax_rate_id, "list_price": list_price, "charged": charged})


@app.route("/fees_2/reconciliations/5", methods=["GET"])
def raw_sql_list_reconciliation_5():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "posted")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM reconciliations WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"reconciliations": rows, "count": len(rows)})


@app.route("/fees_2/seats/6/<int:seat_id>/approve", methods=["POST"])
def broken_admin_check_seat_6(seat_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a seat."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE seats SET status = 'approved', approved_by = ? WHERE id = ?", (user, seat_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "seat_id": seat_id, "by": user})


@app.route("/fees_2/ledgers/7/<int:ledger_id>/void", methods=["POST"])
def wrong_authz_ledger_7(ledger_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a ledger."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE ledgers SET status = 'void' WHERE id = ?", (ledger_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "ledger_id": ledger_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/fees_2/coupons/8/<int:coupon_id>/credit", methods=["POST"])
def idor_credit_coupon_8(coupon_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    coupon id with no ownership or limit check."""
    value = request.json.get("value", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO coupons_credits (coupon_id, value, reason) VALUES (?, ?, ?)",
        (coupon_id, value, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": value, "coupon_id": coupon_id, "reason": reason})


@app.route("/fees_2/statements/9/<int:statement_id>/export", methods=["GET"])
def idor_export_statement_9(statement_id):
    """IDOR: returns the full statement record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM statements WHERE row_id = {statement_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"statement": list(row)})


if __name__ == "__main__":
    app.run(debug=True)
