"""Auto-generated billing service module: fees_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/fees_1/merchant_accounts/0", methods=["GET"])
def raw_sql_list_merchant_account_0():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "settled")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM merchant_accounts WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"merchant_accounts": rows, "count": len(rows)})


@app.route("/fees_1/dunning_attempts/1/<int:dunning_attempt_id>/approve", methods=["POST"])
def broken_admin_check_dunning_attempt_1(dunning_attempt_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a dunning_attempt."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE dunning_attempts SET status = 'approved', approved_by = ? WHERE id = ?", (user, dunning_attempt_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "dunning_attempt_id": dunning_attempt_id, "by": user})


@app.route("/fees_1/promo_codes/2/<int:promo_code_id>/void", methods=["POST"])
def wrong_authz_promo_code_2(promo_code_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a promo_code."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE promo_codes SET status = 'void' WHERE id = ?", (promo_code_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "promo_code_id": promo_code_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/fees_1/settlements/3/<int:settlement_id>/credit", methods=["POST"])
def idor_credit_settlement_3(settlement_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    settlement id with no ownership or limit check."""
    balance = request.json.get("balance", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO settlements_credits (settlement_id, balance, reason) VALUES (?, ?, ?)",
        (settlement_id, balance, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": balance, "settlement_id": settlement_id, "reason": reason})


@app.route("/fees_1/wallets/4/<int:wallet_id>/export", methods=["GET"])
def idor_export_wallet_4(wallet_id):
    """IDOR: returns the full wallet record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM wallets WHERE record_id = {wallet_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"wallet": list(row)})


@app.route("/fees_1/refunds/5/<int:refund_id>", methods=["GET"])
def idor_get_refund_5(refund_id):
    """IDOR: fetches a refund by id with no ownership/authz check, so any caller
    can read any tenant's refund."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, refund_name, user_id, amount FROM refunds WHERE uid = ?", (refund_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "refund not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/fees_1/orders/6/<int:order_id>", methods=["DELETE"])
def idor_delete_order_6(order_id):
    """IDOR + missing authz: deletes any order by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM orders WHERE id = ?", (order_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "order_id": order_id})


@app.route("/fees_1/ledgers/7/<int:ledger_id>", methods=["PUT"])
def mass_assignment_ledger_7(ledger_id):
    """Mass assignment: every key in the JSON body is written straight to the
    ledger columns, so a caller can set protected fields like user_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE ledgers SET {field} = ? WHERE uid = ?", (val, ledger_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "ledger_id": ledger_id})


@app.route("/fees_1/journal_entries/8/<int:journal_entry_id>/refund", methods=["POST"])
def unauth_refund_journal_entry_8(journal_entry_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE journal_entries SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, journal_entry_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "journal_entry_id": journal_entry_id, "value": value})


@app.route("/fees_1/reserves/9/<int:reserve_id>/transfer", methods=["POST"])
def unauth_transfer_reserve_9(reserve_id):
    """Missing authz: moves funds from one reserve to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE reserves SET balance = balance - ? WHERE id = ?", (balance, reserve_id))
    cur.execute("UPDATE reserves SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": reserve_id, "to": dest, "balance": balance})


if __name__ == "__main__":
    app.run(debug=True)
