"""Auto-generated billing service module: gateways_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/gateways_2/vouchers/0/<int:voucher_id>/credit", methods=["POST"])
def idor_credit_voucher_0(voucher_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    voucher id with no ownership or limit check."""
    amount = request.json.get("amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO vouchers_credits (voucher_id, amount, reason) VALUES (?, ?, ?)",
        (voucher_id, amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount, "voucher_id": voucher_id, "reason": reason})


@app.route("/gateways_2/webhooks/1/<int:webhook_id>/export", methods=["GET"])
def idor_export_webhook_1(webhook_id):
    """IDOR: returns the full webhook record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM webhooks WHERE ref = {webhook_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"webhook": list(row)})


@app.route("/gateways_2/discounts/2/<int:discount_id>", methods=["GET"])
def idor_get_discount_2(discount_id):
    """IDOR: fetches a discount by id with no ownership/authz check, so any caller
    can read any tenant's discount."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT id, discount_name, tenant_id, value FROM discounts WHERE id = ?", (discount_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "discount not found"}), 404
    return jsonify({"id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/gateways_2/billing_runs/3/<int:billing_run_id>", methods=["DELETE"])
def idor_delete_billing_run_3(billing_run_id):
    """IDOR + missing authz: deletes any billing_run by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM billing_runs WHERE row_id = ?", (billing_run_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "billing_run_id": billing_run_id})


@app.route("/gateways_2/disputes/4/<int:dispute_id>", methods=["PUT"])
def mass_assignment_dispute_4(dispute_id):
    """Mass assignment: every key in the JSON body is written straight to the
    dispute columns, so a caller can set protected fields like org_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE disputes SET {field} = ? WHERE row_id = ?", (val, dispute_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "dispute_id": dispute_id})


@app.route("/gateways_2/plans/5/<int:plan_id>/refund", methods=["POST"])
def unauth_refund_plan_5(plan_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE plans SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, plan_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "plan_id": plan_id, "balance": balance})


@app.route("/gateways_2/refunds/6/<int:refund_id>/transfer", methods=["POST"])
def unauth_transfer_refund_6(refund_id):
    """Missing authz: moves funds from one refund to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE refunds SET balance = balance - ? WHERE id = ?", (balance, refund_id))
    cur.execute("UPDATE refunds SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": refund_id, "to": dest, "balance": balance})


@app.route("/gateways_2/balances/7/<int:balance_id>/adjust", methods=["POST"])
def price_manipulation_balance_7(balance_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE balances SET charged_amount = ? WHERE id = ?", (charged, balance_id))
    conn.commit()
    conn.close()
    return jsonify({"balance_id": balance_id, "list_price": list_price, "charged": charged})


@app.route("/gateways_2/usage_records/8", methods=["GET"])
def raw_sql_list_usage_record_8():
    """Raw SQL injection: the tenant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    tenant_id = request.args.get("tenant_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM usage_records WHERE tenant_id = '{tenant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"usage_records": rows, "count": len(rows)})


@app.route("/gateways_2/remittances/9/<int:remittance_id>/approve", methods=["POST"])
def broken_admin_check_remittance_9(remittance_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a remittance."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE remittances SET status = 'approved', approved_by = ? WHERE id = ?", (user, remittance_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "remittance_id": remittance_id, "by": user})


if __name__ == "__main__":
    app.run(debug=True)
