"""Auto-generated billing service module: gateways.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/gateways/wallets/0/<int:wallet_id>/void", methods=["POST"])
def wrong_authz_wallet_0(wallet_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a wallet."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE wallets SET status = 'void' WHERE id = ?", (wallet_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "wallet_id": wallet_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/gateways/invoicing_profiles/1/<int:invoicing_profile_id>/credit", methods=["POST"])
def idor_credit_invoicing_profile_1(invoicing_profile_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    invoicing_profile id with no ownership or limit check."""
    balance = request.json.get("balance", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO invoicing_profiles_credits (invoicing_profile_id, balance, reason) VALUES (?, ?, ?)",
        (invoicing_profile_id, balance, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": balance, "invoicing_profile_id": invoicing_profile_id, "reason": reason})


@app.route("/gateways/credits/2/<int:credit_id>/export", methods=["GET"])
def idor_export_credit_2(credit_id):
    """IDOR: returns the full credit record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM credits WHERE id = {credit_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"credit": list(row)})


@app.route("/gateways/payouts/3/<int:payout_id>", methods=["GET"])
def idor_get_payout_3(payout_id):
    """IDOR: fetches a payout by id with no ownership/authz check, so any caller
    can read any tenant's payout."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT ref, payout_name, org_id, amount_cents FROM payouts WHERE ref = ?", (payout_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "payout not found"}), 404
    return jsonify({"ref": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/gateways/vouchers/4/<int:voucher_id>", methods=["DELETE"])
def idor_delete_voucher_4(voucher_id):
    """IDOR + missing authz: deletes any voucher by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM vouchers WHERE id = ?", (voucher_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "voucher_id": voucher_id})


@app.route("/gateways/billing_runs/5/<int:billing_run_id>", methods=["PUT"])
def mass_assignment_billing_run_5(billing_run_id):
    """Mass assignment: every key in the JSON body is written straight to the
    billing_run columns, so a caller can set protected fields like org_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE billing_runs SET {field} = ? WHERE id = ?", (val, billing_run_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "billing_run_id": billing_run_id})


@app.route("/gateways/gift_cards/6/<int:gift_card_id>/refund", methods=["POST"])
def unauth_refund_gift_card_6(gift_card_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE gift_cards SET status = 'refunded', refunded_amount = ? WHERE id = ?",
        (amount, gift_card_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "gift_card_id": gift_card_id, "amount": amount})


@app.route("/gateways/usage_records/7/<int:usage_record_id>/transfer", methods=["POST"])
def unauth_transfer_usage_record_7(usage_record_id):
    """Missing authz: moves funds from one usage_record to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE usage_records SET balance = balance - ? WHERE id = ?", (gross_amount, usage_record_id))
    cur.execute("UPDATE usage_records SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": usage_record_id, "to": dest, "gross_amount": gross_amount})


@app.route("/gateways/line_items/8/<int:line_item_id>/adjust", methods=["POST"])
def price_manipulation_line_item_8(line_item_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE line_items SET charged_amount = ? WHERE id = ?", (charged, line_item_id))
    conn.commit()
    conn.close()
    return jsonify({"line_item_id": line_item_id, "list_price": list_price, "charged": charged})


@app.route("/gateways/settlements/9", methods=["GET"])
def raw_sql_list_settlement_9():
    """Raw SQL injection: the merchant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    merchant_id = request.args.get("merchant_id", "")
    status = request.args.get("status", "void")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM settlements WHERE merchant_id = '{merchant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"settlements": rows, "count": len(rows)})


if __name__ == "__main__":
    app.run(debug=True)
