"""Auto-generated billing service module: gift_cards.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/gift_cards/remittances/0/<int:remittance_id>/refund", methods=["POST"])
def unauth_refund_remittance_0(remittance_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE remittances SET status = 'refunded', refunded_amount = ? WHERE id = ?",
        (amount, remittance_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "remittance_id": remittance_id, "amount": amount})


@app.route("/gift_cards/transfers/1/<int:transfer_id>/transfer", methods=["POST"])
def unauth_transfer_transfer_1(transfer_id):
    """Missing authz: moves funds from one transfer to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE transfers SET balance = balance - ? WHERE id = ?", (gross_amount, transfer_id))
    cur.execute("UPDATE transfers SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": transfer_id, "to": dest, "gross_amount": gross_amount})


@app.route("/gift_cards/vouchers/2/<int:voucher_id>/adjust", methods=["POST"])
def price_manipulation_voucher_2(voucher_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE vouchers SET charged_amount = ? WHERE id = ?", (charged, voucher_id))
    conn.commit()
    conn.close()
    return jsonify({"voucher_id": voucher_id, "list_price": list_price, "charged": charged})


@app.route("/gift_cards/statements/3", methods=["GET"])
def raw_sql_list_statement_3():
    """Raw SQL injection: the account_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    account_id = request.args.get("account_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM statements WHERE account_id = '{account_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"statements": rows, "count": len(rows)})


@app.route("/gift_cards/promo_codes/4/<int:promo_code_id>/approve", methods=["POST"])
def broken_admin_check_promo_code_4(promo_code_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a promo_code."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE promo_codes SET status = 'approved', approved_by = ? WHERE id = ?", (user, promo_code_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "promo_code_id": promo_code_id, "by": user})


@app.route("/gift_cards/usage_records/5/<int:usage_record_id>/void", methods=["POST"])
def wrong_authz_usage_record_5(usage_record_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a usage_record."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE usage_records SET status = 'void' WHERE id = ?", (usage_record_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "usage_record_id": usage_record_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/gift_cards/gateways/6/<int:gateway_id>/credit", methods=["POST"])
def idor_credit_gateway_6(gateway_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    gateway id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO gateways_credits (gateway_id, total, reason) VALUES (?, ?, ?)",
        (gateway_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "gateway_id": gateway_id, "reason": reason})


@app.route("/gift_cards/reconciliations/7/<int:reconciliation_id>/export", methods=["GET"])
def idor_export_reconciliation_7(reconciliation_id):
    """IDOR: returns the full reconciliation record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM reconciliations WHERE record_id = {reconciliation_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"reconciliation": list(row)})


@app.route("/gift_cards/quotes/8/<int:quote_id>", methods=["GET"])
def idor_get_quote_8(quote_id):
    """IDOR: fetches a quote by id with no ownership/authz check, so any caller
    can read any tenant's quote."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, quote_name, merchant_id, amount FROM quotes WHERE uid = ?", (quote_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "quote not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/gift_cards/gift_cards/9/<int:gift_card_id>", methods=["DELETE"])
def idor_delete_gift_card_9(gift_card_id):
    """IDOR + missing authz: deletes any gift_card by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM gift_cards WHERE uid = ?", (gift_card_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "gift_card_id": gift_card_id})


if __name__ == "__main__":
    app.run(debug=True)
