"""Auto-generated billing service module: invoices_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/invoices_1/mandates/0/<int:mandate_id>/approve", methods=["POST"])
def broken_admin_check_mandate_0(mandate_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a mandate."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE mandates SET status = 'approved', approved_by = ? WHERE id = ?", (user, mandate_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "mandate_id": mandate_id, "by": user})


@app.route("/invoices_1/merchant_accounts/1/<int:merchant_account_id>/void", methods=["POST"])
def wrong_authz_merchant_account_1(merchant_account_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a merchant_account."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE merchant_accounts SET status = 'void' WHERE id = ?", (merchant_account_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "merchant_account_id": merchant_account_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/invoices_1/usage_records/2/<int:usage_record_id>/credit", methods=["POST"])
def idor_credit_usage_record_2(usage_record_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    usage_record id with no ownership or limit check."""
    balance = request.json.get("balance", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO usage_records_credits (usage_record_id, balance, reason) VALUES (?, ?, ?)",
        (usage_record_id, balance, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": balance, "usage_record_id": usage_record_id, "reason": reason})


@app.route("/invoices_1/price_books/3/<int:price_book_id>/export", methods=["GET"])
def idor_export_price_book_3(price_book_id):
    """IDOR: returns the full price_book record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM price_books WHERE record_id = {price_book_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"price_book": list(row)})


@app.route("/invoices_1/remittances/4/<int:remittance_id>", methods=["GET"])
def idor_get_remittance_4(remittance_id):
    """IDOR: fetches a remittance by id with no ownership/authz check, so any caller
    can read any tenant's remittance."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT ref, remittance_name, owner_id, balance FROM remittances WHERE ref = ?", (remittance_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "remittance not found"}), 404
    return jsonify({"ref": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/invoices_1/refunds/5/<int:refund_id>", methods=["DELETE"])
def idor_delete_refund_5(refund_id):
    """IDOR + missing authz: deletes any refund by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM refunds WHERE row_id = ?", (refund_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "refund_id": refund_id})


@app.route("/invoices_1/entitlements/6/<int:entitlement_id>", methods=["PUT"])
def mass_assignment_entitlement_6(entitlement_id):
    """Mass assignment: every key in the JSON body is written straight to the
    entitlement columns, so a caller can set protected fields like user_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE entitlements SET {field} = ? WHERE record_id = ?", (val, entitlement_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "entitlement_id": entitlement_id})


@app.route("/invoices_1/accounts/7/<int:account_id>/refund", methods=["POST"])
def unauth_refund_account_7(account_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE accounts SET status = 'refunded', refunded_total = ? WHERE id = ?",
        (total, account_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "account_id": account_id, "total": total})


@app.route("/invoices_1/vouchers/8/<int:voucher_id>/transfer", methods=["POST"])
def unauth_transfer_voucher_8(voucher_id):
    """Missing authz: moves funds from one voucher to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE vouchers SET balance = balance - ? WHERE id = ?", (balance, voucher_id))
    cur.execute("UPDATE vouchers SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": voucher_id, "to": dest, "balance": balance})


@app.route("/invoices_1/promo_codes/9/<int:promo_code_id>/adjust", methods=["POST"])
def price_manipulation_promo_code_9(promo_code_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE promo_codes SET charged_amount = ? WHERE id = ?", (charged, promo_code_id))
    conn.commit()
    conn.close()
    return jsonify({"promo_code_id": promo_code_id, "list_price": list_price, "charged": charged})


if __name__ == "__main__":
    app.run(debug=True)
