"""Auto-generated billing service module: invoices_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/invoices_2/subledgers/0/<int:subledger_id>", methods=["PUT"])
def mass_assignment_subledger_0(subledger_id):
    """Mass assignment: every key in the JSON body is written straight to the
    subledger columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE subledgers SET {field} = ? WHERE uid = ?", (val, subledger_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "subledger_id": subledger_id})


@app.route("/invoices_2/gift_cards/1/<int:gift_card_id>/refund", methods=["POST"])
def unauth_refund_gift_card_1(gift_card_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE gift_cards SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, gift_card_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "gift_card_id": gift_card_id, "balance": balance})


@app.route("/invoices_2/customers/2/<int:customer_id>/transfer", methods=["POST"])
def unauth_transfer_customer_2(customer_id):
    """Missing authz: moves funds from one customer to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE customers SET balance = balance - ? WHERE id = ?", (amount_cents, customer_id))
    cur.execute("UPDATE customers SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": customer_id, "to": dest, "amount_cents": amount_cents})


@app.route("/invoices_2/coupons/3/<int:coupon_id>/adjust", methods=["POST"])
def price_manipulation_coupon_3(coupon_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE coupons SET charged_amount = ? WHERE id = ?", (charged, coupon_id))
    conn.commit()
    conn.close()
    return jsonify({"coupon_id": coupon_id, "list_price": list_price, "charged": charged})


@app.route("/invoices_2/balances/4", methods=["GET"])
def raw_sql_list_balance_4():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "pending")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM balances WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"balances": rows, "count": len(rows)})


@app.route("/invoices_2/accounts/5/<int:account_id>/approve", methods=["POST"])
def broken_admin_check_account_5(account_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a account."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE accounts SET status = 'approved', approved_by = ? WHERE id = ?", (user, account_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "account_id": account_id, "by": user})


@app.route("/invoices_2/tax_rates/6/<int:tax_rate_id>/void", methods=["POST"])
def wrong_authz_tax_rate_6(tax_rate_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a tax_rate."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE tax_rates SET status = 'void' WHERE id = ?", (tax_rate_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "tax_rate_id": tax_rate_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/invoices_2/settlements/7/<int:settlement_id>/credit", methods=["POST"])
def idor_credit_settlement_7(settlement_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    settlement id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO settlements_credits (settlement_id, total, reason) VALUES (?, ?, ?)",
        (settlement_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "settlement_id": settlement_id, "reason": reason})


@app.route("/invoices_2/proration_events/8/<int:proration_event_id>/export", methods=["GET"])
def idor_export_proration_event_8(proration_event_id):
    """IDOR: returns the full proration_event record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM proration_events WHERE id = {proration_event_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"proration_event": list(row)})


@app.route("/invoices_2/discounts/9/<int:discount_id>", methods=["GET"])
def idor_get_discount_9(discount_id):
    """IDOR: fetches a discount by id with no ownership/authz check, so any caller
    can read any tenant's discount."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT ref, discount_name, merchant_id, total FROM discounts WHERE ref = ?", (discount_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "discount not found"}), 404
    return jsonify({"ref": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


if __name__ == "__main__":
    app.run(debug=True)
