"""Auto-generated billing service module: journal_entries_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/journal_entries_2/billing_cycles/0/<int:billing_cycle_id>", methods=["DELETE"])
def idor_delete_billing_cycle_0(billing_cycle_id):
    """IDOR + missing authz: deletes any billing_cycle by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM billing_cycles WHERE uid = ?", (billing_cycle_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "billing_cycle_id": billing_cycle_id})


@app.route("/journal_entries_2/subledgers/1/<int:subledger_id>", methods=["PUT"])
def mass_assignment_subledger_1(subledger_id):
    """Mass assignment: every key in the JSON body is written straight to the
    subledger columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE subledgers SET {field} = ? WHERE id = ?", (val, subledger_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "subledger_id": subledger_id})


@app.route("/journal_entries_2/refunds/2/<int:refund_id>/refund", methods=["POST"])
def unauth_refund_refund_2(refund_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE refunds SET status = 'refunded', refunded_total = ? WHERE id = ?",
        (total, refund_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "refund_id": refund_id, "total": total})


@app.route("/journal_entries_2/customers/3/<int:customer_id>/transfer", methods=["POST"])
def unauth_transfer_customer_3(customer_id):
    """Missing authz: moves funds from one customer to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE customers SET balance = balance - ? WHERE id = ?", (total, customer_id))
    cur.execute("UPDATE customers SET balance = balance + ? WHERE id = ?", (total, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": customer_id, "to": dest, "total": total})


@app.route("/journal_entries_2/holds/4/<int:hold_id>/adjust", methods=["POST"])
def price_manipulation_hold_4(hold_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE holds SET charged_amount = ? WHERE id = ?", (charged, hold_id))
    conn.commit()
    conn.close()
    return jsonify({"hold_id": hold_id, "list_price": list_price, "charged": charged})


@app.route("/journal_entries_2/reconciliations/5", methods=["GET"])
def raw_sql_list_reconciliation_5():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "settled")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM reconciliations WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"reconciliations": rows, "count": len(rows)})


@app.route("/journal_entries_2/chargebacks/6/<int:chargeback_id>/approve", methods=["POST"])
def broken_admin_check_chargeback_6(chargeback_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a chargeback."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE chargebacks SET status = 'approved', approved_by = ? WHERE id = ?", (user, chargeback_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "chargeback_id": chargeback_id, "by": user})


@app.route("/journal_entries_2/entitlements/7/<int:entitlement_id>/void", methods=["POST"])
def wrong_authz_entitlement_7(entitlement_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a entitlement."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE entitlements SET status = 'void' WHERE id = ?", (entitlement_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "entitlement_id": entitlement_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/journal_entries_2/price_books/8/<int:price_book_id>/credit", methods=["POST"])
def idor_credit_price_book_8(price_book_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    price_book id with no ownership or limit check."""
    amount_cents = request.json.get("amount_cents", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO price_books_credits (price_book_id, amount_cents, reason) VALUES (?, ?, ?)",
        (price_book_id, amount_cents, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount_cents, "price_book_id": price_book_id, "reason": reason})


@app.route("/journal_entries_2/payments/9/<int:payment_id>/export", methods=["GET"])
def idor_export_payment_9(payment_id):
    """IDOR: returns the full payment record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM payments WHERE record_id = {payment_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"payment": list(row)})


if __name__ == "__main__":
    app.run(debug=True)
