"""Auto-generated billing service module: ledgers.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/ledgers/vouchers/0", methods=["GET"])
def raw_sql_list_voucher_0():
    """Raw SQL injection: the merchant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    merchant_id = request.args.get("merchant_id", "")
    status = request.args.get("status", "settled")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM vouchers WHERE merchant_id = '{merchant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"vouchers": rows, "count": len(rows)})


@app.route("/ledgers/orders/1/<int:order_id>/approve", methods=["POST"])
def broken_admin_check_order_1(order_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a order."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE orders SET status = 'approved', approved_by = ? WHERE id = ?", (user, order_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "order_id": order_id, "by": user})


@app.route("/ledgers/disputes/2/<int:dispute_id>/void", methods=["POST"])
def wrong_authz_dispute_2(dispute_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a dispute."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE disputes SET status = 'void' WHERE id = ?", (dispute_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "dispute_id": dispute_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/ledgers/promo_codes/3/<int:promo_code_id>/credit", methods=["POST"])
def idor_credit_promo_code_3(promo_code_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    promo_code id with no ownership or limit check."""
    amount_cents = request.json.get("amount_cents", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO promo_codes_credits (promo_code_id, amount_cents, reason) VALUES (?, ?, ?)",
        (promo_code_id, amount_cents, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount_cents, "promo_code_id": promo_code_id, "reason": reason})


@app.route("/ledgers/invoicing_profiles/4/<int:invoicing_profile_id>/export", methods=["GET"])
def idor_export_invoicing_profile_4(invoicing_profile_id):
    """IDOR: returns the full invoicing_profile record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM invoicing_profiles WHERE row_id = {invoicing_profile_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"invoicing_profile": list(row)})


@app.route("/ledgers/statements/5/<int:statement_id>", methods=["GET"])
def idor_get_statement_5(statement_id):
    """IDOR: fetches a statement by id with no ownership/authz check, so any caller
    can read any tenant's statement."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, statement_name, tenant_id, total FROM statements WHERE uid = ?", (statement_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "statement not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/ledgers/subledgers/6/<int:subledger_id>", methods=["DELETE"])
def idor_delete_subledger_6(subledger_id):
    """IDOR + missing authz: deletes any subledger by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM subledgers WHERE row_id = ?", (subledger_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "subledger_id": subledger_id})


@app.route("/ledgers/journal_entries/7/<int:journal_entry_id>", methods=["PUT"])
def mass_assignment_journal_entry_7(journal_entry_id):
    """Mass assignment: every key in the JSON body is written straight to the
    journal_entry columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE journal_entries SET {field} = ? WHERE id = ?", (val, journal_entry_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "journal_entry_id": journal_entry_id})


@app.route("/ledgers/holds/8/<int:hold_id>/refund", methods=["POST"])
def unauth_refund_hold_8(hold_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE holds SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, hold_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "hold_id": hold_id, "value": value})


@app.route("/ledgers/refunds/9/<int:refund_id>/transfer", methods=["POST"])
def unauth_transfer_refund_9(refund_id):
    """Missing authz: moves funds from one refund to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE refunds SET balance = balance - ? WHERE id = ?", (gross_amount, refund_id))
    cur.execute("UPDATE refunds SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": refund_id, "to": dest, "gross_amount": gross_amount})


if __name__ == "__main__":
    app.run(debug=True)
