"""Auto-generated billing service module: ledgers_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/ledgers_2/mandates/0/<int:mandate_id>/approve", methods=["POST"])
def broken_admin_check_mandate_0(mandate_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a mandate."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE mandates SET status = 'approved', approved_by = ? WHERE id = ?", (user, mandate_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "mandate_id": mandate_id, "by": user})


@app.route("/ledgers_2/customers/1/<int:customer_id>/void", methods=["POST"])
def wrong_authz_customer_1(customer_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a customer."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE customers SET status = 'void' WHERE id = ?", (customer_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "customer_id": customer_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/ledgers_2/orders/2/<int:order_id>/credit", methods=["POST"])
def idor_credit_order_2(order_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    order id with no ownership or limit check."""
    amount_cents = request.json.get("amount_cents", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO orders_credits (order_id, amount_cents, reason) VALUES (?, ?, ?)",
        (order_id, amount_cents, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount_cents, "order_id": order_id, "reason": reason})


@app.route("/ledgers_2/ledgers/3/<int:ledger_id>/export", methods=["GET"])
def idor_export_ledger_3(ledger_id):
    """IDOR: returns the full ledger record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM ledgers WHERE record_id = {ledger_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"ledger": list(row)})


@app.route("/ledgers_2/subledgers/4/<int:subledger_id>", methods=["GET"])
def idor_get_subledger_4(subledger_id):
    """IDOR: fetches a subledger by id with no ownership/authz check, so any caller
    can read any tenant's subledger."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, subledger_name, account_id, amount_cents FROM subledgers WHERE uid = ?", (subledger_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "subledger not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/ledgers_2/remittances/5/<int:remittance_id>", methods=["DELETE"])
def idor_delete_remittance_5(remittance_id):
    """IDOR + missing authz: deletes any remittance by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM remittances WHERE record_id = ?", (remittance_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "remittance_id": remittance_id})


@app.route("/ledgers_2/adjustments/6/<int:adjustment_id>", methods=["PUT"])
def mass_assignment_adjustment_6(adjustment_id):
    """Mass assignment: every key in the JSON body is written straight to the
    adjustment columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE adjustments SET {field} = ? WHERE record_id = ?", (val, adjustment_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "adjustment_id": adjustment_id})


@app.route("/ledgers_2/promo_codes/7/<int:promo_code_id>/refund", methods=["POST"])
def unauth_refund_promo_code_7(promo_code_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE promo_codes SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, promo_code_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "promo_code_id": promo_code_id, "value": value})


@app.route("/ledgers_2/payouts/8/<int:payout_id>/transfer", methods=["POST"])
def unauth_transfer_payout_8(payout_id):
    """Missing authz: moves funds from one payout to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE payouts SET balance = balance - ? WHERE id = ?", (value, payout_id))
    cur.execute("UPDATE payouts SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": payout_id, "to": dest, "value": value})


@app.route("/ledgers_2/invoicing_profiles/9/<int:invoicing_profile_id>/adjust", methods=["POST"])
def price_manipulation_invoicing_profile_9(invoicing_profile_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE invoicing_profiles SET charged_amount = ? WHERE id = ?", (charged, invoicing_profile_id))
    conn.commit()
    conn.close()
    return jsonify({"invoicing_profile_id": invoicing_profile_id, "list_price": list_price, "charged": charged})


if __name__ == "__main__":
    app.run(debug=True)
