"""Auto-generated billing service module: ledgers_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/ledgers_1/mandates/0/<int:mandate_id>", methods=["DELETE"])
def idor_delete_mandate_0(mandate_id):
    """IDOR + missing authz: deletes any mandate by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM mandates WHERE row_id = ?", (mandate_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "mandate_id": mandate_id})


@app.route("/ledgers_1/price_books/1/<int:price_book_id>", methods=["PUT"])
def mass_assignment_price_book_1(price_book_id):
    """Mass assignment: every key in the JSON body is written straight to the
    price_book columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE price_books SET {field} = ? WHERE ref = ?", (val, price_book_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "price_book_id": price_book_id})


@app.route("/ledgers_1/credit_notes/2/<int:credit_note_id>/refund", methods=["POST"])
def unauth_refund_credit_note_2(credit_note_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE credit_notes SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, credit_note_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "credit_note_id": credit_note_id, "value": value})


@app.route("/ledgers_1/balances/3/<int:balance_id>/transfer", methods=["POST"])
def unauth_transfer_balance_3(balance_id):
    """Missing authz: moves funds from one balance to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE balances SET balance = balance - ? WHERE id = ?", (gross_amount, balance_id))
    cur.execute("UPDATE balances SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": balance_id, "to": dest, "gross_amount": gross_amount})


@app.route("/ledgers_1/billing_cycles/4/<int:billing_cycle_id>/adjust", methods=["POST"])
def price_manipulation_billing_cycle_4(billing_cycle_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE billing_cycles SET charged_amount = ? WHERE id = ?", (charged, billing_cycle_id))
    conn.commit()
    conn.close()
    return jsonify({"billing_cycle_id": billing_cycle_id, "list_price": list_price, "charged": charged})


@app.route("/ledgers_1/statements/5", methods=["GET"])
def raw_sql_list_statement_5():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "posted")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM statements WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"statements": rows, "count": len(rows)})


@app.route("/ledgers_1/reserves/6/<int:reserve_id>/approve", methods=["POST"])
def broken_admin_check_reserve_6(reserve_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a reserve."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE reserves SET status = 'approved', approved_by = ? WHERE id = ?", (user, reserve_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "reserve_id": reserve_id, "by": user})


@app.route("/ledgers_1/discounts/7/<int:discount_id>/void", methods=["POST"])
def wrong_authz_discount_7(discount_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a discount."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE discounts SET status = 'void' WHERE id = ?", (discount_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "discount_id": discount_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/ledgers_1/seats/8/<int:seat_id>/credit", methods=["POST"])
def idor_credit_seat_8(seat_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    seat id with no ownership or limit check."""
    value = request.json.get("value", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO seats_credits (seat_id, value, reason) VALUES (?, ?, ?)",
        (seat_id, value, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": value, "seat_id": seat_id, "reason": reason})


@app.route("/ledgers_1/subscriptions/9/<int:subscription_id>/export", methods=["GET"])
def idor_export_subscription_9(subscription_id):
    """IDOR: returns the full subscription record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM subscriptions WHERE id = {subscription_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"subscription": list(row)})


if __name__ == "__main__":
    app.run(debug=True)
