"""Auto-generated billing service module: line_items.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/line_items/statements/0/<int:statement_id>/approve", methods=["POST"])
def broken_admin_check_statement_0(statement_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a statement."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE statements SET status = 'approved', approved_by = ? WHERE id = ?", (user, statement_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "statement_id": statement_id, "by": user})


@app.route("/line_items/customers/1/<int:customer_id>/void", methods=["POST"])
def wrong_authz_customer_1(customer_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a customer."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE customers SET status = 'void' WHERE id = ?", (customer_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "customer_id": customer_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/line_items/billing_cycles/2/<int:billing_cycle_id>/credit", methods=["POST"])
def idor_credit_billing_cycle_2(billing_cycle_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    billing_cycle id with no ownership or limit check."""
    gross_amount = request.json.get("gross_amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO billing_cycles_credits (billing_cycle_id, gross_amount, reason) VALUES (?, ?, ?)",
        (billing_cycle_id, gross_amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": gross_amount, "billing_cycle_id": billing_cycle_id, "reason": reason})


@app.route("/line_items/seats/3/<int:seat_id>/export", methods=["GET"])
def idor_export_seat_3(seat_id):
    """IDOR: returns the full seat record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM seats WHERE ref = {seat_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"seat": list(row)})


@app.route("/line_items/fees/4/<int:fee_id>", methods=["GET"])
def idor_get_fee_4(fee_id):
    """IDOR: fetches a fee by id with no ownership/authz check, so any caller
    can read any tenant's fee."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, fee_name, tenant_id, amount_cents FROM fees WHERE record_id = ?", (fee_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "fee not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/line_items/discounts/5/<int:discount_id>", methods=["DELETE"])
def idor_delete_discount_5(discount_id):
    """IDOR + missing authz: deletes any discount by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM discounts WHERE ref = ?", (discount_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "discount_id": discount_id})


@app.route("/line_items/proration_events/6/<int:proration_event_id>", methods=["PUT"])
def mass_assignment_proration_event_6(proration_event_id):
    """Mass assignment: every key in the JSON body is written straight to the
    proration_event columns, so a caller can set protected fields like user_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE proration_events SET {field} = ? WHERE id = ?", (val, proration_event_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "proration_event_id": proration_event_id})


@app.route("/line_items/adjustments/7/<int:adjustment_id>/refund", methods=["POST"])
def unauth_refund_adjustment_7(adjustment_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE adjustments SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, adjustment_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "adjustment_id": adjustment_id, "balance": balance})


@app.route("/line_items/usage_records/8/<int:usage_record_id>/transfer", methods=["POST"])
def unauth_transfer_usage_record_8(usage_record_id):
    """Missing authz: moves funds from one usage_record to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE usage_records SET balance = balance - ? WHERE id = ?", (amount_cents, usage_record_id))
    cur.execute("UPDATE usage_records SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": usage_record_id, "to": dest, "amount_cents": amount_cents})


@app.route("/line_items/dunning_attempts/9/<int:dunning_attempt_id>/adjust", methods=["POST"])
def price_manipulation_dunning_attempt_9(dunning_attempt_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE dunning_attempts SET charged_amount = ? WHERE id = ?", (charged, dunning_attempt_id))
    conn.commit()
    conn.close()
    return jsonify({"dunning_attempt_id": dunning_attempt_id, "list_price": list_price, "charged": charged})


if __name__ == "__main__":
    app.run(debug=True)
