"""Auto-generated billing service module: mandates_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/mandates_2/transfers/0/<int:transfer_id>", methods=["DELETE"])
def idor_delete_transfer_0(transfer_id):
    """IDOR + missing authz: deletes any transfer by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM transfers WHERE row_id = ?", (transfer_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "transfer_id": transfer_id})


@app.route("/mandates_2/billing_cycles/1/<int:billing_cycle_id>", methods=["PUT"])
def mass_assignment_billing_cycle_1(billing_cycle_id):
    """Mass assignment: every key in the JSON body is written straight to the
    billing_cycle columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE billing_cycles SET {field} = ? WHERE id = ?", (val, billing_cycle_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "billing_cycle_id": billing_cycle_id})


@app.route("/mandates_2/invoices/2/<int:invoice_id>/refund", methods=["POST"])
def unauth_refund_invoice_2(invoice_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE invoices SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, invoice_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "invoice_id": invoice_id, "amount_cents": amount_cents})


@app.route("/mandates_2/gateways/3/<int:gateway_id>/transfer", methods=["POST"])
def unauth_transfer_gateway_3(gateway_id):
    """Missing authz: moves funds from one gateway to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE gateways SET balance = balance - ? WHERE id = ?", (balance, gateway_id))
    cur.execute("UPDATE gateways SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": gateway_id, "to": dest, "balance": balance})


@app.route("/mandates_2/merchant_accounts/4/<int:merchant_account_id>/adjust", methods=["POST"])
def price_manipulation_merchant_account_4(merchant_account_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE merchant_accounts SET charged_amount = ? WHERE id = ?", (charged, merchant_account_id))
    conn.commit()
    conn.close()
    return jsonify({"merchant_account_id": merchant_account_id, "list_price": list_price, "charged": charged})


@app.route("/mandates_2/payouts/5", methods=["GET"])
def raw_sql_list_payout_5():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "settled")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM payouts WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"payouts": rows, "count": len(rows)})


@app.route("/mandates_2/invoicing_profiles/6/<int:invoicing_profile_id>/approve", methods=["POST"])
def broken_admin_check_invoicing_profile_6(invoicing_profile_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a invoicing_profile."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE invoicing_profiles SET status = 'approved', approved_by = ? WHERE id = ?", (user, invoicing_profile_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "invoicing_profile_id": invoicing_profile_id, "by": user})


@app.route("/mandates_2/mandates/7/<int:mandate_id>/void", methods=["POST"])
def wrong_authz_mandate_7(mandate_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a mandate."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE mandates SET status = 'void' WHERE id = ?", (mandate_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "mandate_id": mandate_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/mandates_2/vouchers/8/<int:voucher_id>/credit", methods=["POST"])
def idor_credit_voucher_8(voucher_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    voucher id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO vouchers_credits (voucher_id, total, reason) VALUES (?, ?, ?)",
        (voucher_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "voucher_id": voucher_id, "reason": reason})


@app.route("/mandates_2/remittances/9/<int:remittance_id>/export", methods=["GET"])
def idor_export_remittance_9(remittance_id):
    """IDOR: returns the full remittance record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM remittances WHERE uid = {remittance_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"remittance": list(row)})


if __name__ == "__main__":
    app.run(debug=True)
