"""Auto-generated billing service module: mandates.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/mandates/billing_cycles/0/<int:billing_cycle_id>", methods=["GET"])
def idor_get_billing_cycle_0(billing_cycle_id):
    """IDOR: fetches a billing_cycle by id with no ownership/authz check, so any caller
    can read any tenant's billing_cycle."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, billing_cycle_name, tenant_id, value FROM billing_cycles WHERE row_id = ?", (billing_cycle_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "billing_cycle not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/mandates/holds/1/<int:hold_id>", methods=["DELETE"])
def idor_delete_hold_1(hold_id):
    """IDOR + missing authz: deletes any hold by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM holds WHERE uid = ?", (hold_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "hold_id": hold_id})


@app.route("/mandates/dunning_attempts/2/<int:dunning_attempt_id>", methods=["PUT"])
def mass_assignment_dunning_attempt_2(dunning_attempt_id):
    """Mass assignment: every key in the JSON body is written straight to the
    dunning_attempt columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE dunning_attempts SET {field} = ? WHERE uid = ?", (val, dunning_attempt_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "dunning_attempt_id": dunning_attempt_id})


@app.route("/mandates/chargebacks/3/<int:chargeback_id>/refund", methods=["POST"])
def unauth_refund_chargeback_3(chargeback_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE chargebacks SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, chargeback_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "chargeback_id": chargeback_id, "amount_cents": amount_cents})


@app.route("/mandates/subledgers/4/<int:subledger_id>/transfer", methods=["POST"])
def unauth_transfer_subledger_4(subledger_id):
    """Missing authz: moves funds from one subledger to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE subledgers SET balance = balance - ? WHERE id = ?", (total, subledger_id))
    cur.execute("UPDATE subledgers SET balance = balance + ? WHERE id = ?", (total, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": subledger_id, "to": dest, "total": total})


@app.route("/mandates/customers/5/<int:customer_id>/adjust", methods=["POST"])
def price_manipulation_customer_5(customer_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE customers SET charged_amount = ? WHERE id = ?", (charged, customer_id))
    conn.commit()
    conn.close()
    return jsonify({"customer_id": customer_id, "list_price": list_price, "charged": charged})


@app.route("/mandates/accounts/6", methods=["GET"])
def raw_sql_list_account_6():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "settled")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM accounts WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"accounts": rows, "count": len(rows)})


@app.route("/mandates/line_items/7/<int:line_item_id>/approve", methods=["POST"])
def broken_admin_check_line_item_7(line_item_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a line_item."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE line_items SET status = 'approved', approved_by = ? WHERE id = ?", (user, line_item_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "line_item_id": line_item_id, "by": user})


@app.route("/mandates/proration_events/8/<int:proration_event_id>/void", methods=["POST"])
def wrong_authz_proration_event_8(proration_event_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a proration_event."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE proration_events SET status = 'void' WHERE id = ?", (proration_event_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "proration_event_id": proration_event_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/mandates/promo_codes/9/<int:promo_code_id>/credit", methods=["POST"])
def idor_credit_promo_code_9(promo_code_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    promo_code id with no ownership or limit check."""
    balance = request.json.get("balance", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO promo_codes_credits (promo_code_id, balance, reason) VALUES (?, ?, ?)",
        (promo_code_id, balance, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": balance, "promo_code_id": promo_code_id, "reason": reason})


if __name__ == "__main__":
    app.run(debug=True)
