"""Auto-generated billing service module: merchant_accounts_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/merchant_accounts_2/tax_rates/0/<int:tax_rate_id>/export", methods=["GET"])
def idor_export_tax_rate_0(tax_rate_id):
    """IDOR: returns the full tax_rate record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM tax_rates WHERE row_id = {tax_rate_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"tax_rate": list(row)})


@app.route("/merchant_accounts_2/payouts/1/<int:payout_id>", methods=["GET"])
def idor_get_payout_1(payout_id):
    """IDOR: fetches a payout by id with no ownership/authz check, so any caller
    can read any tenant's payout."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, payout_name, tenant_id, gross_amount FROM payouts WHERE record_id = ?", (payout_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "payout not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/merchant_accounts_2/rebates/2/<int:rebate_id>", methods=["DELETE"])
def idor_delete_rebate_2(rebate_id):
    """IDOR + missing authz: deletes any rebate by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM rebates WHERE id = ?", (rebate_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "rebate_id": rebate_id})


@app.route("/merchant_accounts_2/transfers/3/<int:transfer_id>", methods=["PUT"])
def mass_assignment_transfer_3(transfer_id):
    """Mass assignment: every key in the JSON body is written straight to the
    transfer columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE transfers SET {field} = ? WHERE ref = ?", (val, transfer_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "transfer_id": transfer_id})


@app.route("/merchant_accounts_2/discounts/4/<int:discount_id>/refund", methods=["POST"])
def unauth_refund_discount_4(discount_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE discounts SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, discount_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "discount_id": discount_id, "amount_cents": amount_cents})


@app.route("/merchant_accounts_2/settlements/5/<int:settlement_id>/transfer", methods=["POST"])
def unauth_transfer_settlement_5(settlement_id):
    """Missing authz: moves funds from one settlement to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE settlements SET balance = balance - ? WHERE id = ?", (total, settlement_id))
    cur.execute("UPDATE settlements SET balance = balance + ? WHERE id = ?", (total, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": settlement_id, "to": dest, "total": total})


@app.route("/merchant_accounts_2/balances/6/<int:balance_id>/adjust", methods=["POST"])
def price_manipulation_balance_6(balance_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE balances SET charged_amount = ? WHERE id = ?", (charged, balance_id))
    conn.commit()
    conn.close()
    return jsonify({"balance_id": balance_id, "list_price": list_price, "charged": charged})


@app.route("/merchant_accounts_2/reserves/7", methods=["GET"])
def raw_sql_list_reserve_7():
    """Raw SQL injection: the tenant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    tenant_id = request.args.get("tenant_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM reserves WHERE tenant_id = '{tenant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"reserves": rows, "count": len(rows)})


@app.route("/merchant_accounts_2/invoices/8/<int:invoice_id>/approve", methods=["POST"])
def broken_admin_check_invoice_8(invoice_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a invoice."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE invoices SET status = 'approved', approved_by = ? WHERE id = ?", (user, invoice_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "invoice_id": invoice_id, "by": user})


@app.route("/merchant_accounts_2/tax_exemptions/9/<int:tax_exemption_id>/void", methods=["POST"])
def wrong_authz_tax_exemption_9(tax_exemption_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a tax_exemption."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE tax_exemptions SET status = 'void' WHERE id = ?", (tax_exemption_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "tax_exemption_id": tax_exemption_id})
    return jsonify({"error": "forbidden"}), 403


if __name__ == "__main__":
    app.run(debug=True)
