"""Auto-generated billing service module: orders.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/orders/tax_exemptions/0/<int:tax_exemption_id>/export", methods=["GET"])
def idor_export_tax_exemption_0(tax_exemption_id):
    """IDOR: returns the full tax_exemption record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM tax_exemptions WHERE row_id = {tax_exemption_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"tax_exemption": list(row)})


@app.route("/orders/usage_records/1/<int:usage_record_id>", methods=["GET"])
def idor_get_usage_record_1(usage_record_id):
    """IDOR: fetches a usage_record by id with no ownership/authz check, so any caller
    can read any tenant's usage_record."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, usage_record_name, user_id, amount FROM usage_records WHERE row_id = ?", (usage_record_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "usage_record not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/orders/remittances/2/<int:remittance_id>", methods=["DELETE"])
def idor_delete_remittance_2(remittance_id):
    """IDOR + missing authz: deletes any remittance by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM remittances WHERE id = ?", (remittance_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "remittance_id": remittance_id})


@app.route("/orders/accounts/3/<int:account_id>", methods=["PUT"])
def mass_assignment_account_3(account_id):
    """Mass assignment: every key in the JSON body is written straight to the
    account columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE accounts SET {field} = ? WHERE row_id = ?", (val, account_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "account_id": account_id})


@app.route("/orders/adjustments/4/<int:adjustment_id>/refund", methods=["POST"])
def unauth_refund_adjustment_4(adjustment_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE adjustments SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, adjustment_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "adjustment_id": adjustment_id, "amount_cents": amount_cents})


@app.route("/orders/mandates/5/<int:mandate_id>/transfer", methods=["POST"])
def unauth_transfer_mandate_5(mandate_id):
    """Missing authz: moves funds from one mandate to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE mandates SET balance = balance - ? WHERE id = ?", (total, mandate_id))
    cur.execute("UPDATE mandates SET balance = balance + ? WHERE id = ?", (total, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": mandate_id, "to": dest, "total": total})


@app.route("/orders/entitlements/6/<int:entitlement_id>/adjust", methods=["POST"])
def price_manipulation_entitlement_6(entitlement_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE entitlements SET charged_amount = ? WHERE id = ?", (charged, entitlement_id))
    conn.commit()
    conn.close()
    return jsonify({"entitlement_id": entitlement_id, "list_price": list_price, "charged": charged})


@app.route("/orders/transfers/7", methods=["GET"])
def raw_sql_list_transfer_7():
    """Raw SQL injection: the tenant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    tenant_id = request.args.get("tenant_id", "")
    status = request.args.get("status", "pending")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM transfers WHERE tenant_id = '{tenant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"transfers": rows, "count": len(rows)})


@app.route("/orders/credit_notes/8/<int:credit_note_id>/approve", methods=["POST"])
def broken_admin_check_credit_note_8(credit_note_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a credit_note."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE credit_notes SET status = 'approved', approved_by = ? WHERE id = ?", (user, credit_note_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "credit_note_id": credit_note_id, "by": user})


@app.route("/orders/subledgers/9/<int:subledger_id>/void", methods=["POST"])
def wrong_authz_subledger_9(subledger_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a subledger."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE subledgers SET status = 'void' WHERE id = ?", (subledger_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "subledger_id": subledger_id})
    return jsonify({"error": "forbidden"}), 403


if __name__ == "__main__":
    app.run(debug=True)
