"""Auto-generated billing service module: orders_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/orders_2/merchant_accounts/0/<int:merchant_account_id>", methods=["GET"])
def idor_get_merchant_account_0(merchant_account_id):
    """IDOR: fetches a merchant_account by id with no ownership/authz check, so any caller
    can read any tenant's merchant_account."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, merchant_account_name, account_id, amount FROM merchant_accounts WHERE uid = ?", (merchant_account_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "merchant_account not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/orders_2/promo_codes/1/<int:promo_code_id>", methods=["DELETE"])
def idor_delete_promo_code_1(promo_code_id):
    """IDOR + missing authz: deletes any promo_code by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM promo_codes WHERE uid = ?", (promo_code_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "promo_code_id": promo_code_id})


@app.route("/orders_2/customers/2/<int:customer_id>", methods=["PUT"])
def mass_assignment_customer_2(customer_id):
    """Mass assignment: every key in the JSON body is written straight to the
    customer columns, so a caller can set protected fields like account_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE customers SET {field} = ? WHERE record_id = ?", (val, customer_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "customer_id": customer_id})


@app.route("/orders_2/refunds/3/<int:refund_id>/refund", methods=["POST"])
def unauth_refund_refund_3(refund_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE refunds SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, refund_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "refund_id": refund_id, "value": value})


@app.route("/orders_2/webhooks/4/<int:webhook_id>/transfer", methods=["POST"])
def unauth_transfer_webhook_4(webhook_id):
    """Missing authz: moves funds from one webhook to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE webhooks SET balance = balance - ? WHERE id = ?", (value, webhook_id))
    cur.execute("UPDATE webhooks SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": webhook_id, "to": dest, "value": value})


@app.route("/orders_2/dunning_attempts/5/<int:dunning_attempt_id>/adjust", methods=["POST"])
def price_manipulation_dunning_attempt_5(dunning_attempt_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE dunning_attempts SET charged_amount = ? WHERE id = ?", (charged, dunning_attempt_id))
    conn.commit()
    conn.close()
    return jsonify({"dunning_attempt_id": dunning_attempt_id, "list_price": list_price, "charged": charged})


@app.route("/orders_2/price_books/6", methods=["GET"])
def raw_sql_list_price_book_6():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "settled")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM price_books WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"price_books": rows, "count": len(rows)})


@app.route("/orders_2/orders/7/<int:order_id>/approve", methods=["POST"])
def broken_admin_check_order_7(order_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a order."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE orders SET status = 'approved', approved_by = ? WHERE id = ?", (user, order_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "order_id": order_id, "by": user})


@app.route("/orders_2/credits/8/<int:credit_id>/void", methods=["POST"])
def wrong_authz_credit_8(credit_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a credit."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE credits SET status = 'void' WHERE id = ?", (credit_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "credit_id": credit_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/orders_2/settlements/9/<int:settlement_id>/credit", methods=["POST"])
def idor_credit_settlement_9(settlement_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    settlement id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO settlements_credits (settlement_id, total, reason) VALUES (?, ?, ?)",
        (settlement_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "settlement_id": settlement_id, "reason": reason})


if __name__ == "__main__":
    app.run(debug=True)
