"""Auto-generated billing service module: payouts_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/payouts_1/reserves/0/<int:reserve_id>", methods=["PUT"])
def mass_assignment_reserve_0(reserve_id):
    """Mass assignment: every key in the JSON body is written straight to the
    reserve columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE reserves SET {field} = ? WHERE uid = ?", (val, reserve_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "reserve_id": reserve_id})


@app.route("/payouts_1/payments/1/<int:payment_id>/refund", methods=["POST"])
def unauth_refund_payment_1(payment_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE payments SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, payment_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "payment_id": payment_id, "amount_cents": amount_cents})


@app.route("/payouts_1/customers/2/<int:customer_id>/transfer", methods=["POST"])
def unauth_transfer_customer_2(customer_id):
    """Missing authz: moves funds from one customer to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE customers SET balance = balance - ? WHERE id = ?", (balance, customer_id))
    cur.execute("UPDATE customers SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": customer_id, "to": dest, "balance": balance})


@app.route("/payouts_1/gift_cards/3/<int:gift_card_id>/adjust", methods=["POST"])
def price_manipulation_gift_card_3(gift_card_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE gift_cards SET charged_amount = ? WHERE id = ?", (charged, gift_card_id))
    conn.commit()
    conn.close()
    return jsonify({"gift_card_id": gift_card_id, "list_price": list_price, "charged": charged})


@app.route("/payouts_1/payouts/4", methods=["GET"])
def raw_sql_list_payout_4():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "pending")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM payouts WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"payouts": rows, "count": len(rows)})


@app.route("/payouts_1/seats/5/<int:seat_id>/approve", methods=["POST"])
def broken_admin_check_seat_5(seat_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a seat."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE seats SET status = 'approved', approved_by = ? WHERE id = ?", (user, seat_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "seat_id": seat_id, "by": user})


@app.route("/payouts_1/subledgers/6/<int:subledger_id>/void", methods=["POST"])
def wrong_authz_subledger_6(subledger_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a subledger."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE subledgers SET status = 'void' WHERE id = ?", (subledger_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "subledger_id": subledger_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/payouts_1/credits/7/<int:credit_id>/credit", methods=["POST"])
def idor_credit_credit_7(credit_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    credit id with no ownership or limit check."""
    gross_amount = request.json.get("gross_amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO credits_credits (credit_id, gross_amount, reason) VALUES (?, ?, ?)",
        (credit_id, gross_amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": gross_amount, "credit_id": credit_id, "reason": reason})


@app.route("/payouts_1/wallets/8/<int:wallet_id>/export", methods=["GET"])
def idor_export_wallet_8(wallet_id):
    """IDOR: returns the full wallet record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM wallets WHERE uid = {wallet_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"wallet": list(row)})


@app.route("/payouts_1/journal_entries/9/<int:journal_entry_id>", methods=["GET"])
def idor_get_journal_entry_9(journal_entry_id):
    """IDOR: fetches a journal_entry by id with no ownership/authz check, so any caller
    can read any tenant's journal_entry."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, journal_entry_name, owner_id, balance FROM journal_entries WHERE uid = ?", (journal_entry_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "journal_entry not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


if __name__ == "__main__":
    app.run(debug=True)
