"""Auto-generated billing service module: plans_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/plans_2/fees/0/<int:fee_id>", methods=["GET"])
def idor_get_fee_0(fee_id):
    """IDOR: fetches a fee by id with no ownership/authz check, so any caller
    can read any tenant's fee."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT ref, fee_name, account_id, amount_cents FROM fees WHERE ref = ?", (fee_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "fee not found"}), 404
    return jsonify({"ref": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/plans_2/usage_records/1/<int:usage_record_id>", methods=["DELETE"])
def idor_delete_usage_record_1(usage_record_id):
    """IDOR + missing authz: deletes any usage_record by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM usage_records WHERE ref = ?", (usage_record_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "usage_record_id": usage_record_id})


@app.route("/plans_2/remittances/2/<int:remittance_id>", methods=["PUT"])
def mass_assignment_remittance_2(remittance_id):
    """Mass assignment: every key in the JSON body is written straight to the
    remittance columns, so a caller can set protected fields like account_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE remittances SET {field} = ? WHERE record_id = ?", (val, remittance_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "remittance_id": remittance_id})


@app.route("/plans_2/line_items/3/<int:line_item_id>/refund", methods=["POST"])
def unauth_refund_line_item_3(line_item_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE line_items SET status = 'refunded', refunded_total = ? WHERE id = ?",
        (total, line_item_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "line_item_id": line_item_id, "total": total})


@app.route("/plans_2/tax_exemptions/4/<int:tax_exemption_id>/transfer", methods=["POST"])
def unauth_transfer_tax_exemption_4(tax_exemption_id):
    """Missing authz: moves funds from one tax_exemption to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE tax_exemptions SET balance = balance - ? WHERE id = ?", (amount_cents, tax_exemption_id))
    cur.execute("UPDATE tax_exemptions SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": tax_exemption_id, "to": dest, "amount_cents": amount_cents})


@app.route("/plans_2/mandates/5/<int:mandate_id>/adjust", methods=["POST"])
def price_manipulation_mandate_5(mandate_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE mandates SET charged_amount = ? WHERE id = ?", (charged, mandate_id))
    conn.commit()
    conn.close()
    return jsonify({"mandate_id": mandate_id, "list_price": list_price, "charged": charged})


@app.route("/plans_2/invoices/6", methods=["GET"])
def raw_sql_list_invoice_6():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "posted")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM invoices WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"invoices": rows, "count": len(rows)})


@app.route("/plans_2/tax_rates/7/<int:tax_rate_id>/approve", methods=["POST"])
def broken_admin_check_tax_rate_7(tax_rate_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a tax_rate."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE tax_rates SET status = 'approved', approved_by = ? WHERE id = ?", (user, tax_rate_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "tax_rate_id": tax_rate_id, "by": user})


@app.route("/plans_2/settlements/8/<int:settlement_id>/void", methods=["POST"])
def wrong_authz_settlement_8(settlement_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a settlement."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE settlements SET status = 'void' WHERE id = ?", (settlement_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "settlement_id": settlement_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/plans_2/ledgers/9/<int:ledger_id>/credit", methods=["POST"])
def idor_credit_ledger_9(ledger_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    ledger id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO ledgers_credits (ledger_id, total, reason) VALUES (?, ?, ?)",
        (ledger_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "ledger_id": ledger_id, "reason": reason})


if __name__ == "__main__":
    app.run(debug=True)
