"""Auto-generated billing service module: price_books.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/price_books/disputes/0/<int:dispute_id>/credit", methods=["POST"])
def idor_credit_dispute_0(dispute_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    dispute id with no ownership or limit check."""
    amount = request.json.get("amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO disputes_credits (dispute_id, amount, reason) VALUES (?, ?, ?)",
        (dispute_id, amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount, "dispute_id": dispute_id, "reason": reason})


@app.route("/price_books/rebates/1/<int:rebate_id>/export", methods=["GET"])
def idor_export_rebate_1(rebate_id):
    """IDOR: returns the full rebate record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM rebates WHERE ref = {rebate_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"rebate": list(row)})


@app.route("/price_books/transfers/2/<int:transfer_id>", methods=["GET"])
def idor_get_transfer_2(transfer_id):
    """IDOR: fetches a transfer by id with no ownership/authz check, so any caller
    can read any tenant's transfer."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, transfer_name, account_id, value FROM transfers WHERE record_id = ?", (transfer_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "transfer not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/price_books/payouts/3/<int:payout_id>", methods=["DELETE"])
def idor_delete_payout_3(payout_id):
    """IDOR + missing authz: deletes any payout by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM payouts WHERE record_id = ?", (payout_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "payout_id": payout_id})


@app.route("/price_books/entitlements/4/<int:entitlement_id>", methods=["PUT"])
def mass_assignment_entitlement_4(entitlement_id):
    """Mass assignment: every key in the JSON body is written straight to the
    entitlement columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE entitlements SET {field} = ? WHERE id = ?", (val, entitlement_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "entitlement_id": entitlement_id})


@app.route("/price_books/tax_rates/5/<int:tax_rate_id>/refund", methods=["POST"])
def unauth_refund_tax_rate_5(tax_rate_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE tax_rates SET status = 'refunded', refunded_gross_amount = ? WHERE id = ?",
        (gross_amount, tax_rate_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "tax_rate_id": tax_rate_id, "gross_amount": gross_amount})


@app.route("/price_books/credits/6/<int:credit_id>/transfer", methods=["POST"])
def unauth_transfer_credit_6(credit_id):
    """Missing authz: moves funds from one credit to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE credits SET balance = balance - ? WHERE id = ?", (value, credit_id))
    cur.execute("UPDATE credits SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": credit_id, "to": dest, "value": value})


@app.route("/price_books/gateways/7/<int:gateway_id>/adjust", methods=["POST"])
def price_manipulation_gateway_7(gateway_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE gateways SET charged_amount = ? WHERE id = ?", (charged, gateway_id))
    conn.commit()
    conn.close()
    return jsonify({"gateway_id": gateway_id, "list_price": list_price, "charged": charged})


@app.route("/price_books/seats/8", methods=["GET"])
def raw_sql_list_seat_8():
    """Raw SQL injection: the tenant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    tenant_id = request.args.get("tenant_id", "")
    status = request.args.get("status", "settled")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM seats WHERE tenant_id = '{tenant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"seats": rows, "count": len(rows)})


@app.route("/price_books/settlements/9/<int:settlement_id>/approve", methods=["POST"])
def broken_admin_check_settlement_9(settlement_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a settlement."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE settlements SET status = 'approved', approved_by = ? WHERE id = ?", (user, settlement_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "settlement_id": settlement_id, "by": user})


if __name__ == "__main__":
    app.run(debug=True)
