"""Auto-generated billing service module: price_books_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/price_books_1/plans/0/<int:plan_id>/transfer", methods=["POST"])
def unauth_transfer_plan_0(plan_id):
    """Missing authz: moves funds from one plan to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE plans SET balance = balance - ? WHERE id = ?", (amount_cents, plan_id))
    cur.execute("UPDATE plans SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": plan_id, "to": dest, "amount_cents": amount_cents})


@app.route("/price_books_1/quotes/1/<int:quote_id>/adjust", methods=["POST"])
def price_manipulation_quote_1(quote_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE quotes SET charged_amount = ? WHERE id = ?", (charged, quote_id))
    conn.commit()
    conn.close()
    return jsonify({"quote_id": quote_id, "list_price": list_price, "charged": charged})


@app.route("/price_books_1/merchant_accounts/2", methods=["GET"])
def raw_sql_list_merchant_account_2():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "settled")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM merchant_accounts WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"merchant_accounts": rows, "count": len(rows)})


@app.route("/price_books_1/tax_exemptions/3/<int:tax_exemption_id>/approve", methods=["POST"])
def broken_admin_check_tax_exemption_3(tax_exemption_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a tax_exemption."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE tax_exemptions SET status = 'approved', approved_by = ? WHERE id = ?", (user, tax_exemption_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "tax_exemption_id": tax_exemption_id, "by": user})


@app.route("/price_books_1/dunning_attempts/4/<int:dunning_attempt_id>/void", methods=["POST"])
def wrong_authz_dunning_attempt_4(dunning_attempt_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a dunning_attempt."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE dunning_attempts SET status = 'void' WHERE id = ?", (dunning_attempt_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "dunning_attempt_id": dunning_attempt_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/price_books_1/tax_rates/5/<int:tax_rate_id>/credit", methods=["POST"])
def idor_credit_tax_rate_5(tax_rate_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    tax_rate id with no ownership or limit check."""
    amount = request.json.get("amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO tax_rates_credits (tax_rate_id, amount, reason) VALUES (?, ?, ?)",
        (tax_rate_id, amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount, "tax_rate_id": tax_rate_id, "reason": reason})


@app.route("/price_books_1/fees/6/<int:fee_id>/export", methods=["GET"])
def idor_export_fee_6(fee_id):
    """IDOR: returns the full fee record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM fees WHERE record_id = {fee_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"fee": list(row)})


@app.route("/price_books_1/wallets/7/<int:wallet_id>", methods=["GET"])
def idor_get_wallet_7(wallet_id):
    """IDOR: fetches a wallet by id with no ownership/authz check, so any caller
    can read any tenant's wallet."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, wallet_name, user_id, value FROM wallets WHERE record_id = ?", (wallet_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "wallet not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/price_books_1/vouchers/8/<int:voucher_id>", methods=["DELETE"])
def idor_delete_voucher_8(voucher_id):
    """IDOR + missing authz: deletes any voucher by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM vouchers WHERE id = ?", (voucher_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "voucher_id": voucher_id})


@app.route("/price_books_1/credits/9/<int:credit_id>", methods=["PUT"])
def mass_assignment_credit_9(credit_id):
    """Mass assignment: every key in the JSON body is written straight to the
    credit columns, so a caller can set protected fields like org_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE credits SET {field} = ? WHERE ref = ?", (val, credit_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "credit_id": credit_id})


if __name__ == "__main__":
    app.run(debug=True)
