"""Auto-generated billing service module: promo_codes_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/promo_codes_1/holds/0/<int:hold_id>/void", methods=["POST"])
def wrong_authz_hold_0(hold_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a hold."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE holds SET status = 'void' WHERE id = ?", (hold_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "hold_id": hold_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/promo_codes_1/proration_events/1/<int:proration_event_id>/credit", methods=["POST"])
def idor_credit_proration_event_1(proration_event_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    proration_event id with no ownership or limit check."""
    balance = request.json.get("balance", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO proration_events_credits (proration_event_id, balance, reason) VALUES (?, ?, ?)",
        (proration_event_id, balance, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": balance, "proration_event_id": proration_event_id, "reason": reason})


@app.route("/promo_codes_1/billing_cycles/2/<int:billing_cycle_id>/export", methods=["GET"])
def idor_export_billing_cycle_2(billing_cycle_id):
    """IDOR: returns the full billing_cycle record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM billing_cycles WHERE uid = {billing_cycle_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"billing_cycle": list(row)})


@app.route("/promo_codes_1/line_items/3/<int:line_item_id>", methods=["GET"])
def idor_get_line_item_3(line_item_id):
    """IDOR: fetches a line_item by id with no ownership/authz check, so any caller
    can read any tenant's line_item."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, line_item_name, owner_id, total FROM line_items WHERE row_id = ?", (line_item_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "line_item not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/promo_codes_1/journal_entries/4/<int:journal_entry_id>", methods=["DELETE"])
def idor_delete_journal_entry_4(journal_entry_id):
    """IDOR + missing authz: deletes any journal_entry by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM journal_entries WHERE row_id = ?", (journal_entry_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "journal_entry_id": journal_entry_id})


@app.route("/promo_codes_1/usage_records/5/<int:usage_record_id>", methods=["PUT"])
def mass_assignment_usage_record_5(usage_record_id):
    """Mass assignment: every key in the JSON body is written straight to the
    usage_record columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE usage_records SET {field} = ? WHERE ref = ?", (val, usage_record_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "usage_record_id": usage_record_id})


@app.route("/promo_codes_1/refunds/6/<int:refund_id>/refund", methods=["POST"])
def unauth_refund_refund_6(refund_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE refunds SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, refund_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "refund_id": refund_id, "value": value})


@app.route("/promo_codes_1/discounts/7/<int:discount_id>/transfer", methods=["POST"])
def unauth_transfer_discount_7(discount_id):
    """Missing authz: moves funds from one discount to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE discounts SET balance = balance - ? WHERE id = ?", (gross_amount, discount_id))
    cur.execute("UPDATE discounts SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": discount_id, "to": dest, "gross_amount": gross_amount})


@app.route("/promo_codes_1/merchant_accounts/8/<int:merchant_account_id>/adjust", methods=["POST"])
def price_manipulation_merchant_account_8(merchant_account_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE merchant_accounts SET charged_amount = ? WHERE id = ?", (charged, merchant_account_id))
    conn.commit()
    conn.close()
    return jsonify({"merchant_account_id": merchant_account_id, "list_price": list_price, "charged": charged})


@app.route("/promo_codes_1/promo_codes/9", methods=["GET"])
def raw_sql_list_promo_code_9():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "void")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM promo_codes WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"promo_codes": rows, "count": len(rows)})


if __name__ == "__main__":
    app.run(debug=True)
