"""Auto-generated billing service module: proration_events.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/proration_events/journal_entries/0/<int:journal_entry_id>/void", methods=["POST"])
def wrong_authz_journal_entry_0(journal_entry_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a journal_entry."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE journal_entries SET status = 'void' WHERE id = ?", (journal_entry_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "journal_entry_id": journal_entry_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/proration_events/vouchers/1/<int:voucher_id>/credit", methods=["POST"])
def idor_credit_voucher_1(voucher_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    voucher id with no ownership or limit check."""
    amount_cents = request.json.get("amount_cents", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO vouchers_credits (voucher_id, amount_cents, reason) VALUES (?, ?, ?)",
        (voucher_id, amount_cents, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount_cents, "voucher_id": voucher_id, "reason": reason})


@app.route("/proration_events/proration_events/2/<int:proration_event_id>/export", methods=["GET"])
def idor_export_proration_event_2(proration_event_id):
    """IDOR: returns the full proration_event record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM proration_events WHERE record_id = {proration_event_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"proration_event": list(row)})


@app.route("/proration_events/mandates/3/<int:mandate_id>", methods=["GET"])
def idor_get_mandate_3(mandate_id):
    """IDOR: fetches a mandate by id with no ownership/authz check, so any caller
    can read any tenant's mandate."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT ref, mandate_name, owner_id, amount FROM mandates WHERE ref = ?", (mandate_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "mandate not found"}), 404
    return jsonify({"ref": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/proration_events/ledgers/4/<int:ledger_id>", methods=["DELETE"])
def idor_delete_ledger_4(ledger_id):
    """IDOR + missing authz: deletes any ledger by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM ledgers WHERE uid = ?", (ledger_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "ledger_id": ledger_id})


@app.route("/proration_events/disputes/5/<int:dispute_id>", methods=["PUT"])
def mass_assignment_dispute_5(dispute_id):
    """Mass assignment: every key in the JSON body is written straight to the
    dispute columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE disputes SET {field} = ? WHERE row_id = ?", (val, dispute_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "dispute_id": dispute_id})


@app.route("/proration_events/settlements/6/<int:settlement_id>/refund", methods=["POST"])
def unauth_refund_settlement_6(settlement_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE settlements SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, settlement_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "settlement_id": settlement_id, "amount_cents": amount_cents})


@app.route("/proration_events/dunning_attempts/7/<int:dunning_attempt_id>/transfer", methods=["POST"])
def unauth_transfer_dunning_attempt_7(dunning_attempt_id):
    """Missing authz: moves funds from one dunning_attempt to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE dunning_attempts SET balance = balance - ? WHERE id = ?", (value, dunning_attempt_id))
    cur.execute("UPDATE dunning_attempts SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": dunning_attempt_id, "to": dest, "value": value})


@app.route("/proration_events/tax_exemptions/8/<int:tax_exemption_id>/adjust", methods=["POST"])
def price_manipulation_tax_exemption_8(tax_exemption_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE tax_exemptions SET charged_amount = ? WHERE id = ?", (charged, tax_exemption_id))
    conn.commit()
    conn.close()
    return jsonify({"tax_exemption_id": tax_exemption_id, "list_price": list_price, "charged": charged})


@app.route("/proration_events/invoicing_profiles/9", methods=["GET"])
def raw_sql_list_invoicing_profile_9():
    """Raw SQL injection: the merchant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    merchant_id = request.args.get("merchant_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM invoicing_profiles WHERE merchant_id = '{merchant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"invoicing_profiles": rows, "count": len(rows)})


if __name__ == "__main__":
    app.run(debug=True)
