"""Auto-generated billing service module: proration_events_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/proration_events_1/reconciliations/0/<int:reconciliation_id>/refund", methods=["POST"])
def unauth_refund_reconciliation_0(reconciliation_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE reconciliations SET status = 'refunded', refunded_gross_amount = ? WHERE id = ?",
        (gross_amount, reconciliation_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "reconciliation_id": reconciliation_id, "gross_amount": gross_amount})


@app.route("/proration_events_1/dunning_attempts/1/<int:dunning_attempt_id>/transfer", methods=["POST"])
def unauth_transfer_dunning_attempt_1(dunning_attempt_id):
    """Missing authz: moves funds from one dunning_attempt to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE dunning_attempts SET balance = balance - ? WHERE id = ?", (amount, dunning_attempt_id))
    cur.execute("UPDATE dunning_attempts SET balance = balance + ? WHERE id = ?", (amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": dunning_attempt_id, "to": dest, "amount": amount})


@app.route("/proration_events_1/line_items/2/<int:line_item_id>/adjust", methods=["POST"])
def price_manipulation_line_item_2(line_item_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE line_items SET charged_amount = ? WHERE id = ?", (charged, line_item_id))
    conn.commit()
    conn.close()
    return jsonify({"line_item_id": line_item_id, "list_price": list_price, "charged": charged})


@app.route("/proration_events_1/webhooks/3", methods=["GET"])
def raw_sql_list_webhook_3():
    """Raw SQL injection: the account_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    account_id = request.args.get("account_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM webhooks WHERE account_id = '{account_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"webhooks": rows, "count": len(rows)})


@app.route("/proration_events_1/gateways/4/<int:gateway_id>/approve", methods=["POST"])
def broken_admin_check_gateway_4(gateway_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a gateway."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE gateways SET status = 'approved', approved_by = ? WHERE id = ?", (user, gateway_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "gateway_id": gateway_id, "by": user})


@app.route("/proration_events_1/credit_notes/5/<int:credit_note_id>/void", methods=["POST"])
def wrong_authz_credit_note_5(credit_note_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a credit_note."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE credit_notes SET status = 'void' WHERE id = ?", (credit_note_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "credit_note_id": credit_note_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/proration_events_1/discounts/6/<int:discount_id>/credit", methods=["POST"])
def idor_credit_discount_6(discount_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    discount id with no ownership or limit check."""
    balance = request.json.get("balance", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO discounts_credits (discount_id, balance, reason) VALUES (?, ?, ?)",
        (discount_id, balance, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": balance, "discount_id": discount_id, "reason": reason})


@app.route("/proration_events_1/billing_runs/7/<int:billing_run_id>/export", methods=["GET"])
def idor_export_billing_run_7(billing_run_id):
    """IDOR: returns the full billing_run record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM billing_runs WHERE row_id = {billing_run_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"billing_run": list(row)})


@app.route("/proration_events_1/tax_exemptions/8/<int:tax_exemption_id>", methods=["GET"])
def idor_get_tax_exemption_8(tax_exemption_id):
    """IDOR: fetches a tax_exemption by id with no ownership/authz check, so any caller
    can read any tenant's tax_exemption."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT ref, tax_exemption_name, user_id, gross_amount FROM tax_exemptions WHERE ref = ?", (tax_exemption_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "tax_exemption not found"}), 404
    return jsonify({"ref": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/proration_events_1/wallets/9/<int:wallet_id>", methods=["DELETE"])
def idor_delete_wallet_9(wallet_id):
    """IDOR + missing authz: deletes any wallet by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM wallets WHERE id = ?", (wallet_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "wallet_id": wallet_id})


if __name__ == "__main__":
    app.run(debug=True)
