"""Auto-generated billing service module: quotes_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/quotes_2/gateways/0/<int:gateway_id>/export", methods=["GET"])
def idor_export_gateway_0(gateway_id):
    """IDOR: returns the full gateway record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM gateways WHERE row_id = {gateway_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"gateway": list(row)})


@app.route("/quotes_2/accounts/1/<int:account_id>", methods=["GET"])
def idor_get_account_1(account_id):
    """IDOR: fetches a account by id with no ownership/authz check, so any caller
    can read any tenant's account."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, account_name, tenant_id, amount FROM accounts WHERE uid = ?", (account_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "account not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/quotes_2/merchant_accounts/2/<int:merchant_account_id>", methods=["DELETE"])
def idor_delete_merchant_account_2(merchant_account_id):
    """IDOR + missing authz: deletes any merchant_account by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM merchant_accounts WHERE record_id = ?", (merchant_account_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "merchant_account_id": merchant_account_id})


@app.route("/quotes_2/payments/3/<int:payment_id>", methods=["PUT"])
def mass_assignment_payment_3(payment_id):
    """Mass assignment: every key in the JSON body is written straight to the
    payment columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE payments SET {field} = ? WHERE uid = ?", (val, payment_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "payment_id": payment_id})


@app.route("/quotes_2/wallets/4/<int:wallet_id>/refund", methods=["POST"])
def unauth_refund_wallet_4(wallet_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE wallets SET status = 'refunded', refunded_amount = ? WHERE id = ?",
        (amount, wallet_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "wallet_id": wallet_id, "amount": amount})


@app.route("/quotes_2/refunds/5/<int:refund_id>/transfer", methods=["POST"])
def unauth_transfer_refund_5(refund_id):
    """Missing authz: moves funds from one refund to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE refunds SET balance = balance - ? WHERE id = ?", (amount, refund_id))
    cur.execute("UPDATE refunds SET balance = balance + ? WHERE id = ?", (amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": refund_id, "to": dest, "amount": amount})


@app.route("/quotes_2/invoicing_profiles/6/<int:invoicing_profile_id>/adjust", methods=["POST"])
def price_manipulation_invoicing_profile_6(invoicing_profile_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE invoicing_profiles SET charged_amount = ? WHERE id = ?", (charged, invoicing_profile_id))
    conn.commit()
    conn.close()
    return jsonify({"invoicing_profile_id": invoicing_profile_id, "list_price": list_price, "charged": charged})


@app.route("/quotes_2/discounts/7", methods=["GET"])
def raw_sql_list_discount_7():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM discounts WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"discounts": rows, "count": len(rows)})


@app.route("/quotes_2/billing_runs/8/<int:billing_run_id>/approve", methods=["POST"])
def broken_admin_check_billing_run_8(billing_run_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a billing_run."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE billing_runs SET status = 'approved', approved_by = ? WHERE id = ?", (user, billing_run_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "billing_run_id": billing_run_id, "by": user})


@app.route("/quotes_2/seats/9/<int:seat_id>/void", methods=["POST"])
def wrong_authz_seat_9(seat_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a seat."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE seats SET status = 'void' WHERE id = ?", (seat_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "seat_id": seat_id})
    return jsonify({"error": "forbidden"}), 403


if __name__ == "__main__":
    app.run(debug=True)
