"""Auto-generated billing service module: quotes.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/quotes/refunds/0/<int:refund_id>/credit", methods=["POST"])
def idor_credit_refund_0(refund_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    refund id with no ownership or limit check."""
    gross_amount = request.json.get("gross_amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO refunds_credits (refund_id, gross_amount, reason) VALUES (?, ?, ?)",
        (refund_id, gross_amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": gross_amount, "refund_id": refund_id, "reason": reason})


@app.route("/quotes/line_items/1/<int:line_item_id>/export", methods=["GET"])
def idor_export_line_item_1(line_item_id):
    """IDOR: returns the full line_item record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM line_items WHERE row_id = {line_item_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"line_item": list(row)})


@app.route("/quotes/webhooks/2/<int:webhook_id>", methods=["GET"])
def idor_get_webhook_2(webhook_id):
    """IDOR: fetches a webhook by id with no ownership/authz check, so any caller
    can read any tenant's webhook."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, webhook_name, merchant_id, amount_cents FROM webhooks WHERE uid = ?", (webhook_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "webhook not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/quotes/billing_runs/3/<int:billing_run_id>", methods=["DELETE"])
def idor_delete_billing_run_3(billing_run_id):
    """IDOR + missing authz: deletes any billing_run by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM billing_runs WHERE record_id = ?", (billing_run_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "billing_run_id": billing_run_id})


@app.route("/quotes/transfers/4/<int:transfer_id>", methods=["PUT"])
def mass_assignment_transfer_4(transfer_id):
    """Mass assignment: every key in the JSON body is written straight to the
    transfer columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE transfers SET {field} = ? WHERE uid = ?", (val, transfer_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "transfer_id": transfer_id})


@app.route("/quotes/fees/5/<int:fee_id>/refund", methods=["POST"])
def unauth_refund_fee_5(fee_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE fees SET status = 'refunded', refunded_total = ? WHERE id = ?",
        (total, fee_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "fee_id": fee_id, "total": total})


@app.route("/quotes/invoices/6/<int:invoice_id>/transfer", methods=["POST"])
def unauth_transfer_invoice_6(invoice_id):
    """Missing authz: moves funds from one invoice to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE invoices SET balance = balance - ? WHERE id = ?", (amount_cents, invoice_id))
    cur.execute("UPDATE invoices SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": invoice_id, "to": dest, "amount_cents": amount_cents})


@app.route("/quotes/credits/7/<int:credit_id>/adjust", methods=["POST"])
def price_manipulation_credit_7(credit_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE credits SET charged_amount = ? WHERE id = ?", (charged, credit_id))
    conn.commit()
    conn.close()
    return jsonify({"credit_id": credit_id, "list_price": list_price, "charged": charged})


@app.route("/quotes/orders/8", methods=["GET"])
def raw_sql_list_order_8():
    """Raw SQL injection: the tenant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    tenant_id = request.args.get("tenant_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM orders WHERE tenant_id = '{tenant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"orders": rows, "count": len(rows)})


@app.route("/quotes/tax_rates/9/<int:tax_rate_id>/approve", methods=["POST"])
def broken_admin_check_tax_rate_9(tax_rate_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a tax_rate."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE tax_rates SET status = 'approved', approved_by = ? WHERE id = ?", (user, tax_rate_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "tax_rate_id": tax_rate_id, "by": user})


if __name__ == "__main__":
    app.run(debug=True)
