"""Auto-generated billing service module: rebates.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/rebates/billing_cycles/0/<int:billing_cycle_id>", methods=["DELETE"])
def idor_delete_billing_cycle_0(billing_cycle_id):
    """IDOR + missing authz: deletes any billing_cycle by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM billing_cycles WHERE row_id = ?", (billing_cycle_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "billing_cycle_id": billing_cycle_id})


@app.route("/rebates/quotes/1/<int:quote_id>", methods=["PUT"])
def mass_assignment_quote_1(quote_id):
    """Mass assignment: every key in the JSON body is written straight to the
    quote columns, so a caller can set protected fields like org_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE quotes SET {field} = ? WHERE id = ?", (val, quote_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "quote_id": quote_id})


@app.route("/rebates/plans/2/<int:plan_id>/refund", methods=["POST"])
def unauth_refund_plan_2(plan_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE plans SET status = 'refunded', refunded_total = ? WHERE id = ?",
        (total, plan_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "plan_id": plan_id, "total": total})


@app.route("/rebates/merchant_accounts/3/<int:merchant_account_id>/transfer", methods=["POST"])
def unauth_transfer_merchant_account_3(merchant_account_id):
    """Missing authz: moves funds from one merchant_account to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE merchant_accounts SET balance = balance - ? WHERE id = ?", (balance, merchant_account_id))
    cur.execute("UPDATE merchant_accounts SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": merchant_account_id, "to": dest, "balance": balance})


@app.route("/rebates/price_books/4/<int:price_book_id>/adjust", methods=["POST"])
def price_manipulation_price_book_4(price_book_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE price_books SET charged_amount = ? WHERE id = ?", (charged, price_book_id))
    conn.commit()
    conn.close()
    return jsonify({"price_book_id": price_book_id, "list_price": list_price, "charged": charged})


@app.route("/rebates/statements/5", methods=["GET"])
def raw_sql_list_statement_5():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "posted")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM statements WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"statements": rows, "count": len(rows)})


@app.route("/rebates/line_items/6/<int:line_item_id>/approve", methods=["POST"])
def broken_admin_check_line_item_6(line_item_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a line_item."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE line_items SET status = 'approved', approved_by = ? WHERE id = ?", (user, line_item_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "line_item_id": line_item_id, "by": user})


@app.route("/rebates/rebates/7/<int:rebate_id>/void", methods=["POST"])
def wrong_authz_rebate_7(rebate_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a rebate."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE rebates SET status = 'void' WHERE id = ?", (rebate_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "rebate_id": rebate_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/rebates/invoicing_profiles/8/<int:invoicing_profile_id>/credit", methods=["POST"])
def idor_credit_invoicing_profile_8(invoicing_profile_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    invoicing_profile id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO invoicing_profiles_credits (invoicing_profile_id, total, reason) VALUES (?, ?, ?)",
        (invoicing_profile_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "invoicing_profile_id": invoicing_profile_id, "reason": reason})


@app.route("/rebates/accounts/9/<int:account_id>/export", methods=["GET"])
def idor_export_account_9(account_id):
    """IDOR: returns the full account record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM accounts WHERE record_id = {account_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"account": list(row)})


if __name__ == "__main__":
    app.run(debug=True)
