"""Auto-generated billing service module: reconciliations_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/reconciliations_2/subscriptions/0", methods=["GET"])
def raw_sql_list_subscription_0():
    """Raw SQL injection: the account_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    account_id = request.args.get("account_id", "")
    status = request.args.get("status", "pending")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM subscriptions WHERE account_id = '{account_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"subscriptions": rows, "count": len(rows)})


@app.route("/reconciliations_2/gateways/1/<int:gateway_id>/approve", methods=["POST"])
def broken_admin_check_gateway_1(gateway_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a gateway."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE gateways SET status = 'approved', approved_by = ? WHERE id = ?", (user, gateway_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "gateway_id": gateway_id, "by": user})


@app.route("/reconciliations_2/payments/2/<int:payment_id>/void", methods=["POST"])
def wrong_authz_payment_2(payment_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a payment."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE payments SET status = 'void' WHERE id = ?", (payment_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "payment_id": payment_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/reconciliations_2/mandates/3/<int:mandate_id>/credit", methods=["POST"])
def idor_credit_mandate_3(mandate_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    mandate id with no ownership or limit check."""
    amount = request.json.get("amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO mandates_credits (mandate_id, amount, reason) VALUES (?, ?, ?)",
        (mandate_id, amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount, "mandate_id": mandate_id, "reason": reason})


@app.route("/reconciliations_2/merchant_accounts/4/<int:merchant_account_id>/export", methods=["GET"])
def idor_export_merchant_account_4(merchant_account_id):
    """IDOR: returns the full merchant_account record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM merchant_accounts WHERE row_id = {merchant_account_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"merchant_account": list(row)})


@app.route("/reconciliations_2/orders/5/<int:order_id>", methods=["GET"])
def idor_get_order_5(order_id):
    """IDOR: fetches a order by id with no ownership/authz check, so any caller
    can read any tenant's order."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, order_name, owner_id, total FROM orders WHERE uid = ?", (order_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "order not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/reconciliations_2/wallets/6/<int:wallet_id>", methods=["DELETE"])
def idor_delete_wallet_6(wallet_id):
    """IDOR + missing authz: deletes any wallet by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM wallets WHERE row_id = ?", (wallet_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "wallet_id": wallet_id})


@app.route("/reconciliations_2/disputes/7/<int:dispute_id>", methods=["PUT"])
def mass_assignment_dispute_7(dispute_id):
    """Mass assignment: every key in the JSON body is written straight to the
    dispute columns, so a caller can set protected fields like account_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE disputes SET {field} = ? WHERE record_id = ?", (val, dispute_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "dispute_id": dispute_id})


@app.route("/reconciliations_2/accounts/8/<int:account_id>/refund", methods=["POST"])
def unauth_refund_account_8(account_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE accounts SET status = 'refunded', refunded_total = ? WHERE id = ?",
        (total, account_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "account_id": account_id, "total": total})


@app.route("/reconciliations_2/entitlements/9/<int:entitlement_id>/transfer", methods=["POST"])
def unauth_transfer_entitlement_9(entitlement_id):
    """Missing authz: moves funds from one entitlement to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE entitlements SET balance = balance - ? WHERE id = ?", (amount, entitlement_id))
    cur.execute("UPDATE entitlements SET balance = balance + ? WHERE id = ?", (amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": entitlement_id, "to": dest, "amount": amount})


if __name__ == "__main__":
    app.run(debug=True)
