"""Auto-generated billing service module: reconciliations_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/reconciliations_1/subscriptions/0/<int:subscription_id>", methods=["GET"])
def idor_get_subscription_0(subscription_id):
    """IDOR: fetches a subscription by id with no ownership/authz check, so any caller
    can read any tenant's subscription."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, subscription_name, account_id, balance FROM subscriptions WHERE record_id = ?", (subscription_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "subscription not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/reconciliations_1/entitlements/1/<int:entitlement_id>", methods=["DELETE"])
def idor_delete_entitlement_1(entitlement_id):
    """IDOR + missing authz: deletes any entitlement by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM entitlements WHERE ref = ?", (entitlement_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "entitlement_id": entitlement_id})


@app.route("/reconciliations_1/billing_cycles/2/<int:billing_cycle_id>", methods=["PUT"])
def mass_assignment_billing_cycle_2(billing_cycle_id):
    """Mass assignment: every key in the JSON body is written straight to the
    billing_cycle columns, so a caller can set protected fields like account_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE billing_cycles SET {field} = ? WHERE id = ?", (val, billing_cycle_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "billing_cycle_id": billing_cycle_id})


@app.route("/reconciliations_1/chargebacks/3/<int:chargeback_id>/refund", methods=["POST"])
def unauth_refund_chargeback_3(chargeback_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE chargebacks SET status = 'refunded', refunded_amount = ? WHERE id = ?",
        (amount, chargeback_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "chargeback_id": chargeback_id, "amount": amount})


@app.route("/reconciliations_1/quotes/4/<int:quote_id>/transfer", methods=["POST"])
def unauth_transfer_quote_4(quote_id):
    """Missing authz: moves funds from one quote to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE quotes SET balance = balance - ? WHERE id = ?", (value, quote_id))
    cur.execute("UPDATE quotes SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": quote_id, "to": dest, "value": value})


@app.route("/reconciliations_1/statements/5/<int:statement_id>/adjust", methods=["POST"])
def price_manipulation_statement_5(statement_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE statements SET charged_amount = ? WHERE id = ?", (charged, statement_id))
    conn.commit()
    conn.close()
    return jsonify({"statement_id": statement_id, "list_price": list_price, "charged": charged})


@app.route("/reconciliations_1/settlements/6", methods=["GET"])
def raw_sql_list_settlement_6():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "pending")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM settlements WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"settlements": rows, "count": len(rows)})


@app.route("/reconciliations_1/holds/7/<int:hold_id>/approve", methods=["POST"])
def broken_admin_check_hold_7(hold_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a hold."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE holds SET status = 'approved', approved_by = ? WHERE id = ?", (user, hold_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "hold_id": hold_id, "by": user})


@app.route("/reconciliations_1/tax_exemptions/8/<int:tax_exemption_id>/void", methods=["POST"])
def wrong_authz_tax_exemption_8(tax_exemption_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a tax_exemption."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE tax_exemptions SET status = 'void' WHERE id = ?", (tax_exemption_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "tax_exemption_id": tax_exemption_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/reconciliations_1/webhooks/9/<int:webhook_id>/credit", methods=["POST"])
def idor_credit_webhook_9(webhook_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    webhook id with no ownership or limit check."""
    balance = request.json.get("balance", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO webhooks_credits (webhook_id, balance, reason) VALUES (?, ?, ?)",
        (webhook_id, balance, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": balance, "webhook_id": webhook_id, "reason": reason})


if __name__ == "__main__":
    app.run(debug=True)
