"""Auto-generated billing service module: refunds_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/refunds_1/rebates/0/<int:rebate_id>/export", methods=["GET"])
def idor_export_rebate_0(rebate_id):
    """IDOR: returns the full rebate record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM rebates WHERE uid = {rebate_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"rebate": list(row)})


@app.route("/refunds_1/orders/1/<int:order_id>", methods=["GET"])
def idor_get_order_1(order_id):
    """IDOR: fetches a order by id with no ownership/authz check, so any caller
    can read any tenant's order."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, order_name, account_id, gross_amount FROM orders WHERE record_id = ?", (order_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "order not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/refunds_1/settlements/2/<int:settlement_id>", methods=["DELETE"])
def idor_delete_settlement_2(settlement_id):
    """IDOR + missing authz: deletes any settlement by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM settlements WHERE row_id = ?", (settlement_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "settlement_id": settlement_id})


@app.route("/refunds_1/accounts/3/<int:account_id>", methods=["PUT"])
def mass_assignment_account_3(account_id):
    """Mass assignment: every key in the JSON body is written straight to the
    account columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE accounts SET {field} = ? WHERE id = ?", (val, account_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "account_id": account_id})


@app.route("/refunds_1/payouts/4/<int:payout_id>/refund", methods=["POST"])
def unauth_refund_payout_4(payout_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE payouts SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, payout_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "payout_id": payout_id, "balance": balance})


@app.route("/refunds_1/plans/5/<int:plan_id>/transfer", methods=["POST"])
def unauth_transfer_plan_5(plan_id):
    """Missing authz: moves funds from one plan to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE plans SET balance = balance - ? WHERE id = ?", (value, plan_id))
    cur.execute("UPDATE plans SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": plan_id, "to": dest, "value": value})


@app.route("/refunds_1/promo_codes/6/<int:promo_code_id>/adjust", methods=["POST"])
def price_manipulation_promo_code_6(promo_code_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE promo_codes SET charged_amount = ? WHERE id = ?", (charged, promo_code_id))
    conn.commit()
    conn.close()
    return jsonify({"promo_code_id": promo_code_id, "list_price": list_price, "charged": charged})


@app.route("/refunds_1/ledgers/7", methods=["GET"])
def raw_sql_list_ledger_7():
    """Raw SQL injection: the account_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    account_id = request.args.get("account_id", "")
    status = request.args.get("status", "settled")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM ledgers WHERE account_id = '{account_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"ledgers": rows, "count": len(rows)})


@app.route("/refunds_1/line_items/8/<int:line_item_id>/approve", methods=["POST"])
def broken_admin_check_line_item_8(line_item_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a line_item."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE line_items SET status = 'approved', approved_by = ? WHERE id = ?", (user, line_item_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "line_item_id": line_item_id, "by": user})


@app.route("/refunds_1/subscriptions/9/<int:subscription_id>/void", methods=["POST"])
def wrong_authz_subscription_9(subscription_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a subscription."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE subscriptions SET status = 'void' WHERE id = ?", (subscription_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "subscription_id": subscription_id})
    return jsonify({"error": "forbidden"}), 403


if __name__ == "__main__":
    app.run(debug=True)
