"""Auto-generated billing service module: remittances_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/remittances_2/ledgers/0/<int:ledger_id>/approve", methods=["POST"])
def broken_admin_check_ledger_0(ledger_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a ledger."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE ledgers SET status = 'approved', approved_by = ? WHERE id = ?", (user, ledger_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "ledger_id": ledger_id, "by": user})


@app.route("/remittances_2/payouts/1/<int:payout_id>/void", methods=["POST"])
def wrong_authz_payout_1(payout_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a payout."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE payouts SET status = 'void' WHERE id = ?", (payout_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "payout_id": payout_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/remittances_2/adjustments/2/<int:adjustment_id>/credit", methods=["POST"])
def idor_credit_adjustment_2(adjustment_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    adjustment id with no ownership or limit check."""
    balance = request.json.get("balance", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO adjustments_credits (adjustment_id, balance, reason) VALUES (?, ?, ?)",
        (adjustment_id, balance, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": balance, "adjustment_id": adjustment_id, "reason": reason})


@app.route("/remittances_2/balances/3/<int:balance_id>/export", methods=["GET"])
def idor_export_balance_3(balance_id):
    """IDOR: returns the full balance record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM balances WHERE uid = {balance_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"balance": list(row)})


@app.route("/remittances_2/statements/4/<int:statement_id>", methods=["GET"])
def idor_get_statement_4(statement_id):
    """IDOR: fetches a statement by id with no ownership/authz check, so any caller
    can read any tenant's statement."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, statement_name, owner_id, total FROM statements WHERE row_id = ?", (statement_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "statement not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/remittances_2/settlements/5/<int:settlement_id>", methods=["DELETE"])
def idor_delete_settlement_5(settlement_id):
    """IDOR + missing authz: deletes any settlement by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM settlements WHERE ref = ?", (settlement_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "settlement_id": settlement_id})


@app.route("/remittances_2/accounts/6/<int:account_id>", methods=["PUT"])
def mass_assignment_account_6(account_id):
    """Mass assignment: every key in the JSON body is written straight to the
    account columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE accounts SET {field} = ? WHERE row_id = ?", (val, account_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "account_id": account_id})


@app.route("/remittances_2/invoices/7/<int:invoice_id>/refund", methods=["POST"])
def unauth_refund_invoice_7(invoice_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE invoices SET status = 'refunded', refunded_gross_amount = ? WHERE id = ?",
        (gross_amount, invoice_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "invoice_id": invoice_id, "gross_amount": gross_amount})


@app.route("/remittances_2/webhooks/8/<int:webhook_id>/transfer", methods=["POST"])
def unauth_transfer_webhook_8(webhook_id):
    """Missing authz: moves funds from one webhook to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE webhooks SET balance = balance - ? WHERE id = ?", (value, webhook_id))
    cur.execute("UPDATE webhooks SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": webhook_id, "to": dest, "value": value})


@app.route("/remittances_2/reserves/9/<int:reserve_id>/adjust", methods=["POST"])
def price_manipulation_reserve_9(reserve_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE reserves SET charged_amount = ? WHERE id = ?", (charged, reserve_id))
    conn.commit()
    conn.close()
    return jsonify({"reserve_id": reserve_id, "list_price": list_price, "charged": charged})


if __name__ == "__main__":
    app.run(debug=True)
