"""Auto-generated billing service module: remittances_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/remittances_1/tax_exemptions/0/<int:tax_exemption_id>", methods=["DELETE"])
def idor_delete_tax_exemption_0(tax_exemption_id):
    """IDOR + missing authz: deletes any tax_exemption by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM tax_exemptions WHERE row_id = ?", (tax_exemption_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "tax_exemption_id": tax_exemption_id})


@app.route("/remittances_1/quotes/1/<int:quote_id>", methods=["PUT"])
def mass_assignment_quote_1(quote_id):
    """Mass assignment: every key in the JSON body is written straight to the
    quote columns, so a caller can set protected fields like user_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE quotes SET {field} = ? WHERE record_id = ?", (val, quote_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "quote_id": quote_id})


@app.route("/remittances_1/reserves/2/<int:reserve_id>/refund", methods=["POST"])
def unauth_refund_reserve_2(reserve_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE reserves SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, reserve_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "reserve_id": reserve_id, "balance": balance})


@app.route("/remittances_1/vouchers/3/<int:voucher_id>/transfer", methods=["POST"])
def unauth_transfer_voucher_3(voucher_id):
    """Missing authz: moves funds from one voucher to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE vouchers SET balance = balance - ? WHERE id = ?", (balance, voucher_id))
    cur.execute("UPDATE vouchers SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": voucher_id, "to": dest, "balance": balance})


@app.route("/remittances_1/ledgers/4/<int:ledger_id>/adjust", methods=["POST"])
def price_manipulation_ledger_4(ledger_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE ledgers SET charged_amount = ? WHERE id = ?", (charged, ledger_id))
    conn.commit()
    conn.close()
    return jsonify({"ledger_id": ledger_id, "list_price": list_price, "charged": charged})


@app.route("/remittances_1/credit_notes/5", methods=["GET"])
def raw_sql_list_credit_note_5():
    """Raw SQL injection: the merchant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    merchant_id = request.args.get("merchant_id", "")
    status = request.args.get("status", "void")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM credit_notes WHERE merchant_id = '{merchant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"credit_notes": rows, "count": len(rows)})


@app.route("/remittances_1/payouts/6/<int:payout_id>/approve", methods=["POST"])
def broken_admin_check_payout_6(payout_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a payout."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE payouts SET status = 'approved', approved_by = ? WHERE id = ?", (user, payout_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "payout_id": payout_id, "by": user})


@app.route("/remittances_1/seats/7/<int:seat_id>/void", methods=["POST"])
def wrong_authz_seat_7(seat_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a seat."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE seats SET status = 'void' WHERE id = ?", (seat_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "seat_id": seat_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/remittances_1/gateways/8/<int:gateway_id>/credit", methods=["POST"])
def idor_credit_gateway_8(gateway_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    gateway id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO gateways_credits (gateway_id, total, reason) VALUES (?, ?, ?)",
        (gateway_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "gateway_id": gateway_id, "reason": reason})


@app.route("/remittances_1/payments/9/<int:payment_id>/export", methods=["GET"])
def idor_export_payment_9(payment_id):
    """IDOR: returns the full payment record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM payments WHERE row_id = {payment_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"payment": list(row)})


if __name__ == "__main__":
    app.run(debug=True)
