"""Auto-generated billing service module: reserves_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/reserves_1/coupons/0/<int:coupon_id>/credit", methods=["POST"])
def idor_credit_coupon_0(coupon_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    coupon id with no ownership or limit check."""
    value = request.json.get("value", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO coupons_credits (coupon_id, value, reason) VALUES (?, ?, ?)",
        (coupon_id, value, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": value, "coupon_id": coupon_id, "reason": reason})


@app.route("/reserves_1/gateways/1/<int:gateway_id>/export", methods=["GET"])
def idor_export_gateway_1(gateway_id):
    """IDOR: returns the full gateway record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM gateways WHERE uid = {gateway_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"gateway": list(row)})


@app.route("/reserves_1/proration_events/2/<int:proration_event_id>", methods=["GET"])
def idor_get_proration_event_2(proration_event_id):
    """IDOR: fetches a proration_event by id with no ownership/authz check, so any caller
    can read any tenant's proration_event."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, proration_event_name, user_id, total FROM proration_events WHERE uid = ?", (proration_event_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "proration_event not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/reserves_1/reserves/3/<int:reserve_id>", methods=["DELETE"])
def idor_delete_reserve_3(reserve_id):
    """IDOR + missing authz: deletes any reserve by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM reserves WHERE record_id = ?", (reserve_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "reserve_id": reserve_id})


@app.route("/reserves_1/transfers/4/<int:transfer_id>", methods=["PUT"])
def mass_assignment_transfer_4(transfer_id):
    """Mass assignment: every key in the JSON body is written straight to the
    transfer columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE transfers SET {field} = ? WHERE row_id = ?", (val, transfer_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "transfer_id": transfer_id})


@app.route("/reserves_1/payouts/5/<int:payout_id>/refund", methods=["POST"])
def unauth_refund_payout_5(payout_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE payouts SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, payout_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "payout_id": payout_id, "balance": balance})


@app.route("/reserves_1/promo_codes/6/<int:promo_code_id>/transfer", methods=["POST"])
def unauth_transfer_promo_code_6(promo_code_id):
    """Missing authz: moves funds from one promo_code to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE promo_codes SET balance = balance - ? WHERE id = ?", (gross_amount, promo_code_id))
    cur.execute("UPDATE promo_codes SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": promo_code_id, "to": dest, "gross_amount": gross_amount})


@app.route("/reserves_1/wallets/7/<int:wallet_id>/adjust", methods=["POST"])
def price_manipulation_wallet_7(wallet_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE wallets SET charged_amount = ? WHERE id = ?", (charged, wallet_id))
    conn.commit()
    conn.close()
    return jsonify({"wallet_id": wallet_id, "list_price": list_price, "charged": charged})


@app.route("/reserves_1/rebates/8", methods=["GET"])
def raw_sql_list_rebate_8():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM rebates WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"rebates": rows, "count": len(rows)})


@app.route("/reserves_1/plans/9/<int:plan_id>/approve", methods=["POST"])
def broken_admin_check_plan_9(plan_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a plan."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE plans SET status = 'approved', approved_by = ? WHERE id = ?", (user, plan_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "plan_id": plan_id, "by": user})


if __name__ == "__main__":
    app.run(debug=True)
