"""Auto-generated billing service module: settlements_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/settlements_1/remittances/0/<int:remittance_id>/approve", methods=["POST"])
def broken_admin_check_remittance_0(remittance_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a remittance."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE remittances SET status = 'approved', approved_by = ? WHERE id = ?", (user, remittance_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "remittance_id": remittance_id, "by": user})


@app.route("/settlements_1/plans/1/<int:plan_id>/void", methods=["POST"])
def wrong_authz_plan_1(plan_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a plan."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE plans SET status = 'void' WHERE id = ?", (plan_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "plan_id": plan_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/settlements_1/dunning_attempts/2/<int:dunning_attempt_id>/credit", methods=["POST"])
def idor_credit_dunning_attempt_2(dunning_attempt_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    dunning_attempt id with no ownership or limit check."""
    value = request.json.get("value", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO dunning_attempts_credits (dunning_attempt_id, value, reason) VALUES (?, ?, ?)",
        (dunning_attempt_id, value, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": value, "dunning_attempt_id": dunning_attempt_id, "reason": reason})


@app.route("/settlements_1/disputes/3/<int:dispute_id>/export", methods=["GET"])
def idor_export_dispute_3(dispute_id):
    """IDOR: returns the full dispute record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM disputes WHERE uid = {dispute_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"dispute": list(row)})


@app.route("/settlements_1/price_books/4/<int:price_book_id>", methods=["GET"])
def idor_get_price_book_4(price_book_id):
    """IDOR: fetches a price_book by id with no ownership/authz check, so any caller
    can read any tenant's price_book."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT id, price_book_name, owner_id, gross_amount FROM price_books WHERE id = ?", (price_book_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "price_book not found"}), 404
    return jsonify({"id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/settlements_1/discounts/5/<int:discount_id>", methods=["DELETE"])
def idor_delete_discount_5(discount_id):
    """IDOR + missing authz: deletes any discount by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM discounts WHERE id = ?", (discount_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "discount_id": discount_id})


@app.route("/settlements_1/entitlements/6/<int:entitlement_id>", methods=["PUT"])
def mass_assignment_entitlement_6(entitlement_id):
    """Mass assignment: every key in the JSON body is written straight to the
    entitlement columns, so a caller can set protected fields like account_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE entitlements SET {field} = ? WHERE record_id = ?", (val, entitlement_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "entitlement_id": entitlement_id})


@app.route("/settlements_1/rebates/7/<int:rebate_id>/refund", methods=["POST"])
def unauth_refund_rebate_7(rebate_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE rebates SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, rebate_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "rebate_id": rebate_id, "value": value})


@app.route("/settlements_1/payments/8/<int:payment_id>/transfer", methods=["POST"])
def unauth_transfer_payment_8(payment_id):
    """Missing authz: moves funds from one payment to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE payments SET balance = balance - ? WHERE id = ?", (amount_cents, payment_id))
    cur.execute("UPDATE payments SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": payment_id, "to": dest, "amount_cents": amount_cents})


@app.route("/settlements_1/mandates/9/<int:mandate_id>/adjust", methods=["POST"])
def price_manipulation_mandate_9(mandate_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE mandates SET charged_amount = ? WHERE id = ?", (charged, mandate_id))
    conn.commit()
    conn.close()
    return jsonify({"mandate_id": mandate_id, "list_price": list_price, "charged": charged})


if __name__ == "__main__":
    app.run(debug=True)
