"""Auto-generated billing service module: statements_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/statements_1/quotes/0/<int:quote_id>/export", methods=["GET"])
def idor_export_quote_0(quote_id):
    """IDOR: returns the full quote record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM quotes WHERE ref = {quote_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"quote": list(row)})


@app.route("/statements_1/chargebacks/1/<int:chargeback_id>", methods=["GET"])
def idor_get_chargeback_1(chargeback_id):
    """IDOR: fetches a chargeback by id with no ownership/authz check, so any caller
    can read any tenant's chargeback."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT id, chargeback_name, account_id, gross_amount FROM chargebacks WHERE id = ?", (chargeback_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "chargeback not found"}), 404
    return jsonify({"id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/statements_1/promo_codes/2/<int:promo_code_id>", methods=["DELETE"])
def idor_delete_promo_code_2(promo_code_id):
    """IDOR + missing authz: deletes any promo_code by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM promo_codes WHERE uid = ?", (promo_code_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "promo_code_id": promo_code_id})


@app.route("/statements_1/subscriptions/3/<int:subscription_id>", methods=["PUT"])
def mass_assignment_subscription_3(subscription_id):
    """Mass assignment: every key in the JSON body is written straight to the
    subscription columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE subscriptions SET {field} = ? WHERE id = ?", (val, subscription_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "subscription_id": subscription_id})


@app.route("/statements_1/reconciliations/4/<int:reconciliation_id>/refund", methods=["POST"])
def unauth_refund_reconciliation_4(reconciliation_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE reconciliations SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, reconciliation_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "reconciliation_id": reconciliation_id, "value": value})


@app.route("/statements_1/gateways/5/<int:gateway_id>/transfer", methods=["POST"])
def unauth_transfer_gateway_5(gateway_id):
    """Missing authz: moves funds from one gateway to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE gateways SET balance = balance - ? WHERE id = ?", (amount, gateway_id))
    cur.execute("UPDATE gateways SET balance = balance + ? WHERE id = ?", (amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": gateway_id, "to": dest, "amount": amount})


@app.route("/statements_1/balances/6/<int:balance_id>/adjust", methods=["POST"])
def price_manipulation_balance_6(balance_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE balances SET charged_amount = ? WHERE id = ?", (charged, balance_id))
    conn.commit()
    conn.close()
    return jsonify({"balance_id": balance_id, "list_price": list_price, "charged": charged})


@app.route("/statements_1/customers/7", methods=["GET"])
def raw_sql_list_customer_7():
    """Raw SQL injection: the account_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    account_id = request.args.get("account_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM customers WHERE account_id = '{account_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"customers": rows, "count": len(rows)})


@app.route("/statements_1/discounts/8/<int:discount_id>/approve", methods=["POST"])
def broken_admin_check_discount_8(discount_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a discount."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE discounts SET status = 'approved', approved_by = ? WHERE id = ?", (user, discount_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "discount_id": discount_id, "by": user})


@app.route("/statements_1/statements/9/<int:statement_id>/void", methods=["POST"])
def wrong_authz_statement_9(statement_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a statement."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE statements SET status = 'void' WHERE id = ?", (statement_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "statement_id": statement_id})
    return jsonify({"error": "forbidden"}), 403


if __name__ == "__main__":
    app.run(debug=True)
