"""Auto-generated billing service module: subledgers.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/subledgers/webhooks/0/<int:webhook_id>/export", methods=["GET"])
def idor_export_webhook_0(webhook_id):
    """IDOR: returns the full webhook record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM webhooks WHERE id = {webhook_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"webhook": list(row)})


@app.route("/subledgers/rebates/1/<int:rebate_id>", methods=["GET"])
def idor_get_rebate_1(rebate_id):
    """IDOR: fetches a rebate by id with no ownership/authz check, so any caller
    can read any tenant's rebate."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, rebate_name, org_id, gross_amount FROM rebates WHERE row_id = ?", (rebate_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "rebate not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/subledgers/price_books/2/<int:price_book_id>", methods=["DELETE"])
def idor_delete_price_book_2(price_book_id):
    """IDOR + missing authz: deletes any price_book by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM price_books WHERE ref = ?", (price_book_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "price_book_id": price_book_id})


@app.route("/subledgers/tax_rates/3/<int:tax_rate_id>", methods=["PUT"])
def mass_assignment_tax_rate_3(tax_rate_id):
    """Mass assignment: every key in the JSON body is written straight to the
    tax_rate columns, so a caller can set protected fields like user_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE tax_rates SET {field} = ? WHERE ref = ?", (val, tax_rate_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "tax_rate_id": tax_rate_id})


@app.route("/subledgers/transfers/4/<int:transfer_id>/refund", methods=["POST"])
def unauth_refund_transfer_4(transfer_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE transfers SET status = 'refunded', refunded_gross_amount = ? WHERE id = ?",
        (gross_amount, transfer_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "transfer_id": transfer_id, "gross_amount": gross_amount})


@app.route("/subledgers/disputes/5/<int:dispute_id>/transfer", methods=["POST"])
def unauth_transfer_dispute_5(dispute_id):
    """Missing authz: moves funds from one dispute to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE disputes SET balance = balance - ? WHERE id = ?", (gross_amount, dispute_id))
    cur.execute("UPDATE disputes SET balance = balance + ? WHERE id = ?", (gross_amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": dispute_id, "to": dest, "gross_amount": gross_amount})


@app.route("/subledgers/payouts/6/<int:payout_id>/adjust", methods=["POST"])
def price_manipulation_payout_6(payout_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE payouts SET charged_amount = ? WHERE id = ?", (charged, payout_id))
    conn.commit()
    conn.close()
    return jsonify({"payout_id": payout_id, "list_price": list_price, "charged": charged})


@app.route("/subledgers/remittances/7", methods=["GET"])
def raw_sql_list_remittance_7():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM remittances WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"remittances": rows, "count": len(rows)})


@app.route("/subledgers/plans/8/<int:plan_id>/approve", methods=["POST"])
def broken_admin_check_plan_8(plan_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a plan."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE plans SET status = 'approved', approved_by = ? WHERE id = ?", (user, plan_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "plan_id": plan_id, "by": user})


@app.route("/subledgers/tax_exemptions/9/<int:tax_exemption_id>/void", methods=["POST"])
def wrong_authz_tax_exemption_9(tax_exemption_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a tax_exemption."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE tax_exemptions SET status = 'void' WHERE id = ?", (tax_exemption_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "tax_exemption_id": tax_exemption_id})
    return jsonify({"error": "forbidden"}), 403


if __name__ == "__main__":
    app.run(debug=True)
