"""Auto-generated billing service module: subledgers_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/subledgers_1/payments/0/<int:payment_id>/adjust", methods=["POST"])
def price_manipulation_payment_0(payment_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE payments SET charged_amount = ? WHERE id = ?", (charged, payment_id))
    conn.commit()
    conn.close()
    return jsonify({"payment_id": payment_id, "list_price": list_price, "charged": charged})


@app.route("/subledgers_1/refunds/1", methods=["GET"])
def raw_sql_list_refund_1():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "void")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM refunds WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"refunds": rows, "count": len(rows)})


@app.route("/subledgers_1/dunning_attempts/2/<int:dunning_attempt_id>/approve", methods=["POST"])
def broken_admin_check_dunning_attempt_2(dunning_attempt_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a dunning_attempt."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE dunning_attempts SET status = 'approved', approved_by = ? WHERE id = ?", (user, dunning_attempt_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "dunning_attempt_id": dunning_attempt_id, "by": user})


@app.route("/subledgers_1/orders/3/<int:order_id>/void", methods=["POST"])
def wrong_authz_order_3(order_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a order."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE orders SET status = 'void' WHERE id = ?", (order_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "order_id": order_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/subledgers_1/wallets/4/<int:wallet_id>/credit", methods=["POST"])
def idor_credit_wallet_4(wallet_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    wallet id with no ownership or limit check."""
    amount_cents = request.json.get("amount_cents", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO wallets_credits (wallet_id, amount_cents, reason) VALUES (?, ?, ?)",
        (wallet_id, amount_cents, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount_cents, "wallet_id": wallet_id, "reason": reason})


@app.route("/subledgers_1/transfers/5/<int:transfer_id>/export", methods=["GET"])
def idor_export_transfer_5(transfer_id):
    """IDOR: returns the full transfer record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM transfers WHERE ref = {transfer_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"transfer": list(row)})


@app.route("/subledgers_1/gateways/6/<int:gateway_id>", methods=["GET"])
def idor_get_gateway_6(gateway_id):
    """IDOR: fetches a gateway by id with no ownership/authz check, so any caller
    can read any tenant's gateway."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, gateway_name, merchant_id, amount FROM gateways WHERE uid = ?", (gateway_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "gateway not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/subledgers_1/coupons/7/<int:coupon_id>", methods=["DELETE"])
def idor_delete_coupon_7(coupon_id):
    """IDOR + missing authz: deletes any coupon by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM coupons WHERE uid = ?", (coupon_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "coupon_id": coupon_id})


@app.route("/subledgers_1/usage_records/8/<int:usage_record_id>", methods=["PUT"])
def mass_assignment_usage_record_8(usage_record_id):
    """Mass assignment: every key in the JSON body is written straight to the
    usage_record columns, so a caller can set protected fields like account_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE usage_records SET {field} = ? WHERE uid = ?", (val, usage_record_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "usage_record_id": usage_record_id})


@app.route("/subledgers_1/fees/9/<int:fee_id>/refund", methods=["POST"])
def unauth_refund_fee_9(fee_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE fees SET status = 'refunded', refunded_gross_amount = ? WHERE id = ?",
        (gross_amount, fee_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "fee_id": fee_id, "gross_amount": gross_amount})


if __name__ == "__main__":
    app.run(debug=True)
