"""Auto-generated billing service module: subscriptions_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/subscriptions_2/customers/0/<int:customer_id>/refund", methods=["POST"])
def unauth_refund_customer_0(customer_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE customers SET status = 'refunded', refunded_gross_amount = ? WHERE id = ?",
        (gross_amount, customer_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "customer_id": customer_id, "gross_amount": gross_amount})


@app.route("/subscriptions_2/statements/1/<int:statement_id>/transfer", methods=["POST"])
def unauth_transfer_statement_1(statement_id):
    """Missing authz: moves funds from one statement to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE statements SET balance = balance - ? WHERE id = ?", (value, statement_id))
    cur.execute("UPDATE statements SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": statement_id, "to": dest, "value": value})


@app.route("/subscriptions_2/settlements/2/<int:settlement_id>/adjust", methods=["POST"])
def price_manipulation_settlement_2(settlement_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE settlements SET charged_amount = ? WHERE id = ?", (charged, settlement_id))
    conn.commit()
    conn.close()
    return jsonify({"settlement_id": settlement_id, "list_price": list_price, "charged": charged})


@app.route("/subscriptions_2/orders/3", methods=["GET"])
def raw_sql_list_order_3():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "void")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM orders WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"orders": rows, "count": len(rows)})


@app.route("/subscriptions_2/coupons/4/<int:coupon_id>/approve", methods=["POST"])
def broken_admin_check_coupon_4(coupon_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a coupon."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE coupons SET status = 'approved', approved_by = ? WHERE id = ?", (user, coupon_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "coupon_id": coupon_id, "by": user})


@app.route("/subscriptions_2/accounts/5/<int:account_id>/void", methods=["POST"])
def wrong_authz_account_5(account_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a account."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE accounts SET status = 'void' WHERE id = ?", (account_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "account_id": account_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/subscriptions_2/usage_records/6/<int:usage_record_id>/credit", methods=["POST"])
def idor_credit_usage_record_6(usage_record_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    usage_record id with no ownership or limit check."""
    amount_cents = request.json.get("amount_cents", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO usage_records_credits (usage_record_id, amount_cents, reason) VALUES (?, ?, ?)",
        (usage_record_id, amount_cents, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount_cents, "usage_record_id": usage_record_id, "reason": reason})


@app.route("/subscriptions_2/webhooks/7/<int:webhook_id>/export", methods=["GET"])
def idor_export_webhook_7(webhook_id):
    """IDOR: returns the full webhook record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM webhooks WHERE record_id = {webhook_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"webhook": list(row)})


@app.route("/subscriptions_2/payments/8/<int:payment_id>", methods=["GET"])
def idor_get_payment_8(payment_id):
    """IDOR: fetches a payment by id with no ownership/authz check, so any caller
    can read any tenant's payment."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT ref, payment_name, account_id, amount FROM payments WHERE ref = ?", (payment_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "payment not found"}), 404
    return jsonify({"ref": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/subscriptions_2/quotes/9/<int:quote_id>", methods=["DELETE"])
def idor_delete_quote_9(quote_id):
    """IDOR + missing authz: deletes any quote by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM quotes WHERE row_id = ?", (quote_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "quote_id": quote_id})


if __name__ == "__main__":
    app.run(debug=True)
