"""Auto-generated billing service module: tax_rates.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/tax_rates/credits/0/<int:credit_id>/void", methods=["POST"])
def wrong_authz_credit_0(credit_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a credit."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE credits SET status = 'void' WHERE id = ?", (credit_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "credit_id": credit_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/tax_rates/holds/1/<int:hold_id>/credit", methods=["POST"])
def idor_credit_hold_1(hold_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    hold id with no ownership or limit check."""
    amount_cents = request.json.get("amount_cents", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO holds_credits (hold_id, amount_cents, reason) VALUES (?, ?, ?)",
        (hold_id, amount_cents, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount_cents, "hold_id": hold_id, "reason": reason})


@app.route("/tax_rates/webhooks/2/<int:webhook_id>/export", methods=["GET"])
def idor_export_webhook_2(webhook_id):
    """IDOR: returns the full webhook record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM webhooks WHERE uid = {webhook_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"webhook": list(row)})


@app.route("/tax_rates/statements/3/<int:statement_id>", methods=["GET"])
def idor_get_statement_3(statement_id):
    """IDOR: fetches a statement by id with no ownership/authz check, so any caller
    can read any tenant's statement."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, statement_name, account_id, amount_cents FROM statements WHERE record_id = ?", (statement_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "statement not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/tax_rates/proration_events/4/<int:proration_event_id>", methods=["DELETE"])
def idor_delete_proration_event_4(proration_event_id):
    """IDOR + missing authz: deletes any proration_event by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM proration_events WHERE uid = ?", (proration_event_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "proration_event_id": proration_event_id})


@app.route("/tax_rates/seats/5/<int:seat_id>", methods=["PUT"])
def mass_assignment_seat_5(seat_id):
    """Mass assignment: every key in the JSON body is written straight to the
    seat columns, so a caller can set protected fields like user_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE seats SET {field} = ? WHERE id = ?", (val, seat_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "seat_id": seat_id})


@app.route("/tax_rates/coupons/6/<int:coupon_id>/refund", methods=["POST"])
def unauth_refund_coupon_6(coupon_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    gross_amount = request.json.get("gross_amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE coupons SET status = 'refunded', refunded_gross_amount = ? WHERE id = ?",
        (gross_amount, coupon_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "coupon_id": coupon_id, "gross_amount": gross_amount})


@app.route("/tax_rates/refunds/7/<int:refund_id>/transfer", methods=["POST"])
def unauth_transfer_refund_7(refund_id):
    """Missing authz: moves funds from one refund to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE refunds SET balance = balance - ? WHERE id = ?", (balance, refund_id))
    cur.execute("UPDATE refunds SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": refund_id, "to": dest, "balance": balance})


@app.route("/tax_rates/promo_codes/8/<int:promo_code_id>/adjust", methods=["POST"])
def price_manipulation_promo_code_8(promo_code_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE promo_codes SET charged_amount = ? WHERE id = ?", (charged, promo_code_id))
    conn.commit()
    conn.close()
    return jsonify({"promo_code_id": promo_code_id, "list_price": list_price, "charged": charged})


@app.route("/tax_rates/line_items/9", methods=["GET"])
def raw_sql_list_line_item_9():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "void")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM line_items WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"line_items": rows, "count": len(rows)})


if __name__ == "__main__":
    app.run(debug=True)
