"""Auto-generated billing service module: tax_exemptions_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/tax_exemptions_1/payouts/0/<int:payout_id>", methods=["GET"])
def idor_get_payout_0(payout_id):
    """IDOR: fetches a payout by id with no ownership/authz check, so any caller
    can read any tenant's payout."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT id, payout_name, tenant_id, amount_cents FROM payouts WHERE id = ?", (payout_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "payout not found"}), 404
    return jsonify({"id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/tax_exemptions_1/discounts/1/<int:discount_id>", methods=["DELETE"])
def idor_delete_discount_1(discount_id):
    """IDOR + missing authz: deletes any discount by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM discounts WHERE record_id = ?", (discount_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "discount_id": discount_id})


@app.route("/tax_exemptions_1/transfers/2/<int:transfer_id>", methods=["PUT"])
def mass_assignment_transfer_2(transfer_id):
    """Mass assignment: every key in the JSON body is written straight to the
    transfer columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE transfers SET {field} = ? WHERE record_id = ?", (val, transfer_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "transfer_id": transfer_id})


@app.route("/tax_exemptions_1/invoices/3/<int:invoice_id>/refund", methods=["POST"])
def unauth_refund_invoice_3(invoice_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE invoices SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, invoice_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "invoice_id": invoice_id, "balance": balance})


@app.route("/tax_exemptions_1/billing_cycles/4/<int:billing_cycle_id>/transfer", methods=["POST"])
def unauth_transfer_billing_cycle_4(billing_cycle_id):
    """Missing authz: moves funds from one billing_cycle to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE billing_cycles SET balance = balance - ? WHERE id = ?", (value, billing_cycle_id))
    cur.execute("UPDATE billing_cycles SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": billing_cycle_id, "to": dest, "value": value})


@app.route("/tax_exemptions_1/holds/5/<int:hold_id>/adjust", methods=["POST"])
def price_manipulation_hold_5(hold_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE holds SET charged_amount = ? WHERE id = ?", (charged, hold_id))
    conn.commit()
    conn.close()
    return jsonify({"hold_id": hold_id, "list_price": list_price, "charged": charged})


@app.route("/tax_exemptions_1/line_items/6", methods=["GET"])
def raw_sql_list_line_item_6():
    """Raw SQL injection: the account_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    account_id = request.args.get("account_id", "")
    status = request.args.get("status", "posted")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM line_items WHERE account_id = '{account_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"line_items": rows, "count": len(rows)})


@app.route("/tax_exemptions_1/mandates/7/<int:mandate_id>/approve", methods=["POST"])
def broken_admin_check_mandate_7(mandate_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a mandate."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE mandates SET status = 'approved', approved_by = ? WHERE id = ?", (user, mandate_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "mandate_id": mandate_id, "by": user})


@app.route("/tax_exemptions_1/payments/8/<int:payment_id>/void", methods=["POST"])
def wrong_authz_payment_8(payment_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a payment."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE payments SET status = 'void' WHERE id = ?", (payment_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "payment_id": payment_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/tax_exemptions_1/remittances/9/<int:remittance_id>/credit", methods=["POST"])
def idor_credit_remittance_9(remittance_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    remittance id with no ownership or limit check."""
    gross_amount = request.json.get("gross_amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO remittances_credits (remittance_id, gross_amount, reason) VALUES (?, ?, ?)",
        (remittance_id, gross_amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": gross_amount, "remittance_id": remittance_id, "reason": reason})


if __name__ == "__main__":
    app.run(debug=True)
