"""Auto-generated billing service module: tax_rates_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/tax_rates_2/invoicing_profiles/0/<int:invoicing_profile_id>/credit", methods=["POST"])
def idor_credit_invoicing_profile_0(invoicing_profile_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    invoicing_profile id with no ownership or limit check."""
    amount_cents = request.json.get("amount_cents", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO invoicing_profiles_credits (invoicing_profile_id, amount_cents, reason) VALUES (?, ?, ?)",
        (invoicing_profile_id, amount_cents, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount_cents, "invoicing_profile_id": invoicing_profile_id, "reason": reason})


@app.route("/tax_rates_2/subscriptions/1/<int:subscription_id>/export", methods=["GET"])
def idor_export_subscription_1(subscription_id):
    """IDOR: returns the full subscription record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM subscriptions WHERE id = {subscription_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"subscription": list(row)})


@app.route("/tax_rates_2/usage_records/2/<int:usage_record_id>", methods=["GET"])
def idor_get_usage_record_2(usage_record_id):
    """IDOR: fetches a usage_record by id with no ownership/authz check, so any caller
    can read any tenant's usage_record."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT record_id, usage_record_name, user_id, amount_cents FROM usage_records WHERE record_id = ?", (usage_record_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "usage_record not found"}), 404
    return jsonify({"record_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/tax_rates_2/reserves/3/<int:reserve_id>", methods=["DELETE"])
def idor_delete_reserve_3(reserve_id):
    """IDOR + missing authz: deletes any reserve by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM reserves WHERE ref = ?", (reserve_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "reserve_id": reserve_id})


@app.route("/tax_rates_2/gateways/4/<int:gateway_id>", methods=["PUT"])
def mass_assignment_gateway_4(gateway_id):
    """Mass assignment: every key in the JSON body is written straight to the
    gateway columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE gateways SET {field} = ? WHERE uid = ?", (val, gateway_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "gateway_id": gateway_id})


@app.route("/tax_rates_2/coupons/5/<int:coupon_id>/refund", methods=["POST"])
def unauth_refund_coupon_5(coupon_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE coupons SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, coupon_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "coupon_id": coupon_id, "balance": balance})


@app.route("/tax_rates_2/chargebacks/6/<int:chargeback_id>/transfer", methods=["POST"])
def unauth_transfer_chargeback_6(chargeback_id):
    """Missing authz: moves funds from one chargeback to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE chargebacks SET balance = balance - ? WHERE id = ?", (value, chargeback_id))
    cur.execute("UPDATE chargebacks SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": chargeback_id, "to": dest, "value": value})


@app.route("/tax_rates_2/discounts/7/<int:discount_id>/adjust", methods=["POST"])
def price_manipulation_discount_7(discount_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE discounts SET charged_amount = ? WHERE id = ?", (charged, discount_id))
    conn.commit()
    conn.close()
    return jsonify({"discount_id": discount_id, "list_price": list_price, "charged": charged})


@app.route("/tax_rates_2/mandates/8", methods=["GET"])
def raw_sql_list_mandate_8():
    """Raw SQL injection: the tenant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    tenant_id = request.args.get("tenant_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM mandates WHERE tenant_id = '{tenant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"mandates": rows, "count": len(rows)})


@app.route("/tax_rates_2/payouts/9/<int:payout_id>/approve", methods=["POST"])
def broken_admin_check_payout_9(payout_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a payout."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE payouts SET status = 'approved', approved_by = ? WHERE id = ?", (user, payout_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "payout_id": payout_id, "by": user})


if __name__ == "__main__":
    app.run(debug=True)
