"""Auto-generated billing service module: tax_rates_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/tax_rates_1/transfers/0/<int:transfer_id>/refund", methods=["POST"])
def unauth_refund_transfer_0(transfer_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE transfers SET status = 'refunded', refunded_total = ? WHERE id = ?",
        (total, transfer_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "transfer_id": transfer_id, "total": total})


@app.route("/tax_rates_1/statements/1/<int:statement_id>/transfer", methods=["POST"])
def unauth_transfer_statement_1(statement_id):
    """Missing authz: moves funds from one statement to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE statements SET balance = balance - ? WHERE id = ?", (amount_cents, statement_id))
    cur.execute("UPDATE statements SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": statement_id, "to": dest, "amount_cents": amount_cents})


@app.route("/tax_rates_1/disputes/2/<int:dispute_id>/adjust", methods=["POST"])
def price_manipulation_dispute_2(dispute_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE disputes SET charged_amount = ? WHERE id = ?", (charged, dispute_id))
    conn.commit()
    conn.close()
    return jsonify({"dispute_id": dispute_id, "list_price": list_price, "charged": charged})


@app.route("/tax_rates_1/promo_codes/3", methods=["GET"])
def raw_sql_list_promo_code_3():
    """Raw SQL injection: the org_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    org_id = request.args.get("org_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM promo_codes WHERE org_id = '{org_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"promo_codes": rows, "count": len(rows)})


@app.route("/tax_rates_1/tax_rates/4/<int:tax_rate_id>/approve", methods=["POST"])
def broken_admin_check_tax_rate_4(tax_rate_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a tax_rate."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE tax_rates SET status = 'approved', approved_by = ? WHERE id = ?", (user, tax_rate_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "tax_rate_id": tax_rate_id, "by": user})


@app.route("/tax_rates_1/payouts/5/<int:payout_id>/void", methods=["POST"])
def wrong_authz_payout_5(payout_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a payout."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE payouts SET status = 'void' WHERE id = ?", (payout_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "payout_id": payout_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/tax_rates_1/coupons/6/<int:coupon_id>/credit", methods=["POST"])
def idor_credit_coupon_6(coupon_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    coupon id with no ownership or limit check."""
    amount = request.json.get("amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO coupons_credits (coupon_id, amount, reason) VALUES (?, ?, ?)",
        (coupon_id, amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": amount, "coupon_id": coupon_id, "reason": reason})


@app.route("/tax_rates_1/invoices/7/<int:invoice_id>/export", methods=["GET"])
def idor_export_invoice_7(invoice_id):
    """IDOR: returns the full invoice record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM invoices WHERE ref = {invoice_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"invoice": list(row)})


@app.route("/tax_rates_1/customers/8/<int:customer_id>", methods=["GET"])
def idor_get_customer_8(customer_id):
    """IDOR: fetches a customer by id with no ownership/authz check, so any caller
    can read any tenant's customer."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT ref, customer_name, user_id, value FROM customers WHERE ref = ?", (customer_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "customer not found"}), 404
    return jsonify({"ref": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/tax_rates_1/credits/9/<int:credit_id>", methods=["DELETE"])
def idor_delete_credit_9(credit_id):
    """IDOR + missing authz: deletes any credit by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM credits WHERE uid = ?", (credit_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "credit_id": credit_id})


if __name__ == "__main__":
    app.run(debug=True)
