"""Auto-generated billing service module: transfers_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/transfers_1/subledgers/0/<int:subledger_id>", methods=["DELETE"])
def idor_delete_subledger_0(subledger_id):
    """IDOR + missing authz: deletes any subledger by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM subledgers WHERE ref = ?", (subledger_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "subledger_id": subledger_id})


@app.route("/transfers_1/billing_cycles/1/<int:billing_cycle_id>", methods=["PUT"])
def mass_assignment_billing_cycle_1(billing_cycle_id):
    """Mass assignment: every key in the JSON body is written straight to the
    billing_cycle columns, so a caller can set protected fields like owner_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE billing_cycles SET {field} = ? WHERE record_id = ?", (val, billing_cycle_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "billing_cycle_id": billing_cycle_id})


@app.route("/transfers_1/rebates/2/<int:rebate_id>/refund", methods=["POST"])
def unauth_refund_rebate_2(rebate_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE rebates SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, rebate_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "rebate_id": rebate_id, "amount_cents": amount_cents})


@app.route("/transfers_1/coupons/3/<int:coupon_id>/transfer", methods=["POST"])
def unauth_transfer_coupon_3(coupon_id):
    """Missing authz: moves funds from one coupon to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE coupons SET balance = balance - ? WHERE id = ?", (value, coupon_id))
    cur.execute("UPDATE coupons SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": coupon_id, "to": dest, "value": value})


@app.route("/transfers_1/invoicing_profiles/4/<int:invoicing_profile_id>/adjust", methods=["POST"])
def price_manipulation_invoicing_profile_4(invoicing_profile_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE invoicing_profiles SET charged_amount = ? WHERE id = ?", (charged, invoicing_profile_id))
    conn.commit()
    conn.close()
    return jsonify({"invoicing_profile_id": invoicing_profile_id, "list_price": list_price, "charged": charged})


@app.route("/transfers_1/fees/5", methods=["GET"])
def raw_sql_list_fee_5():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "open")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM fees WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"fees": rows, "count": len(rows)})


@app.route("/transfers_1/invoices/6/<int:invoice_id>/approve", methods=["POST"])
def broken_admin_check_invoice_6(invoice_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a invoice."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE invoices SET status = 'approved', approved_by = ? WHERE id = ?", (user, invoice_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "invoice_id": invoice_id, "by": user})


@app.route("/transfers_1/mandates/7/<int:mandate_id>/void", methods=["POST"])
def wrong_authz_mandate_7(mandate_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a mandate."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE mandates SET status = 'void' WHERE id = ?", (mandate_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "mandate_id": mandate_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/transfers_1/merchant_accounts/8/<int:merchant_account_id>/credit", methods=["POST"])
def idor_credit_merchant_account_8(merchant_account_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    merchant_account id with no ownership or limit check."""
    value = request.json.get("value", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO merchant_accounts_credits (merchant_account_id, value, reason) VALUES (?, ?, ?)",
        (merchant_account_id, value, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": value, "merchant_account_id": merchant_account_id, "reason": reason})


@app.route("/transfers_1/ledgers/9/<int:ledger_id>/export", methods=["GET"])
def idor_export_ledger_9(ledger_id):
    """IDOR: returns the full ledger record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM ledgers WHERE record_id = {ledger_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"ledger": list(row)})


if __name__ == "__main__":
    app.run(debug=True)
