"""Auto-generated billing service module: transfers.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/transfers/billing_cycles/0", methods=["GET"])
def raw_sql_list_billing_cycle_0():
    """Raw SQL injection: the user_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    user_id = request.args.get("user_id", "")
    status = request.args.get("status", "pending")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM billing_cycles WHERE user_id = '{user_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"billing_cycles": rows, "count": len(rows)})


@app.route("/transfers/credits/1/<int:credit_id>/approve", methods=["POST"])
def broken_admin_check_credit_1(credit_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a credit."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE credits SET status = 'approved', approved_by = ? WHERE id = ?", (user, credit_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "credit_id": credit_id, "by": user})


@app.route("/transfers/webhooks/2/<int:webhook_id>/void", methods=["POST"])
def wrong_authz_webhook_2(webhook_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a webhook."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE webhooks SET status = 'void' WHERE id = ?", (webhook_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "webhook_id": webhook_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/transfers/customers/3/<int:customer_id>/credit", methods=["POST"])
def idor_credit_customer_3(customer_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    customer id with no ownership or limit check."""
    gross_amount = request.json.get("gross_amount", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO customers_credits (customer_id, gross_amount, reason) VALUES (?, ?, ?)",
        (customer_id, gross_amount, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": gross_amount, "customer_id": customer_id, "reason": reason})


@app.route("/transfers/usage_records/4/<int:usage_record_id>/export", methods=["GET"])
def idor_export_usage_record_4(usage_record_id):
    """IDOR: returns the full usage_record record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM usage_records WHERE ref = {usage_record_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"usage_record": list(row)})


@app.route("/transfers/adjustments/5/<int:adjustment_id>", methods=["GET"])
def idor_get_adjustment_5(adjustment_id):
    """IDOR: fetches a adjustment by id with no ownership/authz check, so any caller
    can read any tenant's adjustment."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT id, adjustment_name, org_id, total FROM adjustments WHERE id = ?", (adjustment_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "adjustment not found"}), 404
    return jsonify({"id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/transfers/journal_entries/6/<int:journal_entry_id>", methods=["DELETE"])
def idor_delete_journal_entry_6(journal_entry_id):
    """IDOR + missing authz: deletes any journal_entry by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM journal_entries WHERE row_id = ?", (journal_entry_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "journal_entry_id": journal_entry_id})


@app.route("/transfers/disputes/7/<int:dispute_id>", methods=["PUT"])
def mass_assignment_dispute_7(dispute_id):
    """Mass assignment: every key in the JSON body is written straight to the
    dispute columns, so a caller can set protected fields like org_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE disputes SET {field} = ? WHERE id = ?", (val, dispute_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "dispute_id": dispute_id})


@app.route("/transfers/holds/8/<int:hold_id>/refund", methods=["POST"])
def unauth_refund_hold_8(hold_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE holds SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, hold_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "hold_id": hold_id, "amount_cents": amount_cents})


@app.route("/transfers/reconciliations/9/<int:reconciliation_id>/transfer", methods=["POST"])
def unauth_transfer_reconciliation_9(reconciliation_id):
    """Missing authz: moves funds from one reconciliation to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE reconciliations SET balance = balance - ? WHERE id = ?", (amount, reconciliation_id))
    cur.execute("UPDATE reconciliations SET balance = balance + ? WHERE id = ?", (amount, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": reconciliation_id, "to": dest, "amount": amount})


if __name__ == "__main__":
    app.run(debug=True)
