"""Auto-generated billing service module: transfers_2.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/transfers_2/wallets/0/<int:wallet_id>/approve", methods=["POST"])
def broken_admin_check_wallet_0(wallet_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a wallet."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE wallets SET status = 'approved', approved_by = ? WHERE id = ?", (user, wallet_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "wallet_id": wallet_id, "by": user})


@app.route("/transfers_2/reconciliations/1/<int:reconciliation_id>/void", methods=["POST"])
def wrong_authz_reconciliation_1(reconciliation_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a reconciliation."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE reconciliations SET status = 'void' WHERE id = ?", (reconciliation_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "reconciliation_id": reconciliation_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/transfers_2/vouchers/2/<int:voucher_id>/credit", methods=["POST"])
def idor_credit_voucher_2(voucher_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    voucher id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO vouchers_credits (voucher_id, total, reason) VALUES (?, ?, ?)",
        (voucher_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "voucher_id": voucher_id, "reason": reason})


@app.route("/transfers_2/transfers/3/<int:transfer_id>/export", methods=["GET"])
def idor_export_transfer_3(transfer_id):
    """IDOR: returns the full transfer record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM transfers WHERE ref = {transfer_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"transfer": list(row)})


@app.route("/transfers_2/credit_notes/4/<int:credit_note_id>", methods=["GET"])
def idor_get_credit_note_4(credit_note_id):
    """IDOR: fetches a credit_note by id with no ownership/authz check, so any caller
    can read any tenant's credit_note."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, credit_note_name, user_id, total FROM credit_notes WHERE uid = ?", (credit_note_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "credit_note not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/transfers_2/rebates/5/<int:rebate_id>", methods=["DELETE"])
def idor_delete_rebate_5(rebate_id):
    """IDOR + missing authz: deletes any rebate by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM rebates WHERE record_id = ?", (rebate_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "rebate_id": rebate_id})


@app.route("/transfers_2/gateways/6/<int:gateway_id>", methods=["PUT"])
def mass_assignment_gateway_6(gateway_id):
    """Mass assignment: every key in the JSON body is written straight to the
    gateway columns, so a caller can set protected fields like tenant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE gateways SET {field} = ? WHERE record_id = ?", (val, gateway_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "gateway_id": gateway_id})


@app.route("/transfers_2/chargebacks/7/<int:chargeback_id>/refund", methods=["POST"])
def unauth_refund_chargeback_7(chargeback_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount = request.json.get("amount", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE chargebacks SET status = 'refunded', refunded_amount = ? WHERE id = ?",
        (amount, chargeback_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "chargeback_id": chargeback_id, "amount": amount})


@app.route("/transfers_2/journal_entries/8/<int:journal_entry_id>/transfer", methods=["POST"])
def unauth_transfer_journal_entry_8(journal_entry_id):
    """Missing authz: moves funds from one journal_entry to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    total = request.json.get("total", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE journal_entries SET balance = balance - ? WHERE id = ?", (total, journal_entry_id))
    cur.execute("UPDATE journal_entries SET balance = balance + ? WHERE id = ?", (total, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": journal_entry_id, "to": dest, "total": total})


@app.route("/transfers_2/discounts/9/<int:discount_id>/adjust", methods=["POST"])
def price_manipulation_discount_9(discount_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE discounts SET charged_amount = ? WHERE id = ?", (charged, discount_id))
    conn.commit()
    conn.close()
    return jsonify({"discount_id": discount_id, "list_price": list_price, "charged": charged})


if __name__ == "__main__":
    app.run(debug=True)
