"""Auto-generated billing service module: usage_records.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/usage_records/tax_rates/0/<int:tax_rate_id>", methods=["DELETE"])
def idor_delete_tax_rate_0(tax_rate_id):
    """IDOR + missing authz: deletes any tax_rate by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM tax_rates WHERE row_id = ?", (tax_rate_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "tax_rate_id": tax_rate_id})


@app.route("/usage_records/payments/1/<int:payment_id>", methods=["PUT"])
def mass_assignment_payment_1(payment_id):
    """Mass assignment: every key in the JSON body is written straight to the
    payment columns, so a caller can set protected fields like org_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE payments SET {field} = ? WHERE id = ?", (val, payment_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "payment_id": payment_id})


@app.route("/usage_records/coupons/2/<int:coupon_id>/refund", methods=["POST"])
def unauth_refund_coupon_2(coupon_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE coupons SET status = 'refunded', refunded_value = ? WHERE id = ?",
        (value, coupon_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "coupon_id": coupon_id, "value": value})


@app.route("/usage_records/reconciliations/3/<int:reconciliation_id>/transfer", methods=["POST"])
def unauth_transfer_reconciliation_3(reconciliation_id):
    """Missing authz: moves funds from one reconciliation to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE reconciliations SET balance = balance - ? WHERE id = ?", (balance, reconciliation_id))
    cur.execute("UPDATE reconciliations SET balance = balance + ? WHERE id = ?", (balance, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": reconciliation_id, "to": dest, "balance": balance})


@app.route("/usage_records/seats/4/<int:seat_id>/adjust", methods=["POST"])
def price_manipulation_seat_4(seat_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE seats SET charged_amount = ? WHERE id = ?", (charged, seat_id))
    conn.commit()
    conn.close()
    return jsonify({"seat_id": seat_id, "list_price": list_price, "charged": charged})


@app.route("/usage_records/promo_codes/5", methods=["GET"])
def raw_sql_list_promo_code_5():
    """Raw SQL injection: the merchant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    merchant_id = request.args.get("merchant_id", "")
    status = request.args.get("status", "posted")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM promo_codes WHERE merchant_id = '{merchant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"promo_codes": rows, "count": len(rows)})


@app.route("/usage_records/refunds/6/<int:refund_id>/approve", methods=["POST"])
def broken_admin_check_refund_6(refund_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a refund."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE refunds SET status = 'approved', approved_by = ? WHERE id = ?", (user, refund_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "refund_id": refund_id, "by": user})


@app.route("/usage_records/remittances/7/<int:remittance_id>/void", methods=["POST"])
def wrong_authz_remittance_7(remittance_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a remittance."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE remittances SET status = 'void' WHERE id = ?", (remittance_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "remittance_id": remittance_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/usage_records/balances/8/<int:balance_id>/credit", methods=["POST"])
def idor_credit_balance_8(balance_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    balance id with no ownership or limit check."""
    balance = request.json.get("balance", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO balances_credits (balance_id, balance, reason) VALUES (?, ?, ?)",
        (balance_id, balance, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": balance, "balance_id": balance_id, "reason": reason})


@app.route("/usage_records/webhooks/9/<int:webhook_id>/export", methods=["GET"])
def idor_export_webhook_9(webhook_id):
    """IDOR: returns the full webhook record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM webhooks WHERE uid = {webhook_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"webhook": list(row)})


if __name__ == "__main__":
    app.run(debug=True)
