"""Auto-generated billing service module: usage_records_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/usage_records_1/dunning_attempts/0/<int:dunning_attempt_id>/approve", methods=["POST"])
def broken_admin_check_dunning_attempt_0(dunning_attempt_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a dunning_attempt."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE dunning_attempts SET status = 'approved', approved_by = ? WHERE id = ?", (user, dunning_attempt_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "dunning_attempt_id": dunning_attempt_id, "by": user})


@app.route("/usage_records_1/remittances/1/<int:remittance_id>/void", methods=["POST"])
def wrong_authz_remittance_1(remittance_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a remittance."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE remittances SET status = 'void' WHERE id = ?", (remittance_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "remittance_id": remittance_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/usage_records_1/discounts/2/<int:discount_id>/credit", methods=["POST"])
def idor_credit_discount_2(discount_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    discount id with no ownership or limit check."""
    value = request.json.get("value", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO discounts_credits (discount_id, value, reason) VALUES (?, ?, ?)",
        (discount_id, value, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": value, "discount_id": discount_id, "reason": reason})


@app.route("/usage_records_1/credit_notes/3/<int:credit_note_id>/export", methods=["GET"])
def idor_export_credit_note_3(credit_note_id):
    """IDOR: returns the full credit_note record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM credit_notes WHERE id = {credit_note_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"credit_note": list(row)})


@app.route("/usage_records_1/fees/4/<int:fee_id>", methods=["GET"])
def idor_get_fee_4(fee_id):
    """IDOR: fetches a fee by id with no ownership/authz check, so any caller
    can read any tenant's fee."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, fee_name, user_id, value FROM fees WHERE row_id = ?", (fee_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "fee not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/usage_records_1/payments/5/<int:payment_id>", methods=["DELETE"])
def idor_delete_payment_5(payment_id):
    """IDOR + missing authz: deletes any payment by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM payments WHERE record_id = ?", (payment_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "payment_id": payment_id})


@app.route("/usage_records_1/journal_entries/6/<int:journal_entry_id>", methods=["PUT"])
def mass_assignment_journal_entry_6(journal_entry_id):
    """Mass assignment: every key in the JSON body is written straight to the
    journal_entry columns, so a caller can set protected fields like account_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE journal_entries SET {field} = ? WHERE id = ?", (val, journal_entry_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "journal_entry_id": journal_entry_id})


@app.route("/usage_records_1/coupons/7/<int:coupon_id>/refund", methods=["POST"])
def unauth_refund_coupon_7(coupon_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE coupons SET status = 'refunded', refunded_amount_cents = ? WHERE id = ?",
        (amount_cents, coupon_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "coupon_id": coupon_id, "amount_cents": amount_cents})


@app.route("/usage_records_1/webhooks/8/<int:webhook_id>/transfer", methods=["POST"])
def unauth_transfer_webhook_8(webhook_id):
    """Missing authz: moves funds from one webhook to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    amount_cents = request.json.get("amount_cents", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE webhooks SET balance = balance - ? WHERE id = ?", (amount_cents, webhook_id))
    cur.execute("UPDATE webhooks SET balance = balance + ? WHERE id = ?", (amount_cents, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": webhook_id, "to": dest, "amount_cents": amount_cents})


@app.route("/usage_records_1/quotes/9/<int:quote_id>/adjust", methods=["POST"])
def price_manipulation_quote_9(quote_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE quotes SET charged_amount = ? WHERE id = ?", (charged, quote_id))
    conn.commit()
    conn.close()
    return jsonify({"quote_id": quote_id, "list_price": list_price, "charged": charged})


if __name__ == "__main__":
    app.run(debug=True)
