"""Auto-generated billing service module: vouchers_1.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/vouchers_1/credit_notes/0/<int:credit_note_id>/export", methods=["GET"])
def idor_export_credit_note_0(credit_note_id):
    """IDOR: returns the full credit_note record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM credit_notes WHERE ref = {credit_note_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"credit_note": list(row)})


@app.route("/vouchers_1/fees/1/<int:fee_id>", methods=["GET"])
def idor_get_fee_1(fee_id):
    """IDOR: fetches a fee by id with no ownership/authz check, so any caller
    can read any tenant's fee."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT row_id, fee_name, owner_id, amount_cents FROM fees WHERE row_id = ?", (fee_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "fee not found"}), 404
    return jsonify({"row_id": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/vouchers_1/adjustments/2/<int:adjustment_id>", methods=["DELETE"])
def idor_delete_adjustment_2(adjustment_id):
    """IDOR + missing authz: deletes any adjustment by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM adjustments WHERE id = ?", (adjustment_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "adjustment_id": adjustment_id})


@app.route("/vouchers_1/payouts/3/<int:payout_id>", methods=["PUT"])
def mass_assignment_payout_3(payout_id):
    """Mass assignment: every key in the JSON body is written straight to the
    payout columns, so a caller can set protected fields like merchant_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE payouts SET {field} = ? WHERE uid = ?", (val, payout_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "payout_id": payout_id})


@app.route("/vouchers_1/discounts/4/<int:discount_id>/refund", methods=["POST"])
def unauth_refund_discount_4(discount_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE discounts SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, discount_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "discount_id": discount_id, "balance": balance})


@app.route("/vouchers_1/dunning_attempts/5/<int:dunning_attempt_id>/transfer", methods=["POST"])
def unauth_transfer_dunning_attempt_5(dunning_attempt_id):
    """Missing authz: moves funds from one dunning_attempt to an arbitrary destination
    chosen by the caller, with no ownership or admin check."""
    dest = request.json.get("destination_id")
    value = request.json.get("value", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE dunning_attempts SET balance = balance - ? WHERE id = ?", (value, dunning_attempt_id))
    cur.execute("UPDATE dunning_attempts SET balance = balance + ? WHERE id = ?", (value, dest))
    conn.commit()
    conn.close()
    return jsonify({"from": dunning_attempt_id, "to": dest, "value": value})


@app.route("/vouchers_1/subledgers/6/<int:subledger_id>/adjust", methods=["POST"])
def price_manipulation_subledger_6(subledger_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE subledgers SET charged_amount = ? WHERE id = ?", (charged, subledger_id))
    conn.commit()
    conn.close()
    return jsonify({"subledger_id": subledger_id, "list_price": list_price, "charged": charged})


@app.route("/vouchers_1/vouchers/7", methods=["GET"])
def raw_sql_list_voucher_7():
    """Raw SQL injection: the tenant_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    tenant_id = request.args.get("tenant_id", "")
    status = request.args.get("status", "captured")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM vouchers WHERE tenant_id = '{tenant_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"vouchers": rows, "count": len(rows)})


@app.route("/vouchers_1/line_items/8/<int:line_item_id>/approve", methods=["POST"])
def broken_admin_check_line_item_8(line_item_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a line_item."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE line_items SET status = 'approved', approved_by = ? WHERE id = ?", (user, line_item_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "line_item_id": line_item_id, "by": user})


@app.route("/vouchers_1/webhooks/9/<int:webhook_id>/void", methods=["POST"])
def wrong_authz_webhook_9(webhook_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a webhook."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE webhooks SET status = 'void' WHERE id = ?", (webhook_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "webhook_id": webhook_id})
    return jsonify({"error": "forbidden"}), 403


if __name__ == "__main__":
    app.run(debug=True)
