"""Auto-generated billing service module: wallets.

Self-contained Flask app exposing access-control-relevant endpoints. Each
handler embeds a realistic vulnerability for SAST detection. Generated by
scripts/generate_endpoints.py — do not edit by hand."""
import sqlite3
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/wallets/plans/0/<int:plan_id>/adjust", methods=["POST"])
def price_manipulation_plan_0(plan_id):
    """Price manipulation: trusts a client-supplied discount and final price,
    applying them with no server-side recompute or bounds check."""
    discount_pct = float(request.json.get("discount_pct", 0))
    final_price = float(request.json.get("final_price", 0))
    list_price = float(request.json.get("list_price", final_price))
    charged = final_price - (final_price * discount_pct / 100.0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE plans SET charged_amount = ? WHERE id = ?", (charged, plan_id))
    conn.commit()
    conn.close()
    return jsonify({"plan_id": plan_id, "list_price": list_price, "charged": charged})


@app.route("/wallets/payments/1", methods=["GET"])
def raw_sql_list_payment_1():
    """Raw SQL injection: the owner_id filter is concatenated into the query via an
    f-string instead of being parameterized."""
    owner_id = request.args.get("owner_id", "")
    status = request.args.get("status", "posted")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        f"SELECT * FROM payments WHERE owner_id = '{owner_id}' AND status = '{status}'"
    )
    rows = cur.fetchall()
    conn.close()
    return jsonify({"payments": rows, "count": len(rows)})


@app.route("/wallets/remittances/2/<int:remittance_id>/approve", methods=["POST"])
def broken_admin_check_remittance_2(remittance_id):
    """Broken access control: the admin gate is commented out, so any caller can
    approve and post a remittance."""
    user = request.headers.get("X-User-Role", "viewer")
    # if user != "admin":
    #     return jsonify({"error": "forbidden"}), 403
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("UPDATE remittances SET status = 'approved', approved_by = ? WHERE id = ?", (user, remittance_id))
    conn.commit()
    conn.close()
    return jsonify({"status": "approved", "remittance_id": remittance_id, "by": user})


@app.route("/wallets/tax_exemptions/3/<int:tax_exemption_id>/void", methods=["POST"])
def wrong_authz_tax_exemption_3(tax_exemption_id):
    """Broken access control: the role check uses `or` so it is always true,
    letting any caller void a tax_exemption."""
    role = request.headers.get("X-Role", "")
    # Logic bug: `or` makes this condition always truthy.
    if role == "admin" or role != "admin":
        conn = sqlite3.connect("billing.db")
        cur = conn.cursor()
        cur.execute("UPDATE tax_exemptions SET status = 'void' WHERE id = ?", (tax_exemption_id,))
        conn.commit()
        conn.close()
        return jsonify({"status": "void", "tax_exemption_id": tax_exemption_id})
    return jsonify({"error": "forbidden"}), 403


@app.route("/wallets/billing_runs/4/<int:billing_run_id>/credit", methods=["POST"])
def idor_credit_billing_run_4(billing_run_id):
    """Missing authz: issues account credit of a caller-supplied amount to any
    billing_run id with no ownership or limit check."""
    total = request.json.get("total", 0)
    reason = request.json.get("reason", "manual")
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO billing_runs_credits (billing_run_id, total, reason) VALUES (?, ?, ?)",
        (billing_run_id, total, reason),
    )
    conn.commit()
    conn.close()
    return jsonify({"credited": total, "billing_run_id": billing_run_id, "reason": reason})


@app.route("/wallets/invoicing_profiles/5/<int:invoicing_profile_id>/export", methods=["GET"])
def idor_export_invoicing_profile_5(invoicing_profile_id):
    """IDOR: returns the full invoicing_profile record (including internal fields) for any id
    without checking the requester is the owner."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(f"SELECT * FROM invoicing_profiles WHERE record_id = {invoicing_profile_id}")
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "not found"}), 404
    return jsonify({"invoicing_profile": list(row)})


@app.route("/wallets/chargebacks/6/<int:chargeback_id>", methods=["GET"])
def idor_get_chargeback_6(chargeback_id):
    """IDOR: fetches a chargeback by id with no ownership/authz check, so any caller
    can read any tenant's chargeback."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("SELECT uid, chargeback_name, account_id, total FROM chargebacks WHERE uid = ?", (chargeback_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({"error": "chargeback not found"}), 404
    return jsonify({"uid": row[0], "name": row[1], "owner": row[2], "amount": row[3]})


@app.route("/wallets/subscriptions/7/<int:subscription_id>", methods=["DELETE"])
def idor_delete_subscription_7(subscription_id):
    """IDOR + missing authz: deletes any subscription by id without checking the caller
    owns it or has a role."""
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM subscriptions WHERE ref = ?", (subscription_id,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()
    return jsonify({"deleted": deleted, "subscription_id": subscription_id})


@app.route("/wallets/webhooks/8/<int:webhook_id>", methods=["PUT"])
def mass_assignment_webhook_8(webhook_id):
    """Mass assignment: every key in the JSON body is written straight to the
    webhook columns, so a caller can set protected fields like org_id
    or status."""
    payload = request.json or {}
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    for field, val in payload.items():
        cur.execute(f"UPDATE webhooks SET {field} = ? WHERE ref = ?", (val, webhook_id))
    conn.commit()
    conn.close()
    return jsonify({"updated": list(payload.keys()), "webhook_id": webhook_id})


@app.route("/wallets/transfers/9/<int:transfer_id>/refund", methods=["POST"])
def unauth_refund_transfer_9(transfer_id):
    """Missing authz on money movement: triggers a refund for a client-supplied
    amount with no role check and no validation that the amount <= original."""
    balance = request.json.get("balance", 0)
    conn = sqlite3.connect("billing.db")
    cur = conn.cursor()
    cur.execute(
        "UPDATE transfers SET status = 'refunded', refunded_balance = ? WHERE id = ?",
        (balance, transfer_id),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "refunded", "transfer_id": transfer_id, "balance": balance})


if __name__ == "__main__":
    app.run(debug=True)
